### ISSUE TITLE
Allow for more Currency Thousands Separator options

### ISSUE THREAD

**Issue by joshfeck** [eventespresso/event-espresso-core#1042]
Some countries do not use a comma or a point for their thousands separator, so for some sites the desired currency format isn't available. Some currencies use a small space (Czech Koruna, Swedish Krona), others use an apostrophe `'`(Swiss Franc). 

Customer requests:
https://eventespresso.com/topic/currency-thousands-seperator-change-in-apostrophe/
https://eventespresso.com/topic/bug-price-of-ticket-is-multiplied-by-10-when-updating-an-event/

**Comment by tn3rb** [comment]
these changes will need to be made to both the initial database data as well as to logic in the general settings countries tab

**Comment by tn3rb** [comment]
related note: just discovered that the currency sign for Serbia is missing. It should be `РСД`

**Comment by tn3rb** [comment]
so turns out:

- default currency data is added to the `wp_esp_country` table in `EE_DMS_Core_4_1_0::insert_default_countries()`, but that does NOT specify values for the `CNT_cur_dec_mrk` or `CNT_cur_thsnds` fields 

- the easiest way to fix the above, would be to edit the table directly using phpMyAdmin or similar app and add the correct values wherever they are known, then export the SQL for the table and replace what's in `EE_DMS_Core_4_1_0`. This would only fix new installs. To fix existing installs would require an actual DMS to run during the next activation

- regardless of whether the above is done or not, new values will need to be added to the available options in the Countries tab in the general settings admin so that users can edit any incorrect values or account for differences in localization below the country level (like Quebec Canada using different values than the rest of Canada).

- the ideal solution for the Countries admin options would be to use radio buttons for known values, and then have an option for "other"
that reveals a text input where the user could enter anything they want

**Comment by joshfeck** [comment]
an option for displaying a small space for thousands separator was added in #2563

**Comment by tn3rb** [comment]
@hoseinrafiei 

similar to what was done in #2563 can you add the following options to the `Currency Thousands Separator` in the Countries admin:

- _ (underscore)
- ' (apostrophe)
