### ISSUE TITLE
single_page_checkout.css is overriding theme css

### ISSUE THREAD

**Issue by designabyss** [eventespresso/event-espresso-core#105]
I am working with a custom theme.

Initially detected the issue while changing a css property by overriding it in theme css file.

**File:** modules/single_page_checkout/css/single_page_checkout.css
**Class:** .spco-whats-next-buttons

**Screenshot**

![image](https://cloud.githubusercontent.com/assets/8544814/9121724/8fc2b6a4-3c9d-11e5-94a3-27278f89c6fd.png)

**Comment by nerrad** [comment]
Hi there, we need more info other than a title.  What theme are you seeing this with?  What css styles are being overridden? What examples do you have illustrating this?

**Comment by tn3rb** [comment]
just add the class of a parent id to your css selector in your theme.css file and your styles will stick.

ie:

```
.some-parent-element-class-name .spco-what's-next-buttons {
    text-align:right;
}
```

more specific css selectors will override less specific css selectors, so the above is more specific than the existing style set in the spco css.

PLZ NOTE, that it is more performant to use the closest selector to the element you want to affect. So for example, using :+1: 

```
body .spco-what's-next-buttons {
    text-align:right;
}
```

would be really inefficient because your browser would have to travel up the entire DOM to confirm whether or not *.spco-what's-next-buttons* belonged to *body*

**Comment by designabyss** [comment]
Thank you, targeting with the ID also did the trick
