### ISSUE TITLE
Create table component

### ISSUE THREAD

**Issue by joshfeck** [eventespresso/event-espresso-core#1057]
- [x] Accessible
- [x] mobile friendly
- [ ]Need to still convert a few tables over to use this component

- [ ] possibly add drag and drop reordering functionality

**Comment by tn3rb** [comment]
done and passed off for review, although no unit tests or documentation yet

**Comment by tn3rb** [comment]
The Ticket Assignments Manager is one of the components that utilizes the new table component. It can be navigated via the keyboard and follows best practices with regards to accessibility, although there's likely improvements that can be made. 

I want to add drag and drop reordering functionality to it, so that it can be used for that purpose as well.

Here's a screenshot of the Ticket Assignments Manager, which doesn't really show the table much since ultimately it is just an HTML table.

![Ticket Assignments Manager](https://user-images.githubusercontent.com/1751030/57402886-249b5d80-718d-11e9-9d7f-d4ca7b8aa6d5.png)

and here is a screenshot of the table's HTML markup showing the proper use of the table caption plus roles and scopes.

![Responsive Table Markup](https://user-images.githubusercontent.com/1751030/57404109-0b47e080-7190-11e9-88e5-e895a670aac5.png)

Html tables are already quite accessible since screen readers have had ages to figure out how to use them and there is only a little bit of extra help needed to make them fully accessible. This fact alone eliminated more than a couple of existing React table libraries because they were using `div`s plus CSS to simulate tables, which pretty much makes it impossible for screen readers to handle that tabular data in the same way as an actual table. Of the other table libraries I Looked at, none of the ones that utilized HTML tables were responsive as they all hardcoded the cell widths into the markup, which forces users to have to scroll horizontally as well as vertically in order to view the data.

This component utilizes media queries to convert how the table is displayed. Essentially the column headers are repeated in the first cell of every row but hidden from screen readers as well as non mobile users, but displayed on mobile while hiding the regular headers. This means mobile users simply have to scroll vertically to read the data and always have the headings visible.

**Comment by tn3rb** [comment]
closing this because the table component has been completed for a while now, and #1527 addresses the drag n drop reordering issue.
