### ISSUE TITLE
"PAY_gateway_response" is hard-coded as an empty string when processing the function "apply_payments_or_refunds"

### ISSUE THREAD

**Issue by nvphuc1989** [eventespresso/event-espresso-core#112]
Hi EE team,

I have added Capture and Refund features in admin transaction details for our gateway plugin. After requested the capture/refund from the gateway, it will update the current transaction by requesting an Ajax action **espresso_apply_payment**. I have found that **PAY_gateway_response** parameter is hard-coded as an empty string when processing the function **apply_payments_or_refunds** at server side. Please suggest. Thanks!
https://github.com/eventespresso/event-espresso-core/blob/master/admin_pages/transactions/Transactions_Admin_Page.core.php#L989

**Comment by mnelson4** [comment]
hi nvphuc1989, that method you're looking at, `apply_payments_or_refunds`, is intended for just recording payments (made somehow in a separate system), but not for actually processing payments (sending information to the gateway in order for them to actually withdraw the funds from the user's account). Admin-side payment processing is a feature the payment method classes themselves should be able to handle, but we haven't yet built the user interface for it. Also admin-side refunds is another feature the gateways should be able to support, but we haven't yet built a user interface for.
So the reason the `PAY_gateway_response` is hard-coded is because in `apply_payments_or_refunds` we don't intend to actually interact with the gateway server or receive any response from them.
Does that make sense?

For your project do you need to be able to process payments in the admin? And do you need to be able to process refunds from the admin?

**Comment by nvphuc1989** [comment]
Yes Mike Nelson, our gateway supports capture (for Preauth method) and refund features in admin.
You mean I can trigger the function **process_payment/process_refund** to add payment/refund in EE_PMT_My_Gateway_Onsite.pm class?
I used the Ajax action **espresso_apply_payment** just because it handles everything such as update payment transactions, change statuses, send email notification...
Please share any example if you have. Thanks!

**Comment by mnelson4** [comment]
> You mean I can trigger the function process_payment/process_refund to add payment/refund in EE_PMT_My_Gateway_Onsite.pm class?

yes you can use those, although it would be best to go through `EE_Payment_Processor::process_payment` and `EE_Payment_Processor::process_refund` in order to invoke the related logic like sending messages, updating transactions and registrations etc.

> Please share any example if you have.

sorry there are currently no examples of processing refunds. If you want to add support for that the following would need to be added to core:
- [ ] add a UI for processing the payment/refunds in the transaction page (similar to the "apply payments" modal dialogue, but it would need to also show the payment method's billing form)
- [ ] add a route onto Transactions_Admin_Page, similar to `espresso_apply_payment` and its corresponding callback `process_payment_sor_refunds`
- [ ] inside that route's callback, validate the form submission, and then if valid use `EE_Payment_Processor::process_payment` or `EE_Payment_Processor::process_refund` according to what the user requested
- [ ] verify the payment's process_payment/process_refund methods are invoked correctly, transactions and reistrations are updated correctly, and messages are delivered
- [ ] update the transactions page like how the "apply payments" modal dialogue does to show the new payment

we hope to get around to doing this, but there are a lot of other priorities at the moment. feel free to open a pull request with the above though if you can!

**Comment by nvphuc1989** [comment]
Thanks Mike Nelson, I'm getting the error that `EE_Payment_Processor::process_payment` and `EE_Payment_Processor::process_refund` should not be called
 statically. Could you please advise?

**Comment by mnelson4** [comment]
yes they're singletons so you should actually call them as `EE_Payment_Processor::instance()->process_refund(...)` etc, ie first get the instance and then call the method on it. We have quite a lot of singletons like that in EE.

**Comment by nvphuc1989** [comment]
Work like a charm :+1:. For the notification, I have to use `apply_filters( 'FHEE__EE_Admin_Page___process_admin_payment_notification__success', FALSE, $payment );`
Thanks a ton for your support!

**Comment by mnelson4** [comment]
so have you added admin-side payment processing and payment refunds to a branch of core? If so we'd love a pull request adding those features to core.

**Comment by nvphuc1989** [comment]
I have used WP function `add_meta_box` for the UI for simplicity. I need to get more understanding of EE core before adding those features to core :)

**Comment by mnelson4** [comment]
ya adding those features to core isn't terribly difficult but it's certainly not a trivial job (which is why we haven't gotten around to doing it yet).
Ok well let me know if you need any more feedback on this matter (and how we could improve our documentation) and it would be nice to see what you've built once you're done.
But it sounds like this is resolved
