### ISSUE TITLE
Get registration details after successfull registration

### ISSUE THREAD

**Issue by msyadav88** [eventespresso/event-espresso-core#116]
I am trying to get the registration details after successful registration using EE_Registration::new_instance()->get_primary_registration() , but its giving me 0 value for all fields.

add_action('AHEE__EE_Registration_Processor__trigger_registration_update_notifications','createpage');
function createpage(){
	$registration = EE_Registration::new_instance()->get_primary_registration();
	$s = $registration->get('ATT_ID');
	file_put_contents(ABSPATH.'log.txt','testing'.$s);
}

Here the $s gives 0 value. So is there any issue in the hook or any other hook should be use to get the registration details?

**Comment by nerrad** [comment]
Hi there,

There's a couple errors in your example:

1. The `AHEE__EE_Registration_Processor__trigger_registration_update_notifications` action passes the registration object so no need to instantiate it.

If you look where the action is declared in `EE_Registration_Processor` you'll see this:

```
do_action(
				'AHEE__EE_Registration_Processor__trigger_registration_update_notifications',
				$registration,
				$additional_details
			);
```

So the correct way to implement the action so that you get what you need is to do this:

```
add_action( 'AHEE__EE_Registration_Processor__trigger_registration_update_notifications', 'createpage', 10, 2 );
function createpage( $registration, $additional_details ) {
	if ( $registration instanceof EE_Registration ) {
		//do stuff with the $registration object.
	}
}
```

You can read more about how to use WordPress [actions and filters in their documentation](https://codex.wordpress.org/Plugin_API).

2. Usage of EE_Registration object was wrong.

You may want to check out the developer documentation we've prepared about our model system [over here](http://developer.eventespresso.com/docs/using-ee4-model-objects/).

`EE_Registration` is what we call the `model object` and is the representation of a registration when instantiated from a row of data in the database or from new data by client code.   So you would use `new_instance()` along with data passed in as arguments for the registration to instantiate a **new** EE_Registration model object.

If you wanted to retrieve an _existing_ registration object from the db, then you would want to use the `model` which is `EEM_Registration`.  There is more info in the documentation I linked to.

However, you shouldn't need to use any of those in this particular action callback because as I already pointed out, the `EE_Registration` object is already exposed by the action.

I hope that helps you out :)

**Comment by msyadav88** [comment]
Really this helps me lots, Thanks Nerrad

**Comment by msyadav88** [comment]
Hi Nerrad,

I just want a bit more help from you. I have use ( $registration->get('ATT_ID'); ) to get the value of a specific field relate to the registration , But is there any way to get the whole attendee or registration detail in an array. Because If I want to get the first name of the attendee , I have to first analyse the relation of each table and then have to query sql. I think there should be some function to get the whole attendee details in array. It will be great helpful if you guide me in this.

**Comment by nerrad** [comment]
It turns out the `EE_Registration` object has a number of methods that assist with retrieving info cached on it.

If you wish to get the attendee information you can do so by:

```
$attendee = $registration->attendee()
```

That will return a `EE_Attendee` object for you to use and you can see all the methods in it for the accessible data.
