### ISSUE TITLE
skip a question dynamically on registration form

### ISSUE THREAD

**Issue by msyadav88** [eventespresso/event-espresso-core#118]
I am trying to skip a specific question dynamically on the registration form. Please guide if any function is there.

**Comment by msyadav88** [comment]
Can you please add the filter hook to skip a question or question group on the registration form.

**Comment by tn3rb** [comment]
have a look at the "FHEE__EE_SPCO_Reg_Step_Attendee_Information__question_group_reg_form__subsections_array" filter in \EE_SPCO_Reg_Step_Attendee_Information::_question_group_reg_form().

You'll be able to loop through each of the inputs, and using the other supplied parameters, may find the data you need to determine whether to remove a question from that array.

**Comment by msyadav88** [comment]
Hi,

Thanks for your update. I have found the input to skip but when I return null the whole page is stopped at that point and shows blank. My code is as below, can you have a look at it please.

add_filter ( 'FHEE__EE_SPCO_Reg_Step_Attendee_Information___question_group_reg_form__question_group_reg_form', 'skip_createpage' );
function skip_createpage($question_group_reg_form,$registration, $question_group){
	if(array_key_exists('12',$question_group_reg_form->inputs())){ // 12 is for a question id
		return null;
	}
        return $question_group_reg_form;
}

**Comment by msyadav88** [comment]
Hi,
It got the code working as below:
add_filter ( 'FHEE__EE_SPCO_Reg_Step_Attendee_Information__question_group_reg_form__subsections_array', 'skip_createpage' );
function skip_createpage($subsections,$registration, $question_group){
	if(array_key_exists('12',$subsections)){
		return array();
	}
        return $subsections;
}

But if I put this filter hook in some other action hook say "AHEE__Single_Page_Checkout___initialize_reg_step__attendee_information" , then it not works

Please let me know if we want to add a filter hook in some action hook function , then how to code it.

**Comment by msyadav88** [comment]
Hi,

Sorry, i have used that filter hook in other action hook called "AHEE__SPCO__before_registration_steps" not "AHEE__Single_Page_Checkout___initialize_reg_step__attendee_information"

**Comment by tn3rb** [comment]
ummm ... it looks like your filter callback well remove question 12 from ALL registration forms. If that's what you want to do, then you can simply remove that question from within the WordPress Admin, by going to Event Espresso > Registration Form > Question Groups tab.
then find which question group has that question added to it, and simply uncheck it.

Regarding the filter callback function not working when you change the filter it is attached to... that would be expected behaviour. Please see https://codex.wordpress.org/Plugin_API for more information about how to use Actions and Filters
