### ISSUE TITLE
Fix issues with display strategy for Payment Methods Settings page

### ISSUE THREAD

**Issue by joshfeck** [eventespresso/event-espresso-core#1181]
I was looking over the source of the payment methods settings page in an attempt to troubleshoot some of the inputs overflowing outside of the container and spotted what appears to be mismatched closing td & tr elements:

![Screen Shot 2019-04-30 at 3 07 22 PM](https://user-images.githubusercontent.com/891156/57102662-05ff1780-6cf2-11e9-81b3-43c54b3c60fd.png)

I asked in chat and Darren found that the extra tr&td's are coming from EEH_HTML::no_row() called by `EE_Admin_Two_Column_Layout`. "It appears there's a clash between using the `EE_Admin_Two_Column_Layout_Strategy` and the injection of rows and cells happening in the `Payments_Admin_Page::_generate_payment_method_settings_form`.  Basically not following the expecting incoming values for the `label/input` expectations for the layout strategy." The structure is ending up with something like this: (no styles or classes for clarity)

```
<tr>
    <td >
        <tr>
            <td>
                Authorize.Net AIM is an on-site payment method for accepting credit and debit card payments and is available to event organizers in the United States, Canada, United Kingdom, and Australia. An account with Authorize.Net is required to accept payments. Need an Authorize.Net account? <a href="https://eventespresso.com/go/authorizenetaim/" target="_blank">Click here to sign up for a merchant account</a>.
            </td>
        </tr>
        <tr>
            <th>
                <label >Click to Activate </label>
            </th>
            <td>
                <a href="https://ee.test/wp-admin/admin.php?page=espresso_payment_settings&action=activate_payment_method&payment_method_type=Aim&activate_payment_method_nonce=ed55379308" id="activate_aim" class="espresso-button-green button-primary" title="Activate Authorize.net AIM Payment Method?">Activate Authorize.net AIM Payment Method?</a>
            </td>
        </tr>
    </td>
</tr>
```

Brent noted that "if you change the `layout_strategy` in  `_generate_payment_method_settings_form()` to `new EE_No_Layout()` it fixes that issue but messes up some of the layout for other things" 
> another potentially better fix is to change `\EE_Admin_Two_Column_Layout::layout_subsection()` to:

```
public function layout_subsection($form_section)
    {
        if ($form_section instanceof EE_Form_Section_Proper ) {
            return EEH_HTML::no_row($form_section->get_html());
        }
        if ( $form_section instanceof EE_Form_Section_HTML ) {
            return $form_section->get_html();
        }
        return '';
    }
```

> then the payments form does not require any other fixes, because it is already handling it's own HTML i think the latter makes more sense because if a form section is using `EE_Form_Section_HTML` then it is kinda implied that it is handling its own HTML and should not have further markup added but that would require all other forms using `EE_Admin_Two_Column_Layout` to be checked over for breakage due to that change
my guess would be that most things would work better with thatt change though

**Comment by tn3rb** [comment]
two possible fixes:

- change the `layout_strategy` in  `_generate_payment_method_settings_form()` to `new EE_No_Layout()` which fixes the issue, but messes up some of the layout for other things and will require additional changes to the payment settings form

- or a potentially better fix is to change `\EE_Admin_Two_Column_Layout::layout_subsection()` to:

```
    public function layout_subsection($form_section)
    {
        if ($form_section instanceof EE_Form_Section_Proper ) {
            return EEH_HTML::no_row($form_section->get_html());
        }
        if ( $form_section instanceof EE_Form_Section_HTML ) {
            return $form_section->get_html();
        }
        return '';
    }
```

then the payments form does not require any other fixes, because it is already handling it's own HTML.

i think the latter makes more sense because if a form section is using `EE_Form_Section_HTML`
then it is kinda implied that it is handling its own HTML and should not have further markup added
but that would require all other forms using `EE_Admin_Two_Column_Layout` to be checked over for breakage due to that change

my guess would be that most things would work better with the latter change option though

**Comment by mnelson4** [comment]
comment is WIP...

Ya I agree the latter change is better, and consistent with how `EE_Two_Column_Layout`, EE_Admin_One_Column_Layout` works.
Negatively Affected forms (ones that DON'T add tr and td tags):

* `\EventEspresso\AttendeeMover\form\VerifyChanges`
* `\EventEspresso\admin_pages\general_settings\AdminOptionsSettings::_generate()`
* `\EventEspresso\admin_pages\general_settings\OrganizationSettings::generate()`
* `\Maintenance_Admin_Page::_get_datetime_offset_fix_form`
* `\Extend_Registration_Form_Admin_Page::_email_validation_settings_form`
* `\EED_Bot_Trap::_bot_trap_settings_form`
* `\EventEspresso\modules\invalid_checkout_access\InvalidCheckoutAccess::getForm`
* `\EE_SPCO_Reg_Step_Attendee_Information::_question_group_reg_form` because on frontend it uses `EE_Div_Per_Section_Layout` (where html subsections should NOT add tr and td tags) but on the backend it uses
* all the forms from the attendee importer
* `\espresso_events_Infusionsoft_Hooks::generateForm`
* `\Infusionsoft_Admin_Page::_generate_question_mapping_form`
* `\Infusionsoft_Admin_Page::_generate_conditional_tagging_form`
* `\EE_MC_Interest_Categories_Form::_template_setup`
* `\EE_MC_Lists_Form::_template_setup`
* `\EE_MC_Merge_Fields_Form::_template_setup`
* `\EED_Stripe_Connect_OAuth_Middleman::add_stripe_connect_button`



Positive Affected forms (ones that add tr and td tags themselves):
* \EE_Stripe_OAuth_Form::_oauth_form_contents`
* `\Payments_Admin_Page::_generate_payment_method_settings_form`
* `\Payments_Admin_Page::_activate_payment_method_button`
* `\Registrations_Admin_Page::_generate_reg_status_change_form`
* `\EE_Infusionsoft_PM_Form`
* `\EED_Payment_Methods_Pro_More_Payment_Methods::add_buttons_onto_payment_settings_forms`

search for form section htmlits default
sections, inputs, and even html sections should be agnostic to their parent form (if any). Eg you should be able to change a parents display strategy dynamically (which we do in the base form section, and `\EE_SPCO_Reg_Step_Attendee_Information::_question_group_reg_form`). If you want to have content outside of a table, but the rest inside it, use a templated layout, or no layout and then subsections using a table-based layout.

That's how it was before https://github.com/eventespresso/event-espresso-core/commit/7ca157a3a0b (for ticket https://events.codebasehq.com/projects/event-espresso/tickets/6573).

**Comment by tn3rb** [comment]
ya ok I can support your conclusions. I wasn't positive whether the suggestion to change `EE_Admin_Two_Column_Layout::layout_subsection()` would actually end up being easier, which is why I called it "potentially better". It certainly seemed like a better choice initially since the payment methods would then not require any other changes, but that obviously requires far more changes for other code, so yeah... not so good after all.

Good work doing all of that research first!

Now that said, does that mean that ALL of the code locations you mentioned in the **"Forms where this would be a welcome change"** list have mismatched table tags and are going to require changes like the payment method forms?

If so, we can likely still squeeze them into this issue, but maybe after editing the title a bit.

**Comment by mnelson4** [comment]
> It certainly seemed like a better choice initially...

Agreed, I only switched opinions once I got checking "all other forms using EE_Admin_Two_Column_Layout... for breakage due to that change", and especially when I realized we were dynamically switching layout strategies.

> "Forms where this would be a welcome change" list have mismatched table tags and are going to require changes like the payment method forms?

Yeah, they should all be fixed; it's up for debate whether to make separate issues or not. Although we've gotten by with them being borked for a while, so apparently it's not too big of a deal.

**Comment by mnelson4** [comment]
So, what needs updating:

* [ ] \EE_Stripe_OAuth_Form::_oauth_form_contents`
* [ ] `\Payments_Admin_Page::_pci_dss_compliance`
* [ ] `\Payments_Admin_Page::_generate_payment_method_settings_form`
* [ ] `\Payments_Admin_Page::_activate_payment_method_button` and anywhere else in this class that uses `EE_Form_Section_HTML`
* [ ] `\Registrations_Admin_Page::_generate_reg_status_change_form`
* [ ] `\EE_Infusionsoft_PM_Form`
* [ ] `\EED_Payment_Methods_Pro_More_Payment_Methods::add_buttons_onto_payment_settings_forms`
* [ ] `\EED_Mijireh_Slurper::add_slurp_link_to_gateway` and other methods involving templates
* [ ] `event-espresso-core/payment_methods/Invoice/templates/invoice_settings_header_display.template.php`
* [ ] `event-espresso-core/payment_methods/Invoice/templates/invoice_settings_header_gateway.template.php`
* [ ] `\Registrations_Admin_Page::form_before_question_group` (although it's deprecated)
* [ ] `\Registrations_Admin_Page::form_after_question_group` (also deprecated)

**Comment by mnelson4** [comment]
Ok we now have PRs for each of the known add-ons where `EE_Form_Section_HTML`s were adding tr and td tags themselves. So once #1191 is merged, this should be good.
