### ISSUE TITLE
Archive not honoring earliest(soonest) upcoming datetime

### ISSUE THREAD

**Issue by jonathan-dejong** [eventespresso/event-espresso-core#119]
Hi!

So what I've found is that if for example an even has three datetimes and one of them has passed. It will not be ordered in the query by it's earliest upcoming datetime but rather the latest (it seems). 

More information here: http://eventespresso.com/topic/events-archive-not-honouring-earliest-upcoming-datetime/

So to clarify I'm talking about the actual query for the events in an archive. :)

**Comment by mnelson4** [comment]
Jonathan are you familiar with writing unit tests? Can you write a test that shows the problem? I think that would be helpful.

**Comment by jonathan-dejong** [comment]
Not really. I've done it some time ago but very basic.. There's usually not much use/budget for unit tests for medium large company websites ;) 

But I could see if I can create a screencast demonstrating it?

**Comment by mnelson4** [comment]
Ya those would be useful too

**Comment by joshfeck** [comment]
This may be related to ticket #8967 where the datetime with the lowest ID is actually being used to order the events, which Brent will be committing a fix for shortly.

**Comment by tn3rb** [comment]
so a couple of things... 
first off, if visiting the event list via the CPT endpoint ​*/events/*​, then you are actually using the query params that get injected by the EE_CPT_Event_Strategy. If using a shortcode, THEN you are using EEH_Event_Query.
Turns out EE_CPT_Event_Strategy was using ` GROUP BY post.ID ` to make the event lists not show duplicate events.
So anyways, the problem is kinda an issue with MySQL where using GROUP BY ignores how the query is ordered via the ORDER BY... but only ​*IF*​ there are multiple results for the items being grouped.

So the solution was to use ` MIN( wp_esp_datetime.DTT_EVT_start ) AS 'event_start_date' ` in the SELECT clause, which prevents multiple records being grabbed based on the one to many relationship between events and datetimes.  But that would return only 1 record for the entire query (ie the event with the earliest datetime), so we still need to ` GROUP BY post.ID ` to get each event, and ​*THEN*​ to order the list chronologically, we use ` ORDER BY event_start_date ASC  ` (edited)

so the final query for the events endpoint ends up being:

```
SELECT SQL_CALC_FOUND_ROWS
  wp_posts.*,
  wp_esp_datetime.*,
  MIN(wp_esp_datetime.DTT_EVT_start) AS event_start_date,
  wp_esp_event_meta.*
FROM wp_posts
  INNER JOIN wp_esp_datetime ON (wp_posts.ID = wp_esp_datetime.EVT_ID)
  LEFT JOIN wp_esp_event_meta ON (wp_esp_event_meta.EVT_ID = wp_posts.ID)
WHERE 1 = 1
      AND wp_posts.post_type = 'espresso_events'
      AND (
        wp_posts.post_status = 'publish'
        OR wp_posts.post_status = 'cancelled'
        OR wp_posts.post_status = 'postponed'
        OR wp_posts.post_status = 'sold_out'
        OR wp_posts.post_status = 'private'
      )
      AND wp_esp_datetime.DTT_EVT_end > "2015-10-15 17:49:55"
GROUP BY wp_posts.ID
ORDER BY event_start_date ASC
LIMIT 0, 10
```

although that's pieced together via a gang of filters and such.

@jonathan-dejong 
this fix is off for review and should be merged to master soon.

**Comment by jonathan-dejong** [comment]
I bow my head to you Brent :+1: 

This is above my head in terms of SQL but I'm glad you've worked it out and look forward to the merge!

**Comment by joshfeck** [comment]
This is merged to master and was included in the latest release of Event Espresso 4.
