### ISSUE TITLE
Inserting venue information using $wpdb->insert

### ISSUE THREAD

**Issue by zoee** [eventespresso/event-espresso-core#122]
Hi I posted this on the support forum but was assed to pop it here instead, we’re doing some CRM integration for a client and I am having trouble inserting the venue information. My query is below, my variables are populated correctly as they print out fine if I echo them above this code. However the code just inserts blanks in to the database (except for the Venue ID which inserts fine!).

			$wpdb->insert( 
				$wpdb->prefix.'esp_venue_meta', 
				array( 
					'VNU_ID' => $venue_id,
					'VNU_address' => $venueAddress1, 
					'VNU_address2' => $venueAddress2, $venueAddress3,
					'VNU_city' => $venueCounty,
					'CNT_ISO' => 'GB',
					'VNU_zip' => $venuePostcode,
					'VNU_phone' => $venuePhone,
				),  
				array('%s','%s','%s','%s','%s','%s','%s') 
			);

Any points in the right direction would be very appreciated!!!

Thanks!

**Comment by mnelson4** [comment]
hi @zoee

I see on the line 
`'VNU_address2' => $venueAddress2, $venueAddress3,` should probably be `'VNU_address2' => $venueAddress2 . $venueAddress3,`. That might be causing the problem.
Also `VNU_ID` should probably be sanitized as an integer, so you should use `'%d'` for the datatypes array.


Also, are you also inserting data into the posts table? Because in Event Espresso 4 venue data is partially stored in the posts table as a custom post type, and partially in the esp_venue_meta table.
Also have you read over our model system documentation? http://developer.eventespresso.com/docs/model-querying
You could use the following lines to create a venue (and sanitizes the data for you to a degree), and then get an `EE_Venue` object back, which is handy for display, further data manipulation, working with related data, etc.:

```
$venue_obj = EE_Venue::new_instance( array(
'VNU_address' => $venueAddress1,
'VNU_address2' => $venueAddress2 . $venueAddress3,
'VNU_city' => $venueCounty,
'CNT_ISO' => 'GB',
'VNU_zip' => $venuePostcode,
'VNU_phone' => $venuePhone ) );
$venue_obj->save();
```

**Comment by zoee** [comment]
Ha! thanks - can't beleive I missed that - I changed it when I was testing and forgot to change it back!!!

All working :)
