### ISSUE TITLE
Set Gateway Label

### ISSUE THREAD

**Issue by gabrielmerovingi** [eventespresso/event-espresso-core#125]
While I would love to show my plugins name as the payment gateway label, I really need to have the option in my gateway settings to allow EE users to set this label themselves. Is this possible?

**Comment by tn3rb** [comment]
@gabrielmerovingi 
I'm assuming you closed this because you found the answer to your own question, but just in case you didn't, Yes this is possible.

Our Payment_Method objects have properties for both a Name, which is the publicly view-able label, and an Admin Name, which only appears in the backend to help you differentiate between similar gateways.

If you go to the WP Admin and click on Event Espresso > Payment Methods, and then look at any of the payment methods, you will see fields for those two properties.

**Comment by gabrielmerovingi** [comment]
Yes, apologies for not adding a reason but just as I sent the message it dawned on me that it was infront of me all along. But appreciate your reply.
