### ISSUE TITLE
How to set transaction to "Failed" status in the function "do_direct_payment"

### ISSUE THREAD

**Issue by nvphuc1989** [eventespresso/event-espresso-core#126]
Hi EE team,

I use the function **do_direct_payment** for checking payment status from the gateway then update the statuses in EE system. When payment has been declined, I will set payment status by the following code:
> $this->_pay_model->declined_status()

then the transaction status is set to **Incomplete** by default. But we want the transaction status to be **Failed**. Could you please advise the solution?

**Comment by tn3rb** [comment]
@nvphuc1989 

In EE, much like in many cases in the real world, we don't kill the transaction when there is a failed payment, we simply offer the chance to attempt another payment. If you set the transaction to failed then your site visitors would have to repeat the entire registration process (choose tickets, fill out the reg form, etc) if they want to attempt another payment. It would be like shopping in a store, and bringing all of your items to the checkout to pay, then having to put everything back on the shelf because your credit card was declined. Why not just allow them to retry the payment using a different method? What if they simply made a mistake entering their credit card details? Why repeat the entire process?

Anyways, that said, I really have NO idea how you have things set up, so maybe there is a really great reason for setting the transaction to failed when a payment is declined.

So to answer your question, the first parameter for the do_direct_payment() method should be an instance of EE_Payment (we'll call it $payment but you may have named it something else). After verifying that the incoming parameter is indeed an instance of EE_Payment, you can get it's related transaction from it, and then set the transaction status like this:

```php
// verify $payment isn't null or something
if ( $payment instanceof EE_Payment ) {
	$transaction = $payment->transaction();
	// $payment should always have a related transaction, but this is faster than try catch
	if ( $transaction instanceof EE_Transaction ) {
		$transaction->set_status( EEM_Transaction::failed_status_code );
	}
}
```

hope that helps

**Comment by nvphuc1989** [comment]
Thanks @tn3rb for the explanation and answer.
