### ISSUE TITLE
Can't create new post in save_post hook with EE

### ISSUE THREAD

**Issue by jonathan-dejong** [eventespresso/event-espresso-core#129]
Hi!

I'v got a script setup to create a new sendpress list (newsletters) whenever a new EE event is created.. 
It's all pretty standard. However it does not work and I get this fatal error:
`[03-Nov-2015 13:48:08 UTC] PHP Fatal error:  Call to a member function _add_relation_to() on null in /home/cmbchalmers/public_html/wp-content/plugins/event-espresso-core-reg/caffeinated/admin/new/pricing/espresso_events_Pricing_Hooks.class.php on line 248`

This occurs on the wp_insert_post function.. It seems EE attempts to also hook into my post insertion and since it's not a EE event it fails? 

Any ideas?
Here's the code:

```
/**
 * Hook into saving of a new event
 */
function ee_to_sp_event_saved( $post_id ) {

	// If this is just a revision, don't send the email.
	if ( wp_is_post_revision( $post_id ) )
		return;


	// Lets find out if this is an event
    $post_object = get_post($post_id);

    if($post_object->post_type == 'espresso_events') {

		// Fetch the title
		$post_title = $post_object->post_title;
		$list_title = $post_title.'-'.$post_id;

        $existing_id = check_post_exists($list_title); //Just a custom function which returns true/false if there's already a post with this name.

        error_log('we are here');

        if( !$existing_id ){
	        //we don't have a list yet
	        remove_action('save_post', 'ee_to_sp_event_saved');
	        error_log('action removed');
	        $list_id = wp_insert_post(array(
		        'post_title' => $list_title,
		        'post_type' => 'sendpress_list',
		        'post_status' => 'publish',
		        'comment_status' => 'closed',
		        'ping_status' => 'closed'
	        ));
	        error_log('list created');
	        add_action( 'save_post', 'ee_to_sp_event_saved' );
	        error_log('action added');

	        if( !is_wp_error($list_id) ){

		        error_log('new post!');
		        //Successfully created a new list, now add some meta
		        update_post_meta($list_id, 'public', 0);
		        update_post_meta($list_id, '_test_list', 0);
		        update_post_meta($list_id, 'sync_role', 'meta');
		        update_post_meta($list_id, 'meta-key', 'user_events'); //MUST be the same as the relationship field in ACF
		        update_post_meta($list_id, 'meta-compare', 'LIKE');
		        update_post_meta($list_id, 'meta-value', $post_id);

	        }

        }

    }

}
add_action( 'save_post', 'ee_to_sp_event_saved' );
```

**Comment by nerrad** [comment]
Hi Jonathon,

You've discovered a bug with the EE Admin functionality that hooks into the save_post action.  In our save post callbacks we dont' check for `post_type` because our callbacks are only hooked in on EE CPT routes.  However, as you've discovered, if a plugin author adds code that executes `wp_insert_post` on the same request that one of our CPT's is loaded, then our save_post callback will be executed on that `save_post` called as well.

I've created a ticket for this: https://events.codebasehq.com/projects/event-espresso/tickets/9030  and will be working on it right away.  It's an easy fix so I should have this up soon.

BTW, you may want to consider using `do_action( "save_post_{$post->post_type}", $post_ID, $post, $update );` for your action hooking into the event saves, so something like:

```
add_action( 'save_post_espresso_events', 'callback' );
```

That saves you having to do a post_type check.

**Comment by nerrad** [comment]
@jonathan-dejong if you want to test the fix I just pushed to the BUG-9030-save_post_checks branch that'd be great.  It should resolve the issue you were seeing.

We've got it up for testing now and it hopefully will be merged to master sometime today.

**Comment by jonathan-dejong** [comment]
Hi Darren,

Thanks for the tip! I've used the post type specific hook before but somewhere along the line I forgot about it.. ;) 

Great to hear about the fix! I'll try it out right away

**Comment by jonathan-dejong** [comment]
Works like a charm!
