### ISSUE TITLE
No attendee block styles on the front end?

### ISSUE THREAD

**Issue by Pebblo** [eventespresso/event-espresso-core#1375]
Looks like the Attendee block front end styles aren't loading, for example, if you look here: 

https://ee4m.eventespresso.com/attendee-block-testing/

The UL has a list-style-type of disc but the `ee-block-event-attendees` CSS sets it to none.

If you view the styles that apply on the page above its only styles from the theme.

**Comment by joshfeck** [comment]
I checked a few versions back and found that the styles still loaded with 4.9.81.p. They don't load anymore after switching to the 4.9.82.p release tag.

**Comment by joshfeck** [comment]
This appears to be a regression from #1286 that was missed in testing

https://github.com/eventespresso/event-espresso-core/pull/1286#issuecomment-498824449

**Comment by joshfeck** [comment]
The styles for the attendee block **do** still load on the editor side. @nerrad since this is related to #1286 do you have any ideas why the attendee block styles no longer load on the front end?

**Comment by nerrad** [comment]
Ya it'll be because the dependencies aren't getting automatically derived from the frontend css built.  The automatic dependency extractor added in #1286 goes by what files are in the import tree for a _script_ and doesn't work really well (it indirectly derives what should be built from script handles) with css dependencies.  So for now, the solution is to just manually add the correct dependencies for the frontend blocks _css_ (the js should still be okay).
