### ISSUE TITLE
Conflicts with mz-mindbody-api

### ISSUE THREAD

**Issue by MikeiLL** [eventespresso/event-espresso-core#140]
Looks like a great plugin! I'm having a jQuery conflict with the jquery modal popup in my plugin. Looks like the scripts are being loaded even on pages which aren't showing the schedule. Is that the case?

**Comment by nerrad** [comment]
Hi there,

Unfortunately you haven't given enough information for us to know exactly what the issue is.

What jquery modal popup are you talking about?

Are you able to give an example console message that indicates the conflict?

When you refer to "schedule" what exactly are you referring to?

We'd like to help, but we'll need more info before we can.

Thanks!

**Comment by MikeiLL** [comment]
Thanks for the reply, Dave.

I’m referring to the jQuery modal pop-up in my plugin.

If I disable all of the event-espresso plugins except on pages where they are being used:

		'espresso-calendar/espresso-calendar.php',
		'espresso-custom-templates/index.php',
		'espresso-members/espresso-members.php',
		'espresso-permissions-basic/espresso-permissions.php',
		'espresso-recurring/espresso-recurring-events.php',
		'espresso-social/espresso-social.php',
		'event-espresso/espresso.php',
		'event-espresso-core/espresso.php’

Then the jQuery conflict disappears on the other pages. Seems like it would be ideal if the above plugin files were only being loaded on pages that needed them.

Please forgive my ignorance as I haven’t gotten to know the suite of event espresso plugins very well yet.

Mike

**Comment by nerrad** [comment]
It's Darren actually,

Mike, unfortunately it's still not clear to me what exactly your issue is.  We can't really help you until we know the answers to the question I originally asked.

In WordPress it is _normal_ for a plugin's main file to be loaded, that's how WordPress plugins work.  So your response doesn't really help at all.  At the very least, can you give me more specifics about what "jQuery conflict" you are talking about?  The output in the browser console would be useful in that case.

Also you state this:

> If I disable all of the event-espresso plugins except on pages where they are being used:

How exactly are you doing that?

**Comment by MikeiLL** [comment]
Hi Darren.

You’re totally right. What I meant to suggest was only loading plugin assets on pages where they were needed, and I’m not completely sure which plugins are loading which assets, as I have neither the premium plugins nor access to the server they are running on.

The conflict I’m seeing is in the console:

	TypeError: $ is not a function

Which I believe is common in jQuery conflicts.

I’m disabling the event-espresso plugins with a small mu-plugin which basically removes specified files from the wp $plugins  (as returned by option_active_plugins), unless the URL (`$_SERVER['REQUEST_URI’]`) contains specified strings.

I have every expectation that there’s a better way of handling it than this, but it does seems to be resolving the conflict on pages where my plugin is utilizing jQuery modal - via color box.

**Comment by joshfeck** [comment]
When you look at the console, there should also be a filename with a line number that points to where it's throwing the TypeError: $ is not a function error. 

I took a look and it appears that you can avoid conflicts in your plugin's JavaScript files by changing it everywhere you have this:

`$(document).ready(function($) {`

to this instead:

`jQuery(document).ready(function($) {`

See also:

https://digwp.com/2011/09/using-instead-of-jquery-in-wordpress/

**Comment by MikeiLL** [comment]
Of course! I had used:

	(function($) {

		//using $(document).ready(function($) here

	})( jQuery );

in some places, but forgot it in others.

Thank you very much.

Is it possible for me to get development copies of the event-espresso plugins for testing or do I need to wait (one week) until the client returns from holiday?

Mike


Michael Kilmer
Media Zen Organic Outreach
Music, Theater, Multimedia and Web Development
info@mzoo.org
201-679-4168
www.mZoo.org
www.madhappy.com
www.rivka.com

**Comment by nerrad** [comment]
We offer some copies of our plugins (but not all add-ons) via public repos listed here: https://github.com/eventespresso

If you need access to anything that is not available via a public repo you will have to contact our sales team via the contact form on our website:  https://eventespresso.com/contact
