### ISSUE TITLE
Wrong Calculated Prices

### ISSUE THREAD

**Issue by thenovacreator** [eventespresso/event-espresso-core#144]
I have tickets that have a price of 64 after the tax is added. But if i buy 5 of them the Result is not 320 as it should be but its 319.99. This is a rounding issue that i corrected in my local version of ee and i want to contribute that solution. How can i do this?

**Comment by mnelson4** [comment]
Please create a pull request. (here's some documentation: https://help.github.com/articles/creating-a-pull-request/; I've found it easiest if I first fork the repo, make the desired changes in my forked version of the repo on the master branch, then create a pull request).
What base price and tax do you have? Are there any other price modifiers?

**Comment by tn3rb** [comment]
sounds like tax is being applied after the ticket price is multiplied by quantity, ie:

```
 ( price * qty )  * tax
```

whereas your fix probably does:

```
 ( price * tax ) * qty
```

**Comment by thenovacreator** [comment]
Well i just pushed up the number of diggets that is used for calculation.
But this could be a good solution too. I think it could be even a better
Solution. I will take a look at this if i find some time.

2016-02-12 17:57 GMT+01:00 Brent Christensen <notifications@github.com>:

> sounds like tax is being applied after the ticket price is multiplied by
> quantity, ie:
>
>  ( price * qty )  * tax
>
> whereas your fix probably does:
>
>  ( price * tax ) * qty
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/eventespresso/event-espresso-core/issues/144#issuecomment-183412070>
> .
>



-- 
Novacreator
Kolja Berlau
Waldstraße 31
24939 Flensburg

**Comment by thenovacreator** [comment]
Hi Folks,

since the change of the calculationorder does not fix the problem i came along with a patch that makes ee using more digits for calculation.

**Comment by nerrad** [comment]
Hi just letting you know we've seen this, will look when we can.

**Comment by mnelson4** [comment]
Hey @thenovacreator,
I'm not sure if we want to introduce that level of precision; instead we've been doing a round-as-you-go approach, so that no line item in EE has a partial penny amount. This is good for when we send line items off to gateways, for example.
For example, let's say the ticket-and-tax-and-discounts combine to make it so a ticket's final price is $3.33333333. And someone orders 3 of them. So their transaction total is $10 exactly. So far great. Then they go to pay with paypal, and so we list out the line items for paypal, who DOES NOT allow partial penny amounts: 3 items at $3.33, making for a total of $9.99.
So they pay via paypal for $9.99 and then come back owing a penny.

It would still be helpful to know what base price and tax do you have? Are there any other price modifiers? That way we can reproduce the issue you're experiencing and first see if there's a smaller change that might resolve it too

**Comment by mnelson4** [comment]
re-mind again actually: in my case 319.99 is right because is applied onto the pretax total then rounded, not applied to individual items then rounded (which does give 320.00)

**Comment by thenovacreator** [comment]
Well use the base price of 2689.08 or 2689.07 and tax amount of 19% and try to get an endprice of 3200.

**Comment by mnelson4** [comment]
@thenovacreator I'm confused at what the issue is you're trying to address. At first I thought the issue was the seemingly incorrect calculations when multiple tickets are purchased (eg  5 $53.78 tickets with 19% tax equals $319.99, not $320 like you had expected and our user interface suggests it should) but now you want to have a specific final price on a single ticket when taxes are applied. Which issue are we trying to address?

The first issue (that 5 tickets $53.76 tickets with a 19% tax equals $319.99) is the case because taxes are actually applied on sum of the individual tickets and THEN rounded; they're not applied to each ticket and then summed and rounded. Ie, this is the calculation we do: `round( 53.76 * 5 * 1.19, 2)`, not `round(53.76 * 1.19, 2 ) * 5`. We can try to change the rounding to happen only on the final amount, and so allow ticket prices to be infinitely precise, but then we'll need to show all those decimal places in invoices (eg show each ticket's price as $63.9744) and transmit them to gateways (which isn't possible because gateways only accept whole penny amounts). So to me right now it seems the best solution is to have the UI be more clear about when taxes are applied (on the pre-tax-total) and when rounding occurs (on each ticket's total). Does that make sense? Do you agree?

The second issue, that you can't get exactly $3200 with a 19% tax, is simply the result of the base price and ticket price modifiers only allowing 2 decimal places. I think allowing the base price and price modifiers to be more precise is quite an acceptable change, especially seeing how these amounts are never sent to gateways and rounding happens on the ticket's total, not on the base price and ticket's price modifiers levels. Does that make sense? Do you agree?

**Comment by thenovacreator** [comment]
Well in my tests you can adress both Problems with the same solution. So it's about both Problems. So I agree with the second statement.

**Comment by thenovacreator** [comment]
Du you have some updates for the status?

**Comment by mnelson4** [comment]
Hi @thenovacreator, here's what's holding things up:

* it would be helpful to have a set of tests that clearly show what dollar amounts currently cause problems and that this change resolves this (php unit tests are ideal, but if not then screenshots showing the exact base prices, price modifiers, taxes, and quantities)
* these changes don't affect how prices are stored in the database, so we're debating how to store more precise numbers (and which fields should be rounded to the nearest penny, and which should be as price as possible)
* we're having some debates about a bigger refactor which, if attempted, would invalidate these changes

You're welcome to help out on the first two items if you want

**Comment by thenovacreator** [comment]
Yes. I will put you some things together.

**Comment by nerrad** [comment]
@thenovacreator any update on this?

**Comment by thenovacreator** [comment]
Well i could ask you too. Are you planning to do the bigger refactoring?

**Comment by nerrad** [comment]
There hasn't been a response from you regarding what @mnelson4 wrote here https://github.com/eventespresso/event-espresso-core/issues/144#issuecomment-204458853 other than your comment in the following post:

> Yes. I will put you some things together.

So I was asking if there was an update on that.  At this point nothing (that I'm aware of @mnelson4 might be able to elaborate) has changed on our end.

**Comment by thenovacreator** [comment]
So to be earnest i did not have the time to write some tests on this. The status is because of this the same as it was at the 1st of april i wrote this.

**Comment by thenovacreator** [comment]
Any Opinions?

**Comment by mnelson4** [comment]
Sorry I haven't gotten around to this either.

> So i am asking myself if it is worth the effort if you planning to refactor anyway.

The unit tests will help to clearly establish expectations. Ideally, the unit tests would FAIL if ran against the master branch, but pass on your branch. 

These unit tests would actually help with refactoring because we could run the refactored code against them to verify your expectations are being met.
