### ISSUE TITLE
Regarding overriding templates

### ISSUE THREAD

**Issue by jonathan-dejong** [eventespresso/event-espresso-core#150]
Hi,

So. Some of EEs templates can be overridden by placing a copy in the uploads folder.
However it seems to be very spontaneous which works and which does not. 

I've had some success with files located in core/modules but no luck with templates in core/shortcodes for example. Is there a strategy to this? 

As an example I've been attempting to modify the thank you page pretty heavily. I can make some headway with some of the filters and CSS (altho hiding stuff with CSS makes me cringe) but some things are just impossible to fix without being able to modify the template as a whole. 

I can't claim to know or understand how your template override functionality works but shouldn't it be equally possible to let users override template files in shortcodes as in modules? 

Thank you!

**Comment by tn3rb** [comment]
can you provide some code to show what you are attempting to do, that way I can trouble shoot it.
as far as I know, any template can be overridden, but maybe there is a bug preventing that from happening with your implementation. I;ll need to see some code though plz.

**Comment by jonathan-dejong** [comment]
Sure, I'll post the example tomorrow!

**Comment by jonathan-dejong** [comment]
Alright! 

So I attempt to modify the `thank-you-page-overview.template.php` file. 
I've created a copy in `uploads/espresso/templates/shortcodes/espresso_thank_you/templates/` which I think would be the correct directory. 

EE isn't reading in that file at all.

**Comment by jonathan-dejong** [comment]
@tn3rb 
Any input on this? :)

**Comment by jonathan-dejong** [comment]
So I saw this in the latest changelog: 

> Add hook to display the template that was found using locate_template

Guessing you've fixed this?

**Comment by Pebblo** [comment]
Hi Jonathan,

This item within the changelog:

> Add hook to display the template that was found using locate_template

Just added a hook to allow you to display the exact location of the template being used.

For example, you now can use something like this:

https://gist.github.com/Pebblo/07381ce848c74786676f5bb7bb495a8e

To display the location a template is loading from, however it doesn't really help you with the above. It enables us to find out where a users output is coming from when a user posts an issue on the forum and we can't find their template in the 'usual' locations.

All templates within EE4 should be ran through EEH_Template::locate_template() which is passed either a relative or absolute path to the template.

locate_template() basically builds out an array of file paths to check for the template, the first path that is readable is where the template will be loaded from. So it builds out an array of locations like this:

/wp-content/themes/<current active WordPress theme>/
<absolute path to file> (if passes to locate_template)
/wp-content/uploads/espresso/templates/<current EE theme>/
/wp-content/uploads/espresso/templates/
/wp-content/plugins/<EE4 folder>/public/<current EE theme>/
/wp-content/plugins/<EE4 folder>/core/templates/<current EE theme>/
/wp-content/plugins/<EE4 folder>/

Then loops through those from top to bottom, as soon as it finds a copy in the template in a location it breaks out of the loop and loads that template.

So the reason some files work from /wp-content/uploads/espresso/templates/ and others do not is because they likely pass an absolute path to locate_template, that's checked **before** /wp-content/ (this is intended behavior)

This means your best bet to load custom templates is to create a child theme and load them from the root directory of the child theme as that is checked before any other location.

**Comment by jonathan-dejong** [comment]
Hi Pebblo,

So what you're saying is basically instead of putting my overriding files in uploads I should put them in my theme? Seems like a strange priority-list to first check the root of current theme, then absolute path and then the overriding location that's recommended.. and if checking in the theme, why not in an "espresso" folder in the theme like everybody else does it (read woocommerce)? 

:)

**Comment by Pebblo** [comment]
> So what you're saying is basically instead of putting my overriding files in uploads I should put them in my theme?

Yes, that is what I am saying, it is the most reliable location for all templates passed to locate_template()

> Seems like a strange priority-list to first check the root of current theme, then absolute path and then the overriding location that's recommended..

The idea behind this is to move away from placing .php within /wp-content/uploads/espresso/

That location has been used since EE3 so we stuck with it, however some hosts will simply delete php files located there, some security plugins will also either delete or empty the file (which means you load an empty template... fun times)

Is there a wiki document you've found recommending that location for EE4?

> and if checking in the theme, why not in an "espresso" folder in the theme like everybody else does it (read woocommerce)?

Yeah that makes sense and we have opened an internal discussion around locate_template to decide where to go with it.

In the meantime your more than welcome to open a pull request to include /espresso/ within the template check if you prefer, or there's also a filter you can use:

`FHEE__EEH_Template__locate_template__full_template_paths`

For example:

https://gist.github.com/Pebblo/62749ca6a3951e860c474d6d206300a9

**Comment by jonathan-dejong** [comment]
Thank you for the very extensive answers :) 

Now that you've explained the uploads folder as a remnant of EE3 it makes sense.. I am however pretty sure I've seen the information about putting the template files there in your documentation somewhere but at the moment I can't remember where. It might've changed too because it was probably about a year ago I learnt this. At that time there was also no mention of the active theme folder. 

I'm gonna try out the gist and move all my files from uploads, thank you. Then I can finally disable php in the uploads folder as well.. a bit more secure :) 

Oh and btw, I cast my vote on an "eventespresso" or "espresso" folder in the theme.
