### ISSUE TITLE
Cost to sponsor feature remove registrant from registration

### ISSUE THREAD

**Issue by jonathan-dejong** [eventespresso/event-espresso-core#159]
### Is this a bug report?

* [ ] yes
* [x] no

I know you guys are able to work in specific features faster if they're being sponsored.

My client wants to know what it'd take to be able to remove a single registrant from a registration of multiple registrants. I can see how it might be a lot more difficult removing the primary registrant so perhaps an estimate for just additional registrants as well as primary would be nice :) 

They have a lot of organisations where people book say 10 people in a registration and then they realize some might not be able to go etc. etc. 

thanks!

**Comment by garthkoyle** [comment]
I'm not sure GitHub is the best place to have this discussion, so after a brief discussion here and you still want to pursue this then we can evaluate it further over email.

Can you describe the situation that is caused when one registration out of a group of registrations wants to attend and others will not, or visa versa?

When an attendee is part of a group of registrations, you can edit a single registration (see the attached image).
![edit-single-registration-from-group-registration](https://cloud.githubusercontent.com/assets/3094547/14686234/0f42e120-06f5-11e6-9ce8-c211a556bb7c.png)


You can also approve single registrations among group registrations.

**Comment by nerrad** [comment]
Does canceling a registration in this group not work for the described use case?

**Comment by jonathan-dejong** [comment]
@garthkoyle I will check with the user and get back to you. 

@nerrad the option to cancel a registration wasn't there a while back? I'm going to ask that they try it to see if that's what they where after..

**Comment by nerrad** [comment]
It's always been possible to change the status of registrations to cancelled from the Registration List table.  However somewhat recently (in the past year?) we added some features that took care of correcting transaction totals etc when a registration was cancelled.  Part of this feature also enabled keeping track of how much each registration owes for the transaction so calculations are adjusted properly.  tldr; the cancel status has been around for a long time, the logic for properly handling side-effects of cancellations is newer.

**Comment by nerrad** [comment]
@jonathan-dejong any update on this?

**Comment by jonathan-dejong** [comment]
@nerrad 

Ah yes. So this is what I'm referring to (screenshot). We just tried it with the latest version since I saw something about bug fixes for emptying trash in the changelog. Still no dice tho. 

![14045285_10157375367910381_1715998179_o](https://cloud.githubusercontent.com/assets/1508751/17738322/0c48f37a-6491-11e6-9ccf-8a0745e839fd.jpg)

**Comment by nerrad** [comment]
Okay that helps explain what you may be trying to do.

The error message you are seeing is because we currently don't support permanently deleting a registration without also permanently deleting all related registrations in the transaction.  The reason being is a permanent delete removes the registration completely from the database and affects all the relations to that registration (transaction, ticket counts, datetime counts, registration payments, transaction totals, line items etc).  Eventually we _will_ support permanent deletes of a single transaction, but it involves a number of incremental steps to get there so we're accounting for all the relations.

When I talked about _cancelling_ a registration, I was NOT referring to trashing the registration but actually changing its registration status to cancelled.  However, I was incorrect in mentioning that the logic that takes care of transaction totals and amount oweing is in place, it isn't (yet).  That's something we have open in progress tickets on and hope to have done relatively soon.

Once that's in place, to accomplish what you want, you just have to cancel the registration to remove from the group, and then trash that registration.  All the totals will be updated, and trashing the registration means it won't appear in a list with that group anymore.  Unfortunately you will not be able to permanently delete the registration until we implement logic to be able to do that apart from other registrations belonging to the same transaction (which likely would be implemented shortly after the work we do on cancellation logic because that's a pre-requisite).

**Comment by jonathan-dejong** [comment]
Thank you for the comprehensive response :) 

I've talked it over with the client. seems just trashing the single registrant from a group registration will be enough. We just have to tweak our front end list of registrants to take this into consideration and not display those persons. 

We're currently running this code which I think is a progression of some code you gave me a long time ago @nerrad. If you have any suggestions on how to achieve this in a better way I'm all ears! Perhaps there's now better models for fetching the data?

```
<?php
					global $wpdb, $post;
					$sql = "SELECT ATT_fname, ATT_lname, ATT_email, REG_ID ";
			        $sql .= "FROM {$wpdb->prefix}esp_attendee_meta ";
			        $sql .= "INNER JOIN {$wpdb->prefix}esp_registration ";
			        $sql .= "ON {$wpdb->prefix}esp_attendee_meta.ATT_ID = {$wpdb->prefix}esp_registration.ATT_ID ";
			        $sql .= "WHERE {$wpdb->prefix}esp_registration.EVT_ID = %d";
			        $attendees = $wpdb->get_results( $wpdb->prepare( $sql, $post->ID ));
					?>
					<?php if($attendees): ?>
						<?php
						$current_user = get_userdata(get_current_user_id());
						$show_attendees = false;
						if(get_field('event_show_attendees')){
							foreach($attendees as $attendee){
								if($attendee->ATT_email == $current_user->user_email){
									$show_attendees = true;
								}
							}
						}
						?>
						<?php if($show_attendees || current_user_can('upload_files')): ?>
							<div class="ee-event-section" id="ee-event-attendees">
								<h2><?php _e('Deltagare', 'sceleton'); ?> <span class="grey-color">(<?php echo count($attendees); ?>)</span></h2>
								<?php get_attendees_pdf_button(); ?>
								<div id="event-attendees-wrap">
									<table class="ee-event-attendees-table list-table">
										<colgroup class="ee-attendee-name"></colgroup>
										<colgroup class="ee-attendee-municipality"></colgroup>
										<colgroup class="ee-attendee-role"></colgroup>
										<thead>
											<tr>
												<th data-orderby="name" data-order="asc" data-icon="N"><?php _e('Namn', 'sceleton'); ?></th>
												<th data-orderby="role" data-order="asc" data-icon="N"><?php _e('Befattning', 'sceleton'); ?></th>
												<th data-orderby="municipality" data-order="asc" data-icon="N"><?php _e('Kommun/Org', 'sceleton'); ?></th>
											</tr>
										</thead>
										<tbody>
											<?php foreach($attendees as $attendee): ?>
												<tr>
										            <?php
										            $fname = $attendee->ATT_fname;
										            $lname = $attendee->ATT_lname;
										            $email = $attendee->ATT_email;
										            $REG_ID = $attendee->REG_ID;
										            $sql2 = "SELECT * FROM {$wpdb->prefix}esp_answer WHERE REG_ID = %d AND QST_ID IN (12, 27)";
										            $answers = $wpdb->get_results( $wpdb->prepare( $sql2, $REG_ID ));
										            foreach( $answers as $answer ){
											            if( $answer->QST_ID == 27 ){
												            $befattning = $answer->ANS_value;
											            }else{
												            $kommun = $answer->ANS_value;
											            }
										            }
										            ?>
													<td class="td-name"><?php echo $fname .' '. $lname; ?></td>
													<td class="td-role"><?php echo (isset($befattning) ? $befattning : ''); ?></td>
													<td class="td-municipality"><?php echo (isset($kommun) ? $kommun : ''); ?></td>
												</tr>
											<?php endforeach; ?>
										</tbody>
									</table>
								</div>
							</div>
						<?php endif; ?>
					<?php endif; ?>
```

**Comment by nerrad** [comment]
hmm I don't remember that code so it may have been someone else on the team.  There's a number of ways to do things differently with the EE model system depending on how efficient you want queries to be (vs ease of use in the client code).

### Option One - grab EE_Attendee objects and loop through.

```
$where = array(
	'Registration.EVT_ID' => $post->ID,
	'ATT_email' => $current_user->user_email
);

$attendees = EEM_Attendee::instance()->get_all( array( $where ) );
/** @var EE_Attendee $attendee */
foreach ( $attendees as $attendee ) {
	//do your code here...
	$first_name = $attendee->fname();
	//etc.
	//to get the registrations attached to this attendee for this event
	/** @var EE_Registration[] $registrations */
	$registrations = $attendee->get_registrations(
		array(
			'EVT_ID' => $post->ID,
		)
	);
	foreach ( $registrations as $registration ) {
		//get answers
		$answers = $registration->answers();
		//loop through EE_Answer objects and display
	}
}
```

### Option Two: grab `EE_Registration` objects and loop through

$where = array(
	'EVT_ID' => $post->ID,
	'Attendee.ATT_email' => $current_user->user_email
);
$registrations = EEM_Registration::instance()->get_all( array( $where ) );

```
/** @var EE_Registration $registration */
foreach( $registrations as $registration ) {
	//get the related attendee object for the registration
	$attendee = $registration->attendee();
	$first_name = $attendee->fname();
	//etc

	//get answers
	$answers = $registration->answers();
	//loop through EE_Answer objects and display
}
```

### Option 3: Use `get_all_wpdb_results`

This might be more efficient because you can have the results returned in single records from the db (instead of assembled objects).  However I'm not going to take the time to do a code example because how well it works is really dependent on the nature of the registrations in your system and the relationships that exist.  

You can read about `get_all_wpdb_results` in the [inline docs](https://github.com/eventespresso/event-espresso-core/blob/master/core/db_models/EEM_Base.model.php#L903) for the method.  If I was to use this approach, I'd probably orient it from the context of answers: `EEM_Answer::instance()->get_all_wpdb_results( $query, ARRAY_A, $columns_to_select );`

**Comment by jonathan-dejong** [comment]
It was like ~2 years ago.. perhaps it's based on the example in your help/support section of your site now that I think about it.. 

Of course I want it to be as fast as possible (which I feel my current code are not). 
Thank you for the examples and tips. I will look into best solution :)

**Comment by nerrad** [comment]
I think the original issue is not relevant now so I'll close this ticket.
