### ISSUE TITLE
Replacement Filter Required

### ISSUE THREAD

**Issue by adbutt** [eventespresso/event-espresso-core#169]
Hey Guys, I have been advised by the support staff to contact you regarding the creation of a replacement filter for FHEE__EE_Registration_Processor___generate_reg_code__new_reg_code, which is apparently deprecated.
Could you please create a filter in the new method that generates the new reg code.

Support ticket for reference: [https://eventespresso.com/topic/modify-the-registration-id-used-in-ee4/]

**Comment by tn3rb** [comment]
???

The \EE_Registration_Processor::generate_reg_code() method was deprecated and replaced by the \EventEspresso\core\domain\entities\RegCode class, as is pointed out in the deprecation notice, and referenced in your forum post. It is a relatively simple DTO (Data Transfer Object), and there is a filter in its constructor for changing the reg code:

```
$this->reg_code = apply_filters(
	'FHEE__Create__regCode__new_reg_code',
	implode( '-', $this->reg_code ),
	$transaction,
	$ticket
);
```

I can't add a replacement filter for FHEE__EE_Registration_Processor___generate_reg_code__new_reg_code because that is it. Josh was likely just not aware that there was a replacement.

You mentioned in your forum post that:

> I can get the 1st (basic one) example to work by hooking it into the FHEE__Create__regCode__new_reg_code however the second example which makes a call for the event ID doesn’t work. 

Which is obviously the above filter, but what second example are you referring to?
The link to the code snippets that you posted has no references to reg code filters, so I'm not sure what code example you are looking at.

>  I need to return the event ID in order to pull the count and another custom field from the event so that the Reg_ID would look something like this companyid(customfield) – count(customfield) – transaction

If you are using the above filter in the RegCode DTO, you will see that it passes an EE_Ticket object as the third parameter. You could get the event ID from it directly, so for example, if you named that var ` $ticket ` () you would use the following method:

```
$ticket->get_event_ID()
```

I hope that is all that you need to do what you want. If not, then let me know if there is anything else you need help with.

**Comment by adbutt** [comment]
Hey Mate, cheers for the update... The example I was referring to has since been removed from the wiki. See below copied example of the original example...
`function change_reg_code($new_reg_code, $registration) {
  d($registration);
    $eventid = $registration->event_ID();
    $count = get_post_meta( $eventid, 'count', true );
    //create a new reg ID e.g. business-count-1598
    $new_reg_code = "my_count-" . $count . '-' . rand(1000, 10000); 
    $newcount = (int)$count + 1;
    update_post_meta($eventid, 'count', $newcount, $count);
    //send the new reg code back to be used.
    return $new_reg_code;
}
add_filter('FHEE__Create__regCode__new_reg_code','change_reg_code', 10, 2);`

appreciate your help on this issue

**Comment by tn3rb** [comment]
oh ya that was from awhile ago. Josh likely removed that from the wiki after reading your post.

So did you get things working to your satisfaction?

**Comment by adbutt** [comment]
Nah mate, Im still struggling to retrieve the ID. Can you point me in the right direction?

**Comment by tn3rb** [comment]
the ID for... the event ?
if you are using the 'FHEE__Create__regCode__new_reg_code' filter on the RegCode DTO 
https://github.com/eventespresso/event-espresso-core/blob/master/core/domain/entities/RegCode.php
then the third parameter passed to the filter callback is the registration's ticket. You can get the event ID directly from that using the method I noted in my first comment. It might look something like this:

```php
add_filter(
    'FHEE__Create__regCode__new_reg_code',
    'myCustomRegCode',
    10,
    3 // <<< the number of arguments passed to filter callback... if this is not 3, then you won't get the ticket
);
/**
 * @param                 $reg_code
 * @param \EE_Transaction $transaction
 * @param \EE_Ticket      $ticket
 */
function myCustomRegCode( $reg_code, \EE_Transaction $transaction, \EE_Ticket $ticket) {
    $event_id = $ticket->get_event_ID();
    // other code
}
```

**Comment by tn3rb** [comment]
did this work out for you?
haven't heard anything back in awhile...

**Comment by adbutt** [comment]
apologies mate, my blonde moment - only passing 2 parameters... cheers
