### ISSUE TITLE
Fix copy ticket

### ISSUE THREAD

**Issue by joshfeck** [eventespresso/event-espresso-core#1707]
The copy ticket feature needs fixing.

![Oct-15-2019 09-35-13](https://user-images.githubusercontent.com/891156/66836405-3e588200-ef2f-11e9-8e4d-eec157407c3f.gif)

**Comment by tn3rb** [comment]
never had that problem... what's your pagination setting (per page) at?
is it showing up on the next page? and/or are other filter settings preventing it from showing?

something similar can happen when you create a new ticket, because sometimes they won't appear in the list immediately because of the current filter settings, so I'm considering tracking newly created tickets and then prepending them onto the list of tickets after other filters have been applied. Might have to do something similar with dates.

**Comment by joshfeck** [comment]
It's set to 6 per page, and there are currently only 2 tickets. So it's not showing on the next page, and if it's not showing because of filter settings then maybe something isn't getting copied over as it should? I would think datetime relationships and sale start/end dates should get copied onto the new ticket, right?

This is one event where I tried to copy a ticket:

https://brent.eventespresso.com/wp-admin/admin.php?page=espresso_events&action=edit&post=34
