### ISSUE TITLE
New custom payment method EE_Select_Input field Portugal language array not work

### ISSUE THREAD

**Issue by getcoderzone** [eventespresso/event-espresso-core#172]
Hi, I’m Using Event Espresso 4.9.16.p Version .
I’m Created New custom payment method but EE_Select_Input field Portugal language array not working .

Please see screenshot: https://s14.postimg.org/5446fb20x/fdjfkd.jpg

when using Portugal language array and ‘required’=>TRUE, then showing this error message:
This registration step could not be completed. Please refresh the page and try again.

How can i fix this issue?

**Comment by getcoderzone** [comment]
event-espresso-core/tests/mocks/addons/new-payment-method/  
I'm Using this payment method addons  .  added new more billing information field .

Its my billing form field code: https://codepaste.net/5dk1md

**Comment by nerrad** [comment]
Hi there,

First of all, I suggest you update to the latest version of Event Espresso first.  `4.9.16.p` is quite few versions behind.

**Comment by getcoderzone** [comment]
now i install 4.9.21.p this version .  same issue :(

**Comment by getcoderzone** [comment]
If you need please check our customize payment method plugin 
https://www.dropbox.com/s/8jjv5ueg22p66iw/aea-offline-billing-2.zip?dl=0

**Comment by mnelson4** [comment]
hi @getcoderzone, thanks for providing your actual addon, that helped a lot in debugging.
I was getting some errors when using your plugin, which turned out to be because of how they used ANSI encoding instead of UTF-8. When I switched them to use UTF-8 they worked fine. So try using UTF-8 for your file's encodings, and see if that resolves your problems.

We're working on a fix in EE core too, so using ANSI files will be more ok

**Comment by getcoderzone** [comment]
now used UTF-8  but same issue  :(
https://s14.postimg.org/6lavonfz5/utf_8.png

**Comment by getcoderzone** [comment]
Thank you now problem solve 👍  
Now Used  UTF-8

**Comment by getcoderzone** [comment]
when you fix EE core ANSI Files issue ? please comment here .

**# Again Thanks a lot**

**Comment by mnelson4** [comment]
yeah we have a fix which is getting tested on branch BUG-10246-use-wp-json-encode, and will probably make it into the next release of EE core.

Also, if your plugin is using the `event_espresso` text domain, it should be in English instead of Portuguese, because everything else in the `event_espresso` text domain is in that language. If you want to write the primary strings in Portuguese I'd just suggest using a different text domain, like "espresso_aea".

Ok good luck! Glad we were figure out the issue :+1:

**Comment by nerrad** [comment]
Just want to chime in and actually _request_ that you do NOT use the `event_espresso` text domain for i18n in your plugin.  That's something that should only be used for **official** Event Espresso plugins.

**Comment by mnelson4** [comment]
hi @getcoderzone we looked into the issue. It turns out that supporting using ANSI files along with JSON encoding and PHP object serialization is a tricky issue. (Basically it would require us to write our own PHP object serializer that would convert ANSI text to UTF8 before serialization).
The upcoming release of 4.9.22 will support ANSI text with `WP_DEBUG=false`, but if you have `WP_DEBUG=true` you'll need to disable the unserialization hash check warning using the following filter:

```
add_filter(
    'FHEE__EE_Session___perform_session_id_hash_check',
    '__return_false'
);
```

Just place that in your functions.php file or anywhere it will get executed early. (That's necessary because even though we've made changes so that we can json-encode text in the ANSI format, when we serialize data and send it to the database in ANSI format, the database changes it to be the format it uses, which is also usually UTF-8. And when the data is unserialized the hash check detects that its been changed and so gives a warning).

So overall, the best approach is certainly to use UTF-8 in all your files, even with EE 4.9.22
