### ISSUE TITLE
Querying EEM_Event model by date range doesn't appear to work

### ISSUE THREAD

**Issue by gazchap** [eventespresso/event-espresso-core#173]
### Is this a bug report?

I think so - not 100% sure. Have been advised to post here from my support forum post: https://eventespresso.com/topic/querying-events-by-date-doesnt-seem-to-be-working/

### What branch did this occur in?

EE4 4.9.16, release.

### What version of WordPress is on the site this issue happened?

WP 4.6.1

### Outline the steps to reproduce

I’m trying to query the EEM_Event model to fetch a list of events that take place between two dates (in this case, basically retrieving all events that take place in December)
The code I’m using is:

```
EEM_Event::instance()->show_next_x_db_queries( 1 );
$posts = EEM_Event::instance()->get_all(
    array(
        array(
            'Datetime.DTT_EVT_start' => array( 'BETWEEN', array( '2016-12-01 00:00:00', '2016-12-31 23:59:59' ) ),
        ),
    )
);
```

However, the SQL query generated by that query is:
SELECT Event_CPT.ID AS ‘Event_CPT.ID’, Event_CPT.post_title AS ‘Event_CPT.post_title’, Event_CPT.post_content AS ‘Event_CPT.post_content’, Event_CPT.post_name AS ‘Event_CPT.post_name’, Event_CPT.post_date AS ‘Event_CPT.post_date’, Event_CPT.post_excerpt AS ‘Event_CPT.post_excerpt’, Event_CPT.post_modified AS ‘Event_CPT.post_modified’, Event_CPT.post_author AS ‘Event_CPT.post_author’, Event_CPT.post_parent AS ‘Event_CPT.post_parent’, Event_CPT.menu_order AS ‘Event_CPT.menu_order’, Event_CPT.post_status AS ‘Event_CPT.post_status’, Event_CPT.comment_status AS ‘Event_CPT.comment_status’, Event_CPT.ping_status AS ‘Event_CPT.ping_status’, Event_Meta.EVT_display_desc AS ‘Event_Meta.EVT_display_desc’, Event_Meta.EVT_display_ticket_selector AS ‘Event_Meta.EVT_display_ticket_selector’, Event_Meta.EVT_visible_on AS ‘Event_Meta.EVT_visible_on’, Event_Meta.EVT_additional_limit AS ‘Event_Meta.EVT_additional_limit’, Event_Meta.EVT_default_registration_status AS ‘Event_Meta.EVT_default_registration_status’, Event_Meta.EVT_member_only AS ‘Event_Meta.EVT_member_only’, Event_Meta.EVT_phone AS ‘Event_Meta.EVT_phone’, Event_Meta.EVT_allow_overflow AS ‘Event_Meta.EVT_allow_overflow’, Event_Meta.EVT_timezone_string AS ‘Event_Meta.EVT_timezone_string’, Event_Meta.EVT_external_URL AS ‘Event_Meta.EVT_external_URL’, Event_Meta.EVT_donations AS ‘Event_Meta.EVT_donations’, Event_CPT.ID AS ‘Event_CPT.ID’, Event_Meta.EVTM_ID AS ‘Event_Meta.EVTM_ID’, Datetime.DTT_ID AS ‘Datetime.DTT_ID’, Datetime.EVT_ID AS ‘Datetime.EVT_ID’, Datetime.DTT_name AS ‘Datetime.DTT_name’, Datetime.DTT_description AS ‘Datetime.DTT_description’, Datetime.DTT_EVT_start AS ‘Datetime.DTT_EVT_start’, Datetime.DTT_EVT_end AS ‘Datetime.DTT_EVT_end’, Datetime.DTT_reg_limit AS ‘Datetime.DTT_reg_limit’, Datetime.DTT_sold AS ‘Datetime.DTT_sold’, Datetime.DTT_is_primary AS ‘Datetime.DTT_is_primary’, Datetime.DTT_order AS ‘Datetime.DTT_order’, Datetime.DTT_parent AS ‘Datetime.DTT_parent’, Datetime.DTT_deleted AS ‘Datetime.DTT_deleted’ FROM wp_posts AS Event_CPT LEFT JOIN wp_esp_event_meta AS Event_Meta ON Event_CPT.ID = Event_Meta.EVT_ID LEFT JOIN wp_esp_datetime AS Datetime ON Datetime.EVT_ID=Event_CPT.ID WHERE Event_CPT.post_type = ‘espresso_events’ AND Event_CPT.post_status NOT IN (‘auto-draft’,’trash’) AND ( (Datetime.DTT_deleted = 0) OR Datetime.DTT_ID IS NULL) AND **Datetime.DTT_EVT_start BETWEEN ‘2016-11-16 15:46:03’ AND ‘2016-11-16 15:46:03’**

(emphasis mine) – it’s completely ignoring my dates, and using the current date/time for both instead.

**Comment by nerrad** [comment]
Hi there,

One thing you'll want to do is review some documentation we have for Dates and Times in EE.  Here's some links to get you started:

- https://github.com/eventespresso/event-espresso-core/blob/master/docs/F--Datetime-System/dates-times-timezones-in-models.md
- http://developer.eventespresso.com/important-changes-to-ee-datetime-system-coming-to-ee/

The documentation above is not exhaustive, however it does give an overview of dates and times in EE.

So with your particular example,  the important thing to remember is that when you build a query using EE's model system, any incoming date strings are **assumed** by the model to be:

- in the timezone for the site.
- in the format for the site.

So, unless you explicitly indicate those things when setting up your query, that's how the model will interpret a date string.

So in your particular example, that's why you see the final query have date strings that are different from what you had because the model is converting what you gave from the timezone on the site into UTC which is how dates are stored in the db for EE data.

So, the easiest way to build your query is to use a helper method we've exposed in the models for date and time queries.

Assuming your datestring is in the timezone `America/New_York` you can do something like this (Note: you don't need to send in the timezone string if your date string is in the same timezone as what your WordPress settings has set):

```
$start_date = EEM_Datetime::instance()->convert_datetime_for_query( 'DTT_EVT_start', '2016-12-01 00:00:00', 'Y-m-d H:i:s', 'America/New_York' );
$end_date = EEM_Datetime::instance()->convert_datetime_for_query( 'DTT_EVT_start', '2016-12-31 23:59:59', 'Y-m-d H:i:s', 'America/New_York' );
$events = EEM_Event::instance()->get_all(
	array(
		array(
			'Datetime.DTT_EVT_start' =>
				array(
					'BETWEEN',
					array( $start_date, $end_date )
				),
		),
	)
);
```

You can read the phpdoc found with the method in `EEM_Base::convert_datetime_for_query()`

**Comment by gazchap** [comment]
Thanks, that has worked. You may want to update the documentation found under the "GOTCHA" section of get_all() on https://github.com/eventespresso/event-espresso-core/blob/master/docs/G--Model-System/model-querying.md as this shows an example for DTT_EVT_start that uses a "naked" string that hasn't been passed through EEM_Datetime::convert_datetime_for_query.
