### ISSUE TITLE
Ticket Price Calculator modal improvements

### ISSUE THREAD

**Issue by joshfeck** [eventespresso/event-espresso-core#1743]
The first time I used the ticket price calculator modal I wasn't sure why I couldn't select a price type for the base ticket price. Which makes sense to me now because I've realized it's not a price modifier, it's a base price! Maybe we could label it as "Base Price" instead of showing a disabled select input?

It might also be useful to show the name of the ticket so the user knows which ticket they're editing prices for. 

![Screen Shot 2019-10-25 at 6 17 59 PM](https://user-images.githubusercontent.com/891156/67608053-9e7fcd00-f754-11e9-9ee5-51e251f721cc.png)

**Comment by garthkoyle** [comment]
+1 I had a similar thought.

**Comment by nicolad** [comment]
@joshfeck @garthkoyle I didn't make it bold since there is a bit of confusion between that and the column label from above:

![image](https://user-images.githubusercontent.com/1477453/67849528-60e1c200-fb0f-11e9-811a-19bc54e20f25.png)

versus:

![image](https://user-images.githubusercontent.com/1477453/67849560-722ace80-fb0f-11e9-995e-8d6ca8ddd980.png)

**Comment by joshfeck** [comment]
Good call on not making the label bold.
