### ISSUE TITLE
Should there be only one link to go to edit in the Card UI?

### ISSUE THREAD

**Issue by joshfeck** [eventespresso/event-espresso-core#1754]
We could remove the edit icon since it's also a sub item of the hamburger icon.

<img width="616" alt="Screen Shot 2019-10-29 at 9 09 53 AM" src="https://user-images.githubusercontent.com/891156/67772212-10476780-fa30-11e9-92b3-4b4584c0574d.png">

**Comment by garthkoyle** [comment]
Because someone can change a number of elements of the datetimes and tickets from the card view, I think we can remove the edit button from the card, and leave it in the hamburger menu. Someone can already edit the T/D Name, T/D description, T capacity, eventually the T/D dates directly from the card view (https://github.com/eventespresso/event-espresso-core/projects/4#card-28581809).

I might reserve doing this though until we need the space on the D/T toolbar for something else, in case people need time to get used to the new UI and an explicit edit button might be helpful.

**Comment by tn3rb** [comment]
done in EDTR v2
closing issue
