### ISSUE TITLE
EDTR: Archive Tickets Action Should Only Be Available for Existing Tickets, Not New Tickets

### ISSUE THREAD

**Issue by garthkoyle** [eventespresso/event-espresso-core#1755]
See: http://p2.eventespresso.com/2019/10/10/edtr-test-server/#comment-20441

> If an event manager has an existing ticket option (that has registrations) that they need to quickly get rid of on the front end, being able to archive it will be most useful.

The archive option would be best shown only on existing tickets, not shown when it’s a new ticket.

**Comment by tn3rb** [comment]
This can easily be achieved by adding `deleted` to the `exclude` array in the `EditTicketForm` component (`/assets/src/editor/events/tickets/editor-ticket/edit-form/edit-ticket-form.js`)

Since we would only want to do this for a new ticket, we simply need to check if the ticket ID is an integer or a CUID.
This can be done via the `isCuid()` function which can be imported from the `cuid` library
