### ISSUE TITLE
Event Espresso New Custom Offsite Payment Getaway mail delay issue .

### ISSUE THREAD

**Issue by getcoderzone** [eventespresso/event-espresso-core#179]
Please See my forum post: https://eventespresso.com/topic/event-espresso-registration-e-mail-response-very-slow/

and please check my last comment . 

Thank You

**Comment by getcoderzone** [comment]
I have found the problem of e-mail delay issue.
I using one Offsite payment getaway plugin mainly when i use this plugin then i face email delay issue.
Can you check Please whats problem this plugin .
Plugin: http://www.test.aea.com.br/aea-offline-billing.zip (Its my Custom Plugin)

**Comment by nerrad** [comment]
Hi there,

That's great that you've got your own custom plugin!

We generally don't do free review of third party plugins only because we're already very focused on continuing to work on feature requests our customers have made and improving the product (see our [public roadmap board on trello](https://trello.com/b/zg9DCIpe/event-espresso-public-roadmap)). 

I'd recommend getting in touch with whoever built that plugin for you and asking them to debug the issue.  If this is something _you've_ built you may want to [review our documentation on payment methods and gateways here](https://github.com/eventespresso/event-espresso-core/tree/master/docs/L--Payment-Methods-and-Gateways) and review if you've followed guidelines there when building a payment method.

Alternatively, the delay may have nothing to do with your custom plugin, but instead be a delay on the part of that gateway in notifying when a transaction is complete.  Or the email server processing the outgoing emails (not your website server) have a delay.  As suggested in the forum post, trying a transactional email service will help rule out the latter possibility.

If you wish quicker action, I suggest looking into hiring one of the developers from [this page](https://eventespresso.com/developers/event-espresso-pros/)

Since this is not an issue related to the Event Espresso core product I'm going to close it.  If you have more specific info on where in EE there may be a problem related to outgoing messages please feel free to add to the ticket.
