### ISSUE TITLE
Full CRUD on REST API or Models?

### ISSUE THREAD

**Issue by Baadier-Sydow** [eventespresso/event-espresso-core#180]
### Is this a bug report?

* [ ] yes
* [x] no

Hi, 

I chatted to Lorenzo Caum around extending EE4 and he suggested that I should ask here.

I noticed that you have both a model system in place and a REST API available.

What I can't find answers to are the following:

REST API

- Do we have both READ and WRITE access to everything as it appears to only be READ access?

Model

- Can we access everything from the models ie CRUD on users, events, registration status etc Or are their limitations or areas of the functionality that we cant use?

While I know that EE4 doesnt explicitly support translations, I'm thinking that I should be able to recreate the user flow that I'm trying to achieve with gravity forms and handling the CRUD myself.

Thanks

**Comment by nerrad** [comment]
Hi there,

> Do we have both READ and WRITE access to everything as it appears to only be READ access?

Currently we only have READ access for all of the models however there is a special endpoint for performing check-ins.  You can read more about our REST API [here](https://github.com/eventespresso/event-espresso-core/tree/master/docs/C--REST-API).  There are a number of internal changes in EE core that will require write endpoints for the REST API so it's likely write endpoints will be available soonish (in the very loose sense of the term).

> Can we access everything from the models ie CRUD on users, events, registration status etc Or are their limitations or areas of the functionality that we cant use?

Yes all our models have full CRUD.  It's actually a pretty powerful way to interact with EE data. You can read more about it [here](https://github.com/eventespresso/event-espresso-core/tree/master/docs/G--Model-System).

> While I know that EE4 doesnt explicitly support translations

I'm not sure if what you mean by _translations_ is how I understand it, but EE is fully translation ready using the WordPress l18n system.  You'll just need the correct pot file installed for the translation (and we even automatically side load any available translation for the set language on the site). 

We have a number of different developer centric documentation that may help you with whatever you are trying to do: https://developer.eventespresso.com/docs. You may also want to bookmark https://developer.eventespresso.com and/or subscribe to its rss feed.  Any significant changes to the EE core codebase will be posted about by our dev team there.

I'm going to close this issue since its not a "to fix" issue, but feel free to continue with any more questions you have in this thread.

**Comment by Baadier-Sydow** [comment]
Thanks for the feedback.

I was wanting to know how the automated emails that are sent out via EE are handled when the user has a different language active for example French.

Is this something we are able configure using WordPress I18n?

How would things be handled in the event of custom notifications?

Thanks

**Comment by nerrad** [comment]
Currently messages are not WP_User aware (mostly because the primary use case for Event Espresso is non wpuser registrations).  However, any parsed shortcodes that have strings in them should be in the language the site is set to if that language file has been translated.  Any other default content in templates is also run through i18n when they are initially generated.  It's possible however, they were generated before the language could be set on the site.  If that's the case, then clicking "reset" on a template while editing, will regenerated it (losing all customizations however) and the content translated IF the translated string exists in the active language file.

An alternative way to internationalize templates, is to edit the existing templates and translate the text there to the language of choice directly in the editor.  You could even have different translated messages for different events if you create a custom message template and assign it to an event.

**Comment by Baadier-Sydow** [comment]
Thanks, I'm sure I have a few more questions for you :)

I'm planning on putting together a proof of concept later this week.
