### ISSUE TITLE
Guidance: Custom Event Ticket Validation

### ISSUE THREAD

**Issue by thebeline** [eventespresso/event-espresso-core#182]
Basically, I am looking for which actions to hook for when the “Register Now” button is pressed, and “Proceed to Payment Options.”

I am looking how to capture the Registration questions and the Tickets, and how to get the Source Event for the Tickets (when proceeding to payment options, it is possible [with plugins], that the Tickets will be for different Events).

And, finally, how to display an error and indicate the user must make a modification to continue.

I have a few use-cases:

* Purchasing a Teen Ticket requires the purchase of an Adult Ticket.
* Purchasing a multi-day Teen Ticket requires the purchase of an equivalent or greater Adult Ticket (specifically, one that covers the Date Times of the Teen Ticket).
* Selecting an upgrade in the registration process may require a specific ticket be purchased (if you want VIP access [which will add a surcharge] you must purchase a ticket that encompasses all Date Times).

And so on.

As I said, I don't think I need it all laid out for me, but just which hooks/filters to intercept, and which functions/methods/objects to use to access the Tickets and their events (and subsequently, the Ticket metadata, and the event metadata).

Thank you in advance! (this is kind of blocking releasing tickets for an event, so, thanks a bunch in advance!!!)

- Mike

**Comment by tn3rb** [comment]
All of our hooks are either prefixed with "AHEE__" for action hooks, or "AFEE__" for filters, so it's relatively easy to use your IDE's search capabilities to find all of our action hooks and filters.

The Event can be retrieved from an EE_Ticket object via the get_related_event() method. Registration Question Groups can then be retrieved from the returned EE_Event object via the question_groups() method, and the subsequent questions for each group from the questions() method. All of our model objects (like events, ticket, questions, etc) can be found in the **/core/db_classes/** folder. Relations between objects are automatically set up. So if you had an EE_Ticket object named $ticket, then you could get the questions for it's corresponding event like this:

```php
$event = $ticket->get_related_event();
$question_groups = $event->question_groups();
foreach ( $question_groups as $question_group ){
    $questions = $question_group->question();
}
```

Adding an error can be done using the EE_Error::add_error() method. Attention notifications (kinda like warnings) can be added using EE_Error::add_attention(), and success notifications can be added using EE_Error::add_success().

With regards to your use cases involving the enforcement of particular ticket selections, I'm inclined to think you would want to inject your logic long before getting to the registration checkout, that way the ticket selections can be modified before continuing.
So based on that, most of the hooks you would want are in the following methods:

 * EED_Ticket_Selector::process_ticket_selections() 
 * EED_Ticket_Selector::_add_ticket_to_cart() 

For example, in EED_Ticket_Selector::process_ticket_selections(), you could use the '**FHEE__EE_Ticket_Selector__process_ticket_selections__before_redirecting_to_checkout**' action for examing the contents of the cart to determine if your business rules have been met.
Then if need be, redirect the user back to the event or event list using the '**FHEE__EE_Ticket_Selector__process_ticket_selections__success_redirect_url**' filter.

Once final ticket selections have passed all of your requirements and the user is advanced to the registration checkout, then the main hooks you would want to use are likely found in the main checkout class **EED_Single_Page_Checkout**, of which:

 * '**FHEE__Single_Page_Checkout___check_form_submission__request_params**' found in \EED_Single_Page_Checkout::_check_form_submission(), and
 * '**AHEE__Single_Page_Checkout__before_{current_step_slug}__{checkout_action}**' found in EED_Single_Page_Checkout::_process_form_action()

are likely the most useful for your needs. The second one is dynamically named based on the current request params, where "**current_step_slug**" would most likely be either:

 * attendee_information
 * payment_options

and checkout_action would almost certainly be:

 * process_reg_step

so if you wanted to do something after the "Proceed to Payment Options" button is clicked, then you could use the '**AHEE__Single_Page_Checkout__before_attendee_information__process_reg_step**' action hook to get all of the data you need. It's only parameter is the current registration step class, which in this case would be EE_SPCO_Reg_Step_Attendee_Information. Each reg step uses a nasty out of control DTO class called EE_Checkout, that holds most of the data while things are being passed around. From it you can find anything you want with regards to questions, and tickets. So for example, after the attendee information registration form is submitted, you could get the reg form question answers from the registrations for each attendee like this:

```php
$registrations = $checkout->transaction->registrations;
foreach ($registrations as $registration) {
    $answers = $registration->answers();
    // and if you need to know the question for the answers
    foreach($answers as $answer) {
        $question = $answer->question();
    }
}
```


lastly, Event and Ticket metadata can be retrieved from their corresponding objects like:

```php
$event_metadata = $event->get_post_meta();
$ticket->get_extra_meta();
```

the reason for the different methods above is because EE_Events are a hybrid of the WordPress Custom Post Type (CPT), and therefore use post meta, but EE_Tickets are not CPTs and therefore do not, but still have their own meta data system via our built in ORM.

Hope that helps.
```

**Comment by thebeline** [comment]
I will look into this.

I have two reasons for looking at custom Ticket Metadata, the full check-in I was talking about in another Issue, and this validation thing.  I am inclined to have the full check-in thing be a checkbox selector, and I am considering this validation thing to be a little more general purpose and maybe not really coded for directly in any "core" way.

I guess this then becomes a question for you guys:

- Do you think the check-in in full functionality is something that should be a "core" thing, and thus have it's own column/property on the object?
- My thought with "validation" is shaping up to being something like "Ticket Tags", which would just be a text-field with free-form input that could be coded for in the back-end.

Both things could be either core functionality (with their own columns and "part" of the object), or snippets.  I, personally, think they are useful enough, and relatively minor enough, that they could be "core" things, but it is up to you.

The check-in in full functionality I believe speaks for it's self.  The Tags functionality I think is a little more obscure, but would look something like:

```
$requires_adult = $provides_adult = false;

foreach ( $tickets as $ticket ) {
    $tags = array_flip(explode(' ', $ticket->get('TK_tags'));

    if ( isset($tags['provide_adult']) ) {
        $provides_adult = true;
        break;
    }

    if ( !$requires_adult  && isset($tags['require_adult') )
        $requires_adult = true;
}

$valid = $provides_adult || !$requires_adult;
```

That is, of course, very simple.  A real validator such as that would take in to account DateTimes.  However, I think tags such as these, perhaps pre-split in some fashion (or not, `str_pos()` or `preg_match()` would do just as well), would be very useful for a **wide** range of purposes, and thus would be well suited for core placement.

Thoughts?

**Comment by tn3rb** [comment]
Your approach for adding ticket data and using it for validating a registration looks like it could work out quite well. Are **we** going to add that functionality into core? Not likely, and certainly not anytime soon, as we have a lot of other mountains to move first. 

If you did want to keep critical business logic in db columns instead of meta data so that it is easier and more efficient to query against, then it is certainly possible to extend our core model classes and model object classes, but that would be more complex than what you have going now.

**Comment by thebeline** [comment]
I want to thank you guys for the positive feedback.

I currently have these changes in my local copy of EE, and I noticed EE tried updating something in the past dew days (it can't, not via cron anyway), so what I will probably be doing is diffing against the latest version, breaking any modifications to tables/core functionality out into a plugin, adding the hooks I need to make that work, pushing **that** PR up, and waiting to see if that PR makes it into master before updating.

That is, unless I see come critical patch that needs to come through, in which case I will add the hooks in-line again...  ;-/  I take it that hooks are easier for you to accept and merge in than some of the other stuff?  :-D

**Comment by tn3rb** [comment]
yes hooks are typically easy for us to merge in
