### ISSUE TITLE
Research Alternatives to Moment JS

### ISSUE THREAD

**Issue by tn3rb** [eventespresso/event-espresso-core#1937]
Need to know the various **Pros & Cons** of various Date libraries 

example:

Library | Pros | Cons
--- | --- | ---
Moment JS | great browser support | older library, does not support tree shaking or other modern JS capabilities

#### Possible Alternatives 
- Luxon
- Date-Fns
- ???

plz try not to spend more than 4 hours on this

**Comment by nicolad** [comment]
| Library   | stars | created      | Tree-shaking | Pattern | TS support                                                          | I18n                                                                                       | Timezone support                                                  |
| --------- | ----- | ------------ | ------------ | ------- | ------------------------------------------------------------------- | ------------------------------------------------------------------------------------------ | ----------------------------------------------------------------- |
| Moment JS | 42930 | Mar 1, 2011  | no           | OO      | yes                                                                 | yes                                                                                        | Good(moment-timezone)                                             |
| Luxon     | 8846  | Nov 30, 2015 | no           | OO      | not yet, there is a [WIP](https://github.com/moment/luxon/pull/548) | [Luxon uses the native Intl API](https://github.com/moment/luxon/blob/master/docs/intl.md) | Good(Intl)                                                        |
| date-fns  | 20599 | Oct 6, 2014  | yes          | FP      | yes                                                                 | 67 locales available                                                                       | [yes](https://date-fns.org/v2.0.0-alpha.27/docs/Time-Zones#usage) |
| dayjs     | 24564 | Apr 10, 2018 | no           | OO      | [yes](https://github.com/iamkun/dayjs/pull/37/files)                | yes                                                                                        | need more info                                                    |

**Comment by nicolad** [comment]
@tn3rb @manzoorwanijk @raphaelkross  take a look here :point_up:

**Comment by nicolad** [comment]
WIP
***
| Library   | pros                                                                                                                                                                                                                                                                                              | cons                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
| --------- | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| Moment JS |                                                                                                                                                                                                                                                                                                   | - uses chaining <br> - Moment.js is mutable and it causes bugs <br> - Complex OOP API (which doubles mutability problem). <br> - Moment.js has a huge performance overhead because of complex API <br> - It is highly based on OOP APIs, which makes it fail to work with tree-shaking, thus leading to a huge bundle size and performance issues. <br> - <br> - <br> - <br> - <br> - <br> - <br> - <br> - <br> - [comparison with date-fns](https://github.com/date-fns/date-fns/issues/275) |
| Luxon     |                                                                                                                                                                                                                                                                                                   | - uses chaining <br> - uses [OOP](https://moment.github.io/luxon/docs/manual/tour.html#your-first-datetime) <br> - <br> - <br> - <br> - <br> - <br> - <br> - <br> - <br> - <br> - <br> -                                                                                                                                                                                                                                                                                                      |
| date-fns  | <br> - works with the native date type <br> - Functionality-wise date-fns equals to Moment.js. <br> - All of date-fns's code are pure functions (and simple to grok) <br> - Locale and internationalization as configs to display functions<br> -<br> -<br> -<br> -<br> -<br> -<br> -<br> -<br> - | ---------                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
| dayjs     | - Similar API as Moment.js                                                                                                                                                                                                                                                                        |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |

https://blog.bitsrc.io/9-javascript-date-time-libraries-for-2018-12d82f37872d
https://inventi.studio/en/blog/why-you-shouldnt-use-moment-js

**Comment by nicolad** [comment]
| Library   | pros                                                                                                                                                                                                                                                            | cons                                                                                                                                                                                                                                                                                                                                                                                                                                       |
| --------- | --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ |
| Moment JS |                                                                                                                                                                                                                                                                 | - uses chaining <br> - Moment.js is mutable and it causes bugs <br> - Complex OOP API (which doubles mutability problem). <br> - Moment.js has a huge performance overhead because of complex API <br> - It is highly based on OOP APIs, which makes it fail to work with tree-shaking, thus leading to a huge bundle size and performance issues. <br> <br> - [comparison with date-fns](https://github.com/date-fns/date-fns/issues/275) |
| Luxon     | - Make all the types immutable. <br> - Use the Intl API to provide internationalization. <br> - Luxon has the best time zone support of any JS date library.<br> - Explicit API: Function names describe exactly what they do so it's easier to work with. <br> | - uses chaining <br> - uses [OOP](https://moment.github.io/luxon/docs/manual/tour.html#your-first-datetime)                                                                                                                                                                                                                                                                                                                                |
| date-fns  | <br> - works with the native date type <br> - Functionality-wise date-fns equals to Moment.js. <br> - All of date-fns's code are pure functions (and simple to grok) <br> - Locale and internationalization as configs to display functions<br>                 | - When comparing a certain date to the current date the function returns a pretty "opinionated" sentence such as "almost 2 years" which can't really be customizable and requires string manipulation to fit result to your needs.                                                                                                                                                                                                         |
| dayjs     | - Similar API as Moment.js                                                                                                                                                                                                                                      |                                                                                                                                                                                                                                                                                                                                                                                                                                            |

### Related links

https://blog.bitsrc.io/9-javascript-date-time-libraries-for-2018-12d82f37872d
https://inventi.studio/en/blog/why-you-shouldnt-use-moment-js
https://blog.logrocket.com/4-alternatives-to-moment-js-for-internationalizing-dates/
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DateTimeFormat

**Comment by nicolad** [comment]
@tn3rb @manzoorwanijk @raphaelkross 
***
The floor is open to comments/ thoughts

**Comment by tn3rb** [comment]
well based on the above, `date-fns` looks like the  clear winner.

re: 
> When comparing a certain date to the current date the function returns a pretty "opinionated" sentence such as "almost 2 years" which can't really be customizable and requires string manipulation to fit result to your needs.

which function is that referring to?
are there other comparison functions that can be used?

**Comment by nicolad** [comment]
> well based on the above, `date-fns` looks like the clear winner.
> 
> re:
> 
> > When comparing a certain date to the current date the function returns a pretty "opinionated" sentence such as "almost 2 years" which can't really be customizable and requires string manipulation to fit result to your needs.
> 
> which function is that referring to?
> are there other comparison functions that can be used?

It's `distanceInWords` [function](https://date-fns.org/v1.30.1/docs/distanceInWords), but we might want to have our own utility function instead and that can use another lib(maybe).

**Comment by nicolad** [comment]
`are there other comparison functions that can be used?` - I don't know yet/ didn't investigated a separate function/lib/package, but if we'd go with `date-fns` we are can pick whatever solution we want since it's using `Date` object type as input and output, so we are not locked into some specific library object type, like in case of `moment` or other.

**Comment by manzoorwanijk** [comment]
@nicolad great details dude! 🥇

**Comment by manzoorwanijk** [comment]
I also agree that `date-fns` looks to be the best.

**Comment by nicolad** [comment]
Ok, I also agree with `date-fns`.
@tn3rb we need to think of a pathway because we don't want to use the same approach as with datetime JS model.
***
Here is one high-level example: https://github.com/palantir/blueprint/tree/develop/packages/datetime/src/common
we can have smth similar, but without moment

**Comment by tn3rb** [comment]
that package isn't using moment... 
or did you just mean we can do something like but not use moment like the EDTR v1 Date VOs ?

**Comment by nicolad** [comment]
> or did you just mean we can do something like but not use moment like the EDTR v1 Date VOs ?
yes, ezactly this :point_up:

**Comment by tn3rb** [comment]
I had a good look through the [date-fns docs](https://date-fns.org/v2.8.1/docs/) and I think they have everything we need already covered.
That said, we'll still need to build some predicates that will operate directly on our entity types

ie: `sortTicketsByStartDate()`

these can be composed from smaller building blocks located in `assets/prototype/domain/shared/predicates`

Going to close this now because we are ready to move on to the next step: #2041
