### ISSUE TITLE
How to get attendees data after Thank you page?

### ISSUE THREAD

**Issue by iammomin** [eventespresso/event-espresso-core#195]
Hello Event Espresso,

I want to integrate Event Espresso with SalesForce.

For that i need to fetch the all attendees details after Thank you page.
How to fetch all attendees details using filter or hook of Event Espresso?
I have tried with

`
add_action( 'AHEE__EE_Registration_Processor__trigger_registration_update_notifications', 'custom_attendee_data', 10, 2 );
function custom_attendee_data( $registration, $additional_details ) {
if ( $registration instanceof EE_Registration ) {
     print_r($registration->attendee());
}
}
`

If there is only one attendee,i can get the basic details using above code, but if there are more then one attendees then how to fetch details of all attendees (i.e. How to loop to get all attendees)?

Second point, i was unable to fetch the details that are stored via custom form fields other then the default form fields provided by the Event Espresso.

If there is only one attendee,i can get the basic details using above code, but if there are more then one attendees then how to fetch details of all attendees (i.e. How to loop to get all attendees)?

Second point, i was unable to fetch the details that are stored via custom form fields other then the default form fields provided by the Event Espresso.

How to fetch custom form fields via hooks and filters for corresponding attendee?
Stuck since last Monday.Hoping for the solution.

Thanks

**Comment by mnelson4** [comment]
I'd suggest using the action `AHEE__EE_Transaction_Processor__update_transaction_and_registrations_after_checkout_or_payment` which gives you the `EE_Transaction` as the first argument, which should have just been completed. You should check the transaction is completed, and then use its helper method to fetch its attendees. Something like this

```
add_action( 'AHEE__EE_Transaction_Processor__update_transaction_and_registrations_after_checkout_or_payment', 'my_ee_addon_transaction_completed_logic', 10, 2 );
function my_ee_addon_transaction_completed_logic( $transaction, $details ) {
  if( ! $transaction instanceof EE_Transaction || ! $transaction->is_completed() ){
    return;
  }
  $attendees = $transaction->attendees();
  //do whatever you want to do with the attendees
  //and if you want their most recent registration's custom question's answers
  foreach( $attendees as $attendee ) {
    $their_registration = $attendee->get_most_recent_registration();
    //get their registrations answers to custom questions
    $answers = $their_registration->answers();
    foreach( $answers as $answer ) {
      //you probably want to know which custom question their is an answer for
      $question = $answer->question();
      //do something with their custom question's answer
    }
  }
}
```

That will get you each attendee, their most recent registration, and their registration's answers to custom questions (FYI custom questions are attached to the registration, whereas standard system questions are stored on the attendee. This is because the standard system questions are considered to be the same for all their registrations)

**Comment by iammomin** [comment]
Hi Nelson,

Thank you for your valuable Time to reply for this question.

I have implemented this code and it work and i am getting the result for custom question.

Here i have used `$question = $answer->question();`  and receive the Question name with Strlen of the question, but how should i get the answer for corresponding question.

I have tried with `$question = $answer->answer();` but Fatal error was generated on screen
Will you please help me out in solving this issue?

Thanks

**Comment by nerrad** [comment]
You're getting a fatal because you're trying to call a method that does not exist in the `EE_Answer` object.  The variable `$answer` is holding an instance of [`EE_Answer`](https://github.com/eventespresso/event-espresso-core/blob/master/core/db_classes/EE_Answer.class.php).   If you search through that class you'll find the method you want.

**Comment by mnelson4** [comment]
Yeah darren is referring to https://github.com/eventespresso/event-espresso-core/blob/master/core/db_classes/EE_Attendee.class.php
But an IDE (phpstorm, netbeans, eclipse, etc) should help you identify what methods are available on the objects retrieved.
Let us know if you have further questions
