### ISSUE TITLE
Looking for action hook

### ISSUE THREAD

**Issue by anvilzephyr** [eventespresso/event-espresso-core#196]
### Is this a bug report?

* [ ] yes
* [x ] no

This is EE4
I'm looking for a hook when a registration is completed regardless of payment method. The code uses promotions as gift certificates. Gravity Forms creates a promotion but the price needs to be modified if used during registration.

add_action( 'wp_ajax_espresso_submit_promo_code','ff_get_promo_code');
add_action( 'wp_ajax_nopriv_espresso_submit_promo_code', 'ff_get_promo_code' );
      
      function ff_get_promo_code(){
         $cart = EE_Registry::instance()->SSN->cart();
         if ( $cart instanceof EE_Cart ) {
            $total = $cart->get_cart_grand_total();
            if ($total>0 && isset($_POST['promo_code'])){
               $code = filter_input(INPUT_POST,'promo_code',FILTER_SANITIZE_STRING);
               $EEM_Promotion = EE_Registry::instance()->load_model( 'Promotion' );
               $promotion = $EEM_Promotion->get_promotion_details_via_code( $code );
               if ( $promotion instanceof EE_Promotion ) {
                  $promotion_array = get_transient( 'promotion_'.$code.'_' . session_id() );
                  if (!is_array($promotion_array))
                     $promotion_array = [$promotion];
                  else $promotion_array[] = $promotion;
                  set_transient( 'promotion_' . session_id(), $promotion_array, 60 * 60 * 1);
 // actions here are not firing
                 add_action('AHEE__EES_Espresso_Thank_You__init_end',  'ff_adjust_promo_code');
               }
            }
         }
      }

I've tried several, but nothing fires. Thanks for any guidance or suggestions. FYI the hook is added to the action callbacks array:
[ff_adjust_promo_code] => Array
                        (
                            [function] => ff_adjust_promo_code
                            [accepted_args] => 1
                        )

**Comment by anvilzephyr** [comment]
I don't know. This may be just an error in my code. I'm testing with wp hooks and still not firing. It looks like I can use the hook AHEE__EES_Espresso_Thank_You__init_end so if you could confirm that that hook should work, I'll continue to debug the issue on my own. Thanks!

**Comment by tn3rb** [comment]
> I'm looking for a hook when a registration is completed regardless of payment method.

I'm not exactly sure what you are looking for because some of the terms being used have multiple meanings, which can confuse things.

Do you mean when the registration form is completed, or when an EE_Registration object is approved?

I'm assuming you mean the first since you have been looking at hooks on the Thank You page. If so, then I would recommend using: "AHEE__EE_SPCO_Reg_Step_Finalize_Registration__process_reg_step__completed" which fires just before users get redirected to the Thank You page.

I have no idea why the "AHEE__EES_Espresso_Thank_You__init_end" hook isn't firing for you, which should happen when the ESPRESSO_THANKS_YOU shortcode is parsed on the Thank You page, so as long as you are setting your ` add_action() ` prior to the ` the_content() ` running, you should be ok.

Now, all of that said, because you mentioned that you want to modify the price, I would think that you should do that as soon as the Promo code has been submitted and verified, which would happen prior to any payments being processed. But maybe you are doing something completely different.

Please let me know if there is anything else we can do to assist you.

**Comment by anvilzephyr** [comment]
Thanks Brent. I'll check the hook you suggested. I don't know when the point of no return is passed (as in the registration is in the system and considered paid). I want to reduce the promotion amount past that point so there is no chance of a user backing out but having their coupon amount reduced. That is why I was trying to wait as long as possible but still have access to the transaction. Thanks!

**Comment by tn3rb** [comment]
@anvilzephyr 
any feedback on how things worked out for you?
If there is nothing else we can help you with regarding this issue, then I'm going to close this ticket.
thnx

**Comment by anvilzephyr** [comment]
@tn3rb I ended up successfully using AHEE__EE_SPCO_Reg_Step_Finalize_Registration__process_reg_step__completed. Thanks again for your help!
