### ISSUE TITLE
BUG: Error with the payment method configuration – Multiple payment gateways

### ISSUE THREAD

**Issue by scwirrel** [eventespresso/event-espresso-core#198]
### Is this a bug report?
* [x] yes
* [ ] no

### What branch did this occur in?
master (release 4.9.26)

### What version of WordPress is on the site this issue happened?
4.71

### Outline the steps to reproduce
I've been advised to post this in GitHub from your support team in the forum: https://eventespresso.com/topic/problem-with-the-payment-method-configuration-multiple-payment-gateways/#post-229270

We are currently in the process of integrating our Event Espresso installation with Apple Pay, using Stripe as the payment gateway. We are able to process payments successfully using Apple Pay but an frustrating issue has now occurred now that we have both a “Stripe Apple Pay” payment gateway and the official EE Stripe gateway active at the same time.

If a user selects a payment gateway and then changes it (i.e clicking on Apple Pay then changing to Stripe), a red error box appears saying
“An issue that has appeared There appears to be a problem with the payment method configuration! Please refresh the page and try again or contact support.”
However if the user clicks the gateway again, it opens correctly and a user is able to make payment.

After some investigation, the issue is related to the display_payment_method function of the SPCO JS and AJAX that gets the billing form for the payment gateway using admin-amax.php.
When looking at the AJAX request made by this function, the Ajax data sent is as follows:
step=payment_options&action=switch_spco_billing_form&selected_method_of_payment=bank&reset_payment_method=1&generate_reg_form=1&process_form_submission=0&noheader=1&ee_front_ajax=1&EESID=207f7b1bc534c38537321e41cba34f37&revisit=&e_reg_url_link=

Sometimes this works correctly and sometimes just returns 0, suggesting there is some issue with how EE handles Ajax requests.

To try to isolate the issue, we have deactivated all custom plugins and theme. This issue still persists when using a default WordPress theme, having only official EE plugins active and setting both EE Stripe and Bank Transfer as the active payment methods. Strangely when using our Apple Pay gateway and the Bank Transfer gateway, the issue only occurs when selecting the bank. The issue never occurs when selecting Apple Pay in this scenario. And once the message has appeared once for a payment gateway, it never reappears and the user can switch between them with no issues.

### Please include any screenshots ar screencasts that can help illustrate the issue (if possible).

![screen shot 2017-01-21 at 01 10 17](https://cloud.githubusercontent.com/assets/25306644/22218977/efe8790c-e1a0-11e6-954f-fedc6cbff51e.png)
<img width="1234" alt="screen shot 2017-01-21 at 01 10 48" src="https://cloud.githubusercontent.com/assets/25306644/22218981/f178c97a-e1a0-11e6-9601-2def247b1191.png">
<img width="1237" alt="screen shot 2017-01-21 at 01 11 02" src="https://cloud.githubusercontent.com/assets/25306644/22218993/fde09882-e1a0-11e6-8a2b-481edaf60201.png">
<img width="1227" alt="screen shot 2017-01-21 at 01 11 10" src="https://cloud.githubusercontent.com/assets/25306644/22218996/ffbf931a-e1a0-11e6-9f96-8d9dd528bd86.png">

### Please include any links to the page(s) demonstrating this issue (if possible).
The issue occurs on the registration checkout page. You can create a registration on our staging site to test this here: https://staging.tickets.chesterfoodanddrink.co.uk/tickets/saturday-15th-april/

**Comment by mnelson4** [comment]
hi @scwirrel so did you copy the entire stripe add-on and rename it or something? Otherwise I'm not sure how you have both Stripe-with-Apple-pay and regular Stripe setup at the same time.

And yes there's an issue where no two Stripe gateways can be active at the same time. Can you reproduce if the normal Stripe payment method is deactivated (leaving only your Stripe-with-Apple-pay gateway and Bank active)?

Also, are the screenshots you provided with `WP_DEBUG=true` and `WP_DEBUG_DISPLAY=true`? It looks like having the two active is causing a fatal error, and there should be more output if that's the case

**Comment by scwirrel** [comment]
Hi Mike.

The Apple Pay add on we created used the boilerplate payment gateway you have in GitHub and some of the functions in the EE stripe add on however the class instances in our add on have all been renamed so although similar, they are different. Another significant difference is that Apple Pay requires the Stripe.js to create the token and your stripe addon uses the stripe checkout js.

Regardless of that, I've found this issue occurs even when just the EE stripe gateway and bank is active and the Apple Pay addon is deactivated completed. It seems the issue is caused regardless of the payment methods.
![screenshot](https://cloud.githubusercontent.com/assets/25306644/22223298/4f8b8c30-e1b2-11e6-834b-8394a7e651b0.png)
In this case I'd just gone from Stripe to Bank

The Screenshots provided are with WP_DEBUG as true. WP_DEBUG_DISPLAY is not defined in our wp-config

**Comment by mnelson4** [comment]
Ok thanks that's helpful info. In this last screenshot, is your Stripe-with-Apple Pay add-on active? (I can see the payment method is inactive, but how about the add-on that contains the payment method?) That might help give us a clue where to start looking

**Comment by scwirrel** [comment]
No, in the screenshot the actual plugin is deactivated from in WordPress.

**Comment by mnelson4** [comment]
ah ok, so that clearly excludes your plugin from being the source of the problem. What other add-ons do you have active? And what versions of EE core, stripe, and other add-ons do you have?

**Comment by scwirrel** [comment]
Heres the plugins we have active. 
<img width="1212" alt="screen shot 2017-01-21 at 01 11 33" src="https://cloud.githubusercontent.com/assets/25306644/22225370/1ebe2ede-e1ba-11e6-889b-182a1a656177.png">

We have deactivated everything including reverting to the Twenty Sixteen theme to prevent any conflicts.

**Comment by mnelson4** [comment]
thanks we're investigating to see if we can reproduce this issue with those add-ons active

**Comment by tn3rb** [comment]
@scwirrel 
I'm unable to recreate the issue you are reporting on my local test site nor on your staging site.
I can click between the two payment options with no problems. After selecting Stripe, I can click the "Pay Now" button, and the payment modal window appears correctly. You do not currently have your Stripe payment method in test mode, so I am unable to test any further, but the form appears to react correctly to anything that I enter into the Stripe form.

<img src="https://box.everhelper.me/attachment/735783/48492334-2d6e-4612-8dac-e89d667acbe7/288536-HpbgyMwx7sLvRyr4/screen.png">

Have you made any changes to your payment method configurations in the Event Espresso admin since first posting above? Even simply resaving one of the payment method settings forms without changing anything could have fixed any incorrect info in the database.

If that is not the case, then what internet browser and computer IS are you using for testing? 
ie: Safari on Mac, or Edge on Windows 10, etc.

**Comment by mnelson4** [comment]
@Pebblo suggested there might be a caching issue. We're not sure what your add-on was doing but maybe it was loading a different JS file that was having issues and now that it's deactivated we're not having problems (I actually tried it too, and created a video showing it working for me: https://drive.google.com/file/d/0B5P8GXTvZgfMN2JnNVhUUUszNlE/view), but you might have been getting a cached version of the js file. So if you clear your browser's cache, does it work for you too?

Assuming it works for you again, maybe you should try using your Apple-pay-with-stripe add-on with Stripe deactivated

**Comment by scwirrel** [comment]
I don't it's a caching issue. I've just created a fresh Wordpress install on a new server and domain with a fresh EE database and purely the EE addons activated and I'm having the same issue using my Mac on Chrome and Safari.
https://scwirrel-my.sharepoint.com/personal/ross_gaskell_scwirrel_com/_layouts/15/guestaccess.aspx?docid=0cb18f91cc3344025939548d69381dc88&authkey=ARMuGb5kCwy3s3aGqbihspE

I'll test this on our PCs in work to see but I'm probably better doing as you say, extending our Apple Pay add on to support entering card details manually so we only have one payment method active at one time. When there is only one, it works perfectly.

**Comment by tn3rb** [comment]
If you watch the Network tab in your browser's dev tools, you can see that additional Stripe resources attempt to load when you click the Invoice payment method the second time. This is basically hwat is happening:

 * click "Proceed to Payment Options" button
  * two AJAX requests are triggered (submit step 1 form & retrieve step 2 form)
 * click on Invoice payment method
  * one AJAX request is triggered (switch payment method)
 * click on Stripe  payment method (this is where it starts to get weird and your site deviates from what happens when I watch my test site) 
  * one AJAX request is triggered (switch payment method)
  * on my test site, Stripe makes a bunch of GET requests to retrieve it's resources from various Stripe related URLs, but on your site, your Stripe payment method sends additional AJAX POST requests to staging2.chesterfoodanddrink.co.uk and only a couple of GET requests to Stripe related URLSs
 * THEN when you click on the Invoice payment method a second time, there are additional GET requests sent to Stripe as well as the expected AJAX request (switch payment method), whereas on my test site, Stripe ceases to function when another payment method is clicked.

So what does this mean? It appears to me that the following things are happening:

 * the additional AJAX POST requests made to your server when selecting Stripe, indicate that something is not configured properly, and it is looking for resources locally that **should** be retrieved via GET requests from Stripe. 
 * since Stripe is making additional requests when you click on the Invoice payment method a second time, there must be one or more listeners that are incorrectly attached to all ".spco-payment-method" elements in the DOM. 

I have a couple more questions for you to try and help me find a solution to this

 1. Was that the EE Stripe payment method in that screen cast or your Appl Pay one?
 2. How is your JavaScript for your ApplePay payment method getting loaded? As in where and when? Is it getting loaded the same way our addons do, or are you loading it elsewhere on every request as is typical in WordPress (ie: load ALL resources everywhere)?

I tested the checkout of your http://staging2.chesterfoodanddrink.co.uk site and did NOT see the same results that you received in your screencast and everything ran the same as when I test locally, ie: Stripe did not attempt additional requests when I clicked on the Invoice payment method a second time. This leads me to believe that it is either:

 * something funny is happening with browsers on Mac, which I am going to go test in a minute because my wife uses Macs, but seems odd because most of the Event Espresso team members are using Macs, and have never experienced this problem  (as far as I know)
 * OR something funny happening specifically with your computer's configuration. Do you have any browser addons setup? Do you have HTTP caching disabled when your dev tools is open? Are there any other web related programs you have running that may be interfering with things? Are you accessing the sites via a VPN? Can you try another computer or access via another network?

I'm sorry if that last batch of questions sounds accusational, but we really have to start turning over some odd rocks looking for a solution when only one person has a problem that can not be recreated by others, even when testing on the same site. Your https://staging.tickets.chesterfoodanddrink.co.uk/ site that you posted yesterday as well as your http://staging2.chesterfoodanddrink.co.uk site that you were using in your last screencast, BOTH behave correctly for myself and do not display any errors. It sounds like Michael also did not have troubles with the first site. Michael and I are both using PCs, so it's possible the issue is related to Macs, but again, most of the Event Espresso team members are using Macs, and have never reported this issue. 

Other possibilities that may explain why only you (as far as we know at this time) are experiencing troubles, are:

 * maybe the issues only occur when you are logged in! Log out and try the reg process again.
 * maybe you have inadvertently changed something on the server or site setup AFTER you have experienced the issue, that causes the issue to not happen when we visit those sites.

So anyways,  please confirm that this is issue still occurs if you use another computer, or use your computer via a different network (if possible). I am going to go test your site on my wife's Mac now, and will report back.

**Comment by tn3rb** [comment]
http://staging2.chesterfoodanddrink.co.uk works correctly from my wife's Mac using Firefox, Chrome, and Safari. Therefore this does not appear to be a Mac related issue, unless you are running a really old version of Mac OS.

So please test this using:

 * a different computer
 * a different network

let us know what you find

**Comment by scwirrel** [comment]
That is so bizarre, I have the same issue on my work PC as my Mac. Both are on different networks and ISPs.   Both computers are up to date (running macOS Sierra and windows 10 respectively).

![capture](https://cloud.githubusercontent.com/assets/25306644/22260760/49eb02fa-e262-11e6-91b8-48276ff9f543.PNG)

Our Apple Pay add on is completely deactivated, we are using the official EE Stripe add on on the staging2 site. HTTP caching is enabled, both computers are not working over a VPN and as you can see in the screenshot above I am logged out, and have not logged into site before on this machine.

**Comment by nerrad** [comment]
Just want to post that I gave this a whirl on your site for this event: http://staging2.chesterfoodanddrink.co.uk/events/test/  and I also was *unable* to reproduce the report.

I switched selected the credit card option initially, then switched to invoice and then back again, I never saw the notice.

**Comment by tn3rb** [comment]
@scwirrel 

can you please send me admin creds for one of your testing sites plz?
https://eventespresso.com/send-login-details/
ftp access would be great too, because then I can examine your payment method code as well, and try to recreate the issue locally using your code.

**Comment by scwirrel** [comment]
Brent I can't find your name in the dropdown for who requested login information.

Also not sure if this may help, but I could get you remote access to a VM on our network so that you can test the page on a machine where the error message actually appears.

**Comment by tn3rb** [comment]
> Brent I can't find your name in the dropdown for who requested login information.

oh ha ha... oops... ya I guess only members of the support team are listed there. You can select Josh then if you want, and I'll let him know that those creds are for me.

If you prefer to go the VPN route, that's fine too, but don't post anything here for obvious reasons, just add the VPN info to that form

**Comment by scwirrel** [comment]
No problem, I'll get that to you tomorrow

**Comment by tn3rb** [comment]
@scwirrel 

okay we think we figured it out...

Ready?

You're clicking too fast.
You're not waiting for the Stripe payment method to fully load and retrieve all of it's resources before switching to Invoice. It's possible that some of the Stripe resources are taking longer to load for you in the UK, than they do for us in North America because we are likely closer to the Stripe servers. It took one of our support staff in the UK (awesome guy named Tony) to figure out that if he clicked back and forth really fast between payment methods, that he could trigger the error. 

So try it again, but slow down with the clicking (or get a faster server if you have the need for speed).

That said, we'll continue to look into the issue, to see if there is any user proofing that can be put in place to stop speed demons like yourself from breaking things.

**Comment by scwirrel** [comment]
Haha! I am known in the office for being too impatient with a mouse.

Low and behold slowing down the switch does fix the error. That being said, even if I swapped between them with a 5 second delay the error still occurs. You really have to slow the click down.

Also because the loading cog icon disappears, I assumed that it had fully loaded even though it hasn't. If the Stripe add on JS could either have this cog remain on screen or at least prevent the switching of payment method until Stripe has fully loaded that would prevent any other trigger happy users from getting an error especially as the UK does have rather poor internet speeds in a number of areas (without our fibre line, standard DSL in our area of Chester is around 3-5mbps with fibre an expensive luxury/necessity)

I think it is better for us however to just stick to our Apple Pay add on and extend that to have a card form that we can tokenise with Stripe JS, rather than having to load that as well as Stripe Checkout and the other resources from the Stripe add on.

**Comment by tn3rb** [comment]
I agree totally about the loading gif vanishing too early with Stripe, and now that we have confirmed the issue, I am going to create a ticket to look into why that is the case.

This is the first time this issue has come up that I am aware of, so hopefully you won't have any troubles with before we get a fix out.

**Comment by scwirrel** [comment]
I know its the first time I've had this issue as well. We've been running EE on our production server with just the Stripe add on activated for a couple of weeks without any issues at all.

Thanks for your help with this. Glad it is an issue and not me going crazy!

**Comment by tn3rb** [comment]
No worries, glad we can help, and hope your event is a great success.
Don't hesitate to ask us for any help you might need.

for internal ref: https://events.codebasehq.com/projects/event-espresso/tickets/10424
