### ISSUE TITLE
Storing and loading model object traversal state

### ISSUE THREAD

**Issue by mnelson4** [eventespresso/event-espresso-core#2018]
## Issue Overview

On https://github.com/eventespresso/event-espresso-core/pull/1977 I add `\EventEspresso\core\services\orm\tree_traversal\ModelObjNode`, which takes a model object, and then recursively discovers its dependent model objects (ie, model objects that have a foreign key to it). It can take a break mid-search and then pickup where it left off (its parent class has a method `\EventEspresso\core\services\orm\tree_traversal\BaseNode::visit` which accepts `$model_objects_to_identify`, which is a count of how many objects to identify in this batch). So far, that's been shown to work, provided we do all the discovering during a SINGLE HTTP request, so the thing can be stored in-memory.
In order to complete https://github.com/eventespresso/event-espresso-core/issues/1904, we need to be able to do that across MULTIPLE HTTP requests, in order to support doing it via a batch process. So the question is: how to persist the state of how far along we are in the model object tree traversal/discovery across HTTP requests?

The easiest way would be to just serialize the object and dump it into a WP option. But that has blown up for us in the past, and it that might not be efficient enough to work...

The trouble is we're going to inevitably be dealing with some events with thousands of registrations, which, if we don't store the data compactly, could easily get too big for the WP options table (yes, according to MySQL, you should be able to store GBs of data in each cell; but shared hosts are limited to sending about 1 MB of data in each insertion/update query, so the effective limit is actually around 1 MB; we've encountered this limit while doing migrations which is why migrations use multiple options, one for each `EE_Data_Migration_Script_Stage`.)

## The current approach: Recursive ModelObjNodes

I had assumed I'd use the `\EventEspresso\core\services\orm\tree_traversal\ModelObjNode::toArray` to convert the `ModelObjNode`s into an array, which can be JSON-encoded into a WordPress option; then have a static method (or a factory) for generating the objects from that JSON string on the subsequent requests.

When we're keeping track of thousands of model objects, converting the tree of `ModelObjNode`s into an array then into a JSON string, sending it to the DB; then on the next request, turning that JSON string into an array, then that array into a plethora of objects (one `ModelObjNode` and several `RelationNode`s for each model object), I'm worried that might use up a lot of memory and CPU.

So really, the problem isn't just "how to persist state" between requests, but how to do so **efficiently** enough to handle an event with thousands of registrations.

## Alternative: a single ModelObjDiscoverer class
One alternative idea I've had: don't bother having `ModelObjNode`s and `RelationNode`s. Just have a single business class, called something like `ModelObjDiscoverer` that explores the tree, and stores its data to an array directly. When it comes time to save to the DB, it just converts that exact array into a JSON string; and when it loads, it loads it directly from a JSON string into an array. That should be much easier on memory as we're not building a giant tree of objects, just the one mandatory array. That array would also be as compact as possible in order to fit into WP option's 1MB limit.

## A yucky alternative: use multiple WP options or a separate table
In some combination with the above options, we could also store the state into multiple WP options, or a new DB table. It would be a bit of a pain needing to fetch the tree in pieces, and, if we needed to re-fetch the entire tree from multiple database options on each request, it would partially defeat the purpose of traversing the tree ahead of time and storing it to the DB (because the data's already in the DB, it's just dispersed so we're trying to aggregate it.) 

Also a reminder: I've got until January 3rd for this project (and this is the biggest unknown; everything else is pretty straightforward.)

Thoughts on the best approach to solve this problem?

See https://github.com/eventespresso/event-espresso-core/issues/1904 for some more context.

**Comment by tn3rb** [comment]
#### Alternative: Separate Traversal and Data Storage Objects

Currently you are using recursive `ModelObjNode` classes but are considering using a single `ModelObjDiscoverer` class.nother alternative would be to keep the recursive `ModelObjNode` classes that are responsible for acquiring data for a single node  but use a single data structure

**Comment by tn3rb** [comment]
#### Alternative: Separate Traversal and Data Storage Objects

Currently you are using recursive `ModelObjNode` classes but are considering using a single `ModelObjDiscoverer` class.
Another alternative would be to keep the recursive `ModelObjNode` classes but refactor them so that they are only responsible for acquiring data for a single node and then use a separate single data structure for storing all of the node data. 

In other words, multiple service classes that do the work but don't retain any data, and a single separate class for handling data storage.

Then at the end of a batch request, you only have to serialize the contents of the data handler (which would likely do that for you) and then persist to the db in whatever location gets decided upon. I would also recommend using a separate class & interface for handling persistence which would allow it to be changed easily (for testing, or EventSmart, etc). 

Then on the next request, the main Manager class would employ your persistence class to retrieve the stored data, which would then be handed to the data handler which would unserialize it into the same structure it was prior to persistence.

Then main Manager class would employ another class for handling tree traversal within the already discovered data in your data handler, and for locating where you left off after the previous request.

So the process might look like this:

#### Initial Discovery
- CascadingDeletesManager creates NodeDataHandler
- CascadingDeletesManager creates first ModelObjNode and injects NodeDataHandler upon construction
- CascadingDeletesManager unleashes ModelObjNode on the db
- ModelObjNode passes data to NodeDataHandler as records are discovered
- ModelObjNode creates additional ModelObjNode and RelationNode objects as more "nodes" are discovered
- At some point the process stops (and progress is recorded???) either because of:
      - the discovery process finding all records
      - some predetermined limit is reached (ex: max records)
- CascadingDeletesManager loads ObjNodePersistenceHandler and passes it the NodeDataHandler
- ObjNodePersistenceHandler retrieves the serialized data from NodeDataHandler (or maybe does that itself) and persists it to wherever

#### Subsequent Batch Job Requests

- CascadingDeletesManager loads ObjNodePersistenceHandler and NodeDataHandler 
- ObjNodePersistenceHandler retrieves data from storage and passes it to NodeDataHandler 
- discovery continues if not already complete, or
- discovery is completed and CascadingDeletesManager loads the RecordReaper class
- RecordReaper uses the info it gets from NodeDataHandler to commit unspeakable atrocities upon the records of this world
- RecordReaper records its progress within NodeDataHandler (maybe separate progress record or simply by deleting node data after success?)
- At some point the process stops either because of:
      - the carnage is complete and all records have ceased to exist
      - the predetermined batch limit is reached
- ObjNodePersistenceHandler retrieves the serialized data from NodeDataHandler (or maybe does that itself) and persists it to wherever
- rinse and repeat

**Comment by mnelson4** [comment]
Thanks Brent! Great analysis thanks.

> RecordReaper uses the info it gets from the NodeDTO to commit unspeakable atrocities upon the records of this world

😈

> the ModelObjNode and RelationNode classes are refactored to be pure services meaning they do not store ANY state whatsoever and are only capable of receiving data (and other services) and acting upon that data, but do not store anything internally

I'm leaning this way, currently...

For the `NodeDTO`, I'm thinking it will be a wrapper for a PHP array. (It's nice that way we won't be copying this potentially-giant array.) I'm trying to keep my mind open to the SPL data structures, but at least initially a PHP array seems the most convenient.

> generate a unique name for the entire job process and then also give names to each batch (this might already be partially handled by the existing batch job logic, so ignore if this is duplication).
> record data for the entire job process, discovery progress, total number of records, completed batch jobs, current batch job, next batch job, etc (again, this might already be handled extensively by the batch job logic, but I can't remember off the top of my head).

Yeah the batch system would normally take care of these things, I think.

I think for this current ticket, I don't think I'll implement `RecordReaper` or `NodeDataManager` just yet, as I'm just wanting to store and retrieve the state of tree traversal etc. But I they sound appropriate for after I think (my brain struggles that many moves in advance.) 

I'll try to apply these in creating the initial version, although I'll mostly be trying to get something that works rather than following your suggested structure to the tee...

**Comment by tn3rb** [comment]
> For the NodeDTO, I'm thinking it will be a wrapper for a PHP array. (It's nice that way we won't be copying this potentially-giant array.) I'm trying to keep my mind open to the SPL data structures, but at least initially a PHP array seems the most convenient.

Look at the methods on the **SplDoublyLinkedList** class

- add( $index, $value )
- bottom()
- count()
- current()
- getIteratorMode()
- isEmpty()
- key()
- next()
- offsetExists( $index )
- offsetGet( $index )
- offsetSet( $index, $value )
- offsetUnset( $index )
- pop()
- prev()
- push( $value )
- rewind()
- serialize()
- setIteratorMode( $mode )
- shift()
- top()
- unserialize( $serialized )
- unshift( $value )
- valid()

most of these are identical to the functions that you would use to operate on an array but instead of doing:

```php
$number = count( $my_array );
```

you would do:

```php
$number = $my_array->count();
```

and the above also utilizes the `Iterator` interface which means it can be looped over just like a regular array:

```php
$nodes = new SplDoublyLinkedList();
$nodes->push('node A');
$nodes->push('node B');
$nodes->push('node C');
foreach($nodes as $node) {
    // do... node... stuff ???
}
```

so for the most part they should be pretty easy to utilize, despite being something new.

The biggest differences between the above and primitive arrays though are:

 - they can be extended and therefore customized, so a `NodeDTO` class could extend `SplDoublyLinkedList` (or other data structure) and would have ALL of those array like functions built into it and could be type hinted for in function declarations
 - iterator modes: control traversal direction without having to re-sort the array or create duplicates (like some array functions do):
      - IT_MODE_LIFO : The list will be iterated in a last in, first out order, like a stack.
      - IT_MODE_FIFO : The list will be iterated in a first in, first out order, like a queue.
 - control whether items are kept or deleted when looping over them:
      - IT_MODE_DELETE : Iteration will remove the iterated elements.
      - IT_MODE_KEEP : Iteration will not remove the iterated elements.
 - the SPL Data Structures are passed by reference by default since they are objects (could be a downside depending on your use case)

But the main reason I'm pushing them though is because, at least with PHP 7+, they are supposedly faster than arrays and apparently use around half the memory.

Oh wow, I just went to look for some benchmarking info on this and discovered that PHP 7 introduces a new Data Structures extension that includes a bunch of new structures that are supposedly even **MORE** performant: https://www.php.net/manual/en/book.ds.php
too bad those aren't available to us :(

Anyways, couldn't find the same benchmarks I have seen in the past, but here's some slides from a presentation that at least mention the speed  and memory benefits: https://www.slideshare.net/MarkBakerUK/spl-datastructures-24333471

**Comment by mnelson4** [comment]
Oh I see, it has serialize and unserialize methods built in. I thought I'd have to serialize and unserialize to a PHP array, THEN convert that into whatever SPL data structure I was using, which looks like it would double the work and memory.

I played with it and hoped its serializer would maintain the pointer to the current element but it doesn't (it seems each time it gets unserialized, it loses the pointer to where it was last in the list). So that's a bummer.

I'm seeing a few instances where SPL data structures would make the data's usage more clear (eg I certainly have queues and then separate maps), and it would be cool if PHP7 makes it more efficient, but knowing that I'm going to need to serialize the data and store it, efficiently, has me still leaning towards a basic PHP array.

**Comment by mnelson4** [comment]
This got sidetracked as we instead want to optimize some code that's majorly slowing down ES. See https://github.com/eventespresso/event-espresso-core/issues/2035

**Comment by mnelson4** [comment]
This isn't outside the realm of possibility, and the next shepherd of this project may want to attempt this, but I won't be able to, so closing for now in order to tidy up the project.
