### ISSUE TITLE
Differentiate between archived and deleted entities

### ISSUE THREAD

**Issue by manzoorwanijk** [eventespresso/event-espresso-core#2089]
We have `deleted` attribute for many entities in the model system which is referred as `archived` at many places in the codebase. We need to clarify the meaning and usage of these two terms. It's also possible that there are no complete implementations of one/both of these in the code base.

**Comment by tn3rb** [comment]
Here's a list of all of the table models that have a `deleted` field:

- `wp_esp_datetime.DTT_deleted`
- `wp_esp_price.PRC_deleted`
- `wp_esp_price_type.PRT_deleted`
- `wp_esp_promotion.PRO_deleted`
- `wp_esp_question.QST_deleted`
- `wp_esp_question_group.QSG_deleted`
- `wp_esp_question_option.QSO_deleted`
- `wp_esp_registration.REG_deleted`
- `wp_esp_ticket.TKT_deleted`

it likely would have been better to have named these fields `archived` instead of `deleted` because it is a little more accurate of a description for how we are using that. Essentially it means that the "archived" data should not be returned with regular query results and should only be returned when specifically asked for. Another term used within the model system is "soft delete" which means the record is functionally deleted, because it no longer appears in query results, but has not been actually removed from the database, which would be a "hard delete".

I think users may find the term "archive" less frightening than "delete" so for any public facing UI labels or documentation, we should likely favour that.

We may at some point want to consider replacing this single boolean field with an enum field named something like "state" which could then have values like "deleted", "archived", "draft", and operate similarly to the `wp_posts.post_status` field which controls post display and access.

Would love to hear opinions from @joshfeck and @mnelson4 on this matter

**Comment by mnelson4** [comment]
Yeah the terms "soft deleted", "archived", and sometimes even "trashed" are used pretty interchangeably. See https://github.com/eventespresso/event-espresso-core/blob/master/docs/G--Model-System/statuses.md#soft-deletedarchivedtrashable-models
The term "archived" is probably best. Changing it in the database isn't much of an option as it would require quite a lot of headache to migrate the data over (for us, support, and on EventSmart). Changing the PHP methods is more of an option, especially if we first soft deprecate the old methods/names etc. Y'all can do as you please in the client-side code!

**Comment by tn3rb** [comment]
for client side GQl/Apollo logic, let's convert everything to use the term `trashed` instead of `deleted` or `archived`
