### ISSUE TITLE
Hello , I have a question about EE4 REST API checkIn features

### ISSUE THREAD

**Issue by s31b18** [eventespresso/event-espresso-core#211]
Hello , I am now developing a ticket scanning mobile application with EE4 REST API  

In your documentation ,  I find that this is the only endpoint for the checkIn features. 

 - http://mysite.com/wp-json/ee/v4.8.33/registrations/123/toggle_checkin_for_datetime/456

And my question is that is there any endpoint only for checkIn or checkout , since with this endpoint , you can keep checkIn and checkout .

Also , how can I set that a registration is only allowed to checkIn for one time in each date time. 

Thank you

**Comment by mnelson4** [comment]
So you'd like an endpoint that ONLY checks the attendee in; and a separate endpoint for ONLY checking them out, right?

Right now that doesn't exist. To achieve that, you would first send a request to `http://mysite.com/wp-json/ee/v4.8.36/registrations/123/?calculate=datetime_checkin_stati`. That will add a property onto the registration which is a JSON object, where each key is a datetime ID, and the value is their checking status for that datetime, ie  "NEVER" (they have never checked into the datetime), "IN" (they are currently checked in), "OUT" (they checked in earlier, but have since been checked out). Based on that result, you would decide whether or not you want to send a request to toggle their check-in status.

> Also , how can I set that a registration is only allowed to checkIn for one time in each date time.
thoughts @nerrad ?

**Comment by tn3rb** [comment]
> Also , how can I set that a registration is only allowed to checkIn for one time in each date time.

Since the three values for checkins are:

 * Never
 * Checked In
 * Checked Out

if you only want to allow ONE checkin, then only check them in, if the current value is "NEVER" (which I believe is actually a null value or absence of record in the db)
