### ISSUE TITLE
Write Tests for Application Mutations

### ISSUE THREAD

**Issue by tn3rb** [eventespresso/event-espresso-core#2130]
- see `assets\prototype\application\services\apollo\mutations`

this may not be possible, so close this issue if these files are not testable

**Comment by manzoorwanijk** [comment]
After trying to write tests for it, I realized that it's better to test the individual entity mutations instead of testing `useEntityMutator`, because it eventually calls those mutation handlers for each entity and thus making it difficult to test it in isolation. Testing individual mutations will eventually test `useEntityMutator` because all of them are going to use it.
