### ISSUE TITLE
Evaluate Reusability of Data Handling Logic

### ISSUE THREAD

**Issue by tn3rb** [eventespresso/event-espresso-core#2147]
Currently most if not all data handling logic is located in `assets\prototype\domain\eventEditor\data`, but eventually we will begin building out areas of EE's UI that are outside of the event editor. This means we will have to do one of two things:

- potentially copy a lot of the logic in `assets\prototype\domain\eventEditor\data` for the new domain UI
- extract any and all reusable logic from `assets\prototype\domain\eventEditor\data` and move into `assets\prototype\domain\shared\data`

If it is decided that logic can and/or should be extracted for reuse, then we will need to do the following:

- identify and document all extractable logic/components (as a bullet list in this issue)
- discuss any potential changes required, pros/cons/etc
- create new issues for actionable items

**Comment by manzoorwanijk** [comment]
Different areas under `/domain/eventEditor/data` that can be improved/reused:

#### 1. `/queries`

It has a lot of scope for improvement and extraction for reusability. The main hook that almost decides everything what other related hooks will/can do is the query options hook e.g. `useDatetimeQueryOptions` for datetime related queries. By using this hook, other hooks (used for retreiving data) decide about how to ask Apollo for data.

For example, `useDatetimes` retrieves the list of datetimes from **eventEditor** Apollo Cache. It does so by making use of `useDatetimeQueryOptions` to generate the appropriate query. To make it reusable (in other domains), we can pass those query options directly to `useDatetimes` as an optional argument. So the definition of `useDatetimes` would be something like this:

```js
const useDatetimes = (queryOptions?: ReadQueryOptions): Datetime[] => {
	const options: ReadQueryOptions = { ...useDatetimeQueryOptions(), ...queryOptions };
```

So here is the list of hooks inside `/domain/eventEditor/data/queries` that can be extracted using the above appoach:

-   `/datetimes`

    -   `useDatetimes`
    -   `useDatetimeIds`
    -   `useDatetimeItem`

-   `/tickets`

    -   `useTckets`
    -   `useTcketIds`
    -   `useTcketItem`

-   `/prices`

    -   `usePrices`

-   `/priceTypes`

    -   `usePriceTypes`
    -   `usePriceTypeForPrice`
    -   `useDefaultPriceType`

-   `/events`

    -   `useEventId`

##### pros

-   These hooks can literally be used for any domain.

##### cons

-   Extraction comes at the cost of gereralizing things which is sometimes problematic.
-   We may loose some of the TS benefits like the generics passed to `readQuery` (which can be sacrficed IMHO)
-   We will have to get rid of global status flag checks like `if (!isLoaded(TypeName.datetimes))`

#### 2. `/mutations` and `/entities`

There isn't anything there which can be extracted for other domains as the mutation handlers and cache updaters are designed to handle data changes specific to eventEditor. For other domains, we may have to create similar mutation handlers for its data/entities.

#### 3. TS types

Currently TS types are scatterred at many places and are being pulled from different places. They are one of the main reasons for `application` and `domain` sometimes getting coupled. IMHO, we should move all the TS types to `domain/shared` except the ones defined in `/domain/eventEditor/data/mutations/types.ts` because they aren't really being used anywhere else.

**Comment by nicolad** [comment]
Another option might be to use the factory pattern for creating queries/ mutations by accepting apollo instance and `gql` string as args. Maybe.

**Comment by tn3rb** [comment]
> We will have to get rid of global status flag checks like if (!isLoaded(TypeName.datetimes))

hmmm... dunno if I like that... those hooks do not consist of very much logic at all, so let's just keep things where they are for now. As we start to develop additional domains we will see what logic is getting duplicated and will be better able to see what can be extracted and shared.

**Comment by manzoorwanijk** [comment]
I agree with keeping things the way they are until we have another domain to work with.
