### ISSUE TITLE
Re-Evaluate Current EDTR Architecture and Component Dependencies

### ISSUE THREAD

**Issue by tn3rb** [eventespresso/event-espresso-core#2149]
Ideally we want our application to be free of hard coupling and inter-layer dependencies that can potentially limit flexibility, reusability, and testability. So from time to time we want to look through everything and try to find any "brittle"  structures (hard & inflexible) that could be improved before they become too embedded.

**Comment by manzoorwanijk** [comment]
Evaluation 

#### `ConfigProvider`

`ConfigProvider` component inside `/application/services/context/ConfigProvider` uses a bit of logic that should be extracted to a custom hook where all the conditions and calculations will be carried out.

#### `useMutators`

`useMutators` hook inside `/application/services/apollo/mutations` pulls code from `/domain/eventEditor`. IMHO it should belong to `/domain/eventEditor` because it providers the event editor related mutators.

#### `EditDateModal` and `EditTicketModal`

We should extract the use of `useContext` to a hook like `useDateContext` or `useTicketContext` to handover the importing of context to it to give us the data we need.

#### `EditDatetime` and `EditTicket`

These two components are rendered for every list item, which creates lots of instances which may not even be used at all. IMHO we should use a global modal (or at least a single modal for an entity list) and pass it the data that we want it to work with.

#### `TicketPriceCalculator` modal

I have same opinion for TPC modal.

**Comment by tn3rb** [comment]
> `ConfigProvider` component... uses a bit of logic that should be extracted to a custom hook where all the conditions and calculations will be carried out.

i think that one is ok as is and that logic shouldn't change for other domains 

> `useMutators` hook... pulls code from `/domain/eventEditor`. IMHO it should belong to `/domain/eventEditor` because it providers the event editor related mutators.

yes totally agree. I should have caught that before but didn't. We don't want our different layers to be hard coupled like that.
Created issue #2227 

> We should extract the use of `useContext` to a hook like `useDateContext` or `useTicketContext` to handover the importing of context to it to give us the data we need.

Created issue #2228

#### re: `EditDatetime`, `EditTicket`, && `TicketPriceCalculator`

> These components are rendered for every list item, which creates lots of instances which may not even be used at all. IMHO we should use a global modal (or at least a single modal for an entity list) and pass it the data that we want it to work with.

great idea. that bugged me when I was working on EDTR v1 but just never got around to making that change and eventually forgot about it.
Created issue #2229
