### ISSUE TITLE
Event Espresso not supporting the WPML 

### ISSUE THREAD

**Issue by mangatsaini20** [eventespresso/event-espresso-core#220]
Hello

I have installed the Wordpress WPML plugin for multilingual, the problem is that Event Espresso plugin is not supporing the WPML so how we can translate the content of Events like Name & description of the Events for different languages for multilingual website.

Thanks

**Comment by nerrad** [comment]
Hi there,

We generally don't help with support type questions like these in this project simply because we're limited on the time we can give to these kinds of questions.  In this case, an example of a request that might get some additional attention would be things like:

-   "I'm trying to integrate with the WPML plugin and here's a pull request that adds some filter and action hooks that will help with that."
- "I've built an integration with the WPML plugin for EE and it works okay except with this one problem I'm having with x.  Here's the some example code demonstrating what I've done and the results demonstrating the problem."
