### ISSUE TITLE
Complete Unit Tests for Datetime Mutations

### ISSUE THREAD

**Issue by tn3rb** [eventespresso/event-espresso-core#2239]
- [ ] domain/eventEditor/data/mutations/datetimes/updateTicketCache
- [ ] domain/eventEditor/data/mutations/datetimes/useDatetimeMutator
- [ ] domain/eventEditor/data/mutations/datetimes/useUpdateDatetimeCache

**Comment by manzoorwanijk** [comment]
These components may not be testable in isolation, otherwise I would have done that in previous PRs. The reason for that is these components are entirely used by `/application/services/apollo/mutations` hooks and are dependent upon the cache proxy supplied by Apollo mutation `update` callbacks. This is the reason I created `create`, `update` and `delete` mutations for each entity e.g. in `/domain/eventEditor/data/mutations/datetimes/test`.

**Comment by tn3rb** [comment]
ok great thanks... I wondered if that was the case, but created these issues for the sake of being thorough.

I'm going to add those file names to a list of untestable components so that I (hopefully) don't do this again
