### ISSUE TITLE
Invalid input for State/Province

### ISSUE THREAD

**Issue by hodyhong** [eventespresso/event-espresso-core#224]
Even when the State/Province question is not required, the checkout will not go through without customer put in a state/province. The required message will not be triggered like other required fields. The error modal message of "Invalid input" will come up instead.

### Is this a bug report?

* [/] yes
* [ ] no

### What branch did this occur in?
Master

### What version of WordPress is on the site this issue happened?
4.7.3

### Outline the steps to reproduce
Leave state empty and go through registration.

### Please include any screenshots ar screencasts that can help illustrate the issue (if possible).
[https://ballaratfoto.org/wp-content/uploads/2017/04/no_state.png](url)
[https://ballaratfoto.org/wp-content/uploads/2017/04/filled_except_state.png](url)
[https://ballaratfoto.org/wp-content/uploads/2017/04/invalid.png](url)

**Comment by joshfeck** [comment]
Hi there,

Are you sure you were testing Master at the time you saw the error? The reason I ask is because the issue you report here was fixed in this commit: https://github.com/eventespresso/event-espresso-core/commit/499071c4d72e926269c2f5401ee0409374bbbfd5

which was merged into Master last week.

**Comment by hodyhong** [comment]
Thanks! I didn't actually checkout that commit.
