### ISSUE TITLE
Research and Implement Optimistic UI

### ISSUE THREAD

**Issue by tn3rb** [eventespresso/event-espresso-core#2314]
Identify areas where Optimistic UI can be utilized to change the data presented in components prior to mutations completing. 

Examples:

- when deleting entities they should be removed immediately
- when updating fields, changes could be made immediately to UI components (if possible)

The above of course is potentially easier said than done, which is why the underlying logic in the mutation handlers needs to be examined to see if any of the above (or others) is even possible.

Once all potential opportunities for implementing Optimistic UI have been identified and listed here, additional issues can be created if need be and/or multiple PRs can be made to perform the changes.

**Comment by manzoorwanijk** [comment]
For optimistic UI/responses, we need to:
- Make use of `useQuery` with `fetchPolicy: 'cache-only'` instead of `client.readQuery()`. It properly sets up subscriptions to Apollo cache for optimistic responses.
- Add optimistic responses to all the entity mutators like `useDatetimeMutator`
- Update mutation tests affected by optimistic responses
