### ISSUE TITLE
Ticket editor modal and Price Calculator modal crashes if there is no default price type.

### ISSUE THREAD

**Issue by tn3rb** [eventespresso/event-espresso-core#2341]
plz investigate and fix if solution is obvious

**Comment by manzoorwanijk** [comment]
Such a situation can arise when there are no price types defined or loaded as happened that day when `usePriceTypes` returned nothing because of no rehydration for price types. How do we want to handle it?
- Should we display a warning to create price types?
- Should we disable TPC?

```ts
const usePriceModifier = (price: Price): TpcPriceModifier => {
	const priceType = usePriceTypeForPrice(price.id);
	return {
		...price,
		priceType: priceType.id,
		priceTypeOrder: priceType.order,
	};
};
```
as you can see `priceType` is an important field here, how do we handle it?

**Comment by tn3rb** [comment]
> - Should we display a warning to create price types?
> - Should we disable TPC?

Yes 😄

**Comment by manzoorwanijk** [comment]
We now add a default price if there is none.
