### ISSUE TITLE
Filter FHEE__EEM_Answer__get_attendee_question_answer_value__answer_value returns same ID

### ISSUE THREAD

**Issue by sacerro** [eventespresso/event-espresso-core#241]
> Before submitting your issue, please ensure that what you are reporting is specific to Event Espresso 4.

When submitting an issue, please follow this rough guideline for your report.

### Is this a bug report?

* [ ] yes
* [X] no

### What branch did this occur in?
4.9.45.p

### What version of WordPress is on the site this issue happened?
4.8.1

### Outline the steps to reproduce
I'm trying to fill with user data all atteedee fields. For that, I use 'FHEE__EEM_Answer__get_attendee_question_answer_value__answer_value' filter.

`
class EED_CustomLogin_Module extends EED_Module {

		public static function set_hooks() {
			add_filter( 'AHEE__SPCO__load_reg_steps__reg_steps_to_load', array( 'EED_CustomLogin_Module', 'register_login_reg_step' ) );
			add_filter( 'FHEE__EEM_Answer__get_attendee_question_answer_value__answer_value', array( 'EED_CustomLogin_Module', 'filter_answer_for_attendee' ), 100, 4 );
		}
		public function run($WP) {
		}
		public static function register_login_reg_step( $reg_steps ) {
			array_unshift(
				$reg_steps,
				array(
					'file_path'  => EE_CUSTOMLOGIN_PATH . 'core/steps/',
					'class_name' => 'CustomLoginStep',
					'slug'       => 'custom_login_step',
					'has_hooks'  => false,
				)
			);
			return $reg_steps;
		}
		public static function filter_answer_for_attendee($value, EE_Registration $registration, $question_id, $system_id = null ) {
			var_dump ($question_id);
			echo "<br/>";
			if ( ! $registration->is_primary_registrant() ) {
				return $value;
			}

			if ( empty($value) ) {
				$current_user = wp_get_current_user();
				switch ($question_id) {
					case 14:
						$value = get_user_meta($current_user->ID, '_zip', true);
						break;
					default:
						break;
				}
			}
			return $value;
		}
	}

`
Function allways print ID 14 (var_dump) instead of Question ID. Is this a bug or I need to use other filter for that?

### Please include any screenshots ar screencasts that can help illustrate the issue (if possible).

![image](https://user-images.githubusercontent.com/1681325/30333060-51a86714-97dc-11e7-8380-4f81eaae28bd.png)
![image](https://user-images.githubusercontent.com/1681325/30333072-5dfb0c60-97dc-11e7-851b-28620f2b2681.png)

**Comment by sacerro** [comment]
I wrote var_dump but in the code I put echo $question_id (It "do the same"). We need to "extend" WP_User_Integration addon (we installed and activated). Is there any other filter we can use for that?

**Comment by nerrad** [comment]
I think the issue you may be experiencing is that filter is only for system questions (i.e. fname/lname/email).  It's likely there is another filter that will work better for what you want to do (which I think is to auto-fill non-system question values).  I don't have time to dig into it at the moment but I or someone else will get back to you when we have something helpful.

**Comment by mnelson4** [comment]
you might want to try the filter `FHEE__EE_Question__generate_form_input__return`.

Here is some sample code that uses it:

```
add_filter('FHEE__EE_Question__generate_form_input__return', 'customize_input', 10, 4);
public static function customize_input( EE_Form_Input_Base $input, EE_Registration $reg, EE_Question $question, EE_Answer $answer = null)
    {
        $input->set_default('foobar');
        return $input;
    }
```

**Comment by tn3rb** [comment]
Hi @sacerro 

If you want to manipulate ALL attendee fields, and grab info from existing WP Users to use as attendee data and/or copy incoming attendee data to an existing WP User, then I would recommend using the `FHEE_EventEspresso_core_services_commands_attendee_CreateAttendeeCommandHandler__findExistingAttendee__existing_attendee` hook.

This filter runs for each registration when the Attendee Information checkout step is submitted. The first hook that you were using, as well as the one that Michael suggested both run BEFORE the Attendee Information checkout step is processed, which means your filter callback would be running on initial page load and page refreshes, which would not be good imho.

So the `FHEE_EventEspresso_core_services_commands_attendee_CreateAttendeeCommandHandler__findExistingAttendee__existing_attendee` hook that I'm suggesting runs immediately BEFORE we create an EE_Attendee object for each registration from the reg form. This EE_Attendee object could represent an existing attendee or it could be a brand new record created. The filter itself runs at the end of  the `EventEspresso\core\services\commands\attendee\CreateAttendeeCommandHandler::findExistingAttendee()` method, and would return an EE_Attendee object for an existing attendee that has a first name, last name, and email address that ALL match those of from the incoming attendee data from the reg form.

This phook will be great for your purposes because it provides you with:

 * an EE_Attendede object for an existing attendee (if one exists - will be null otherwise)
 * the EE_Registration object created for the attendee for the current event/ticket
 * ALL of the attendee data for the registration submitted via the registration form

With the above data, you can do any  of the following:

 * search for existing WP Users  with matching data and edit their properties
 * create new WP Users from the incoming attendee reg form data
 * edit existing EE_Attendee objects/records using any of the above data
  * edit the incoming attendee reg form data and let the system create a new Attendee object/record
 * lots more

hope that helps

**Comment by sacerro** [comment]
FHEE__EE_Question__generate_form_input__return filter is the best option.
Thanks for your help!
