### ISSUE TITLE
Move Filtering and Pagination Logic into EntityList Component

### ISSUE THREAD

**Issue by nicolad** [eventespresso/event-espresso-core#2424]
`assets\src\domain\eventEditor\ui\datetimes\datesList\List.tsx`  needs to be refactored to use `assets\src\application\ui\layout\entityList\EntityList`

**Comment by tn3rb** [comment]
In EDTR v1 the component tree looked something like this:

```
├── EditorDateEntitiesList
|	├── DatesListFilterBar
|	├── EntityPagination
|	├── EntityList
|	|	├── EditorDateEntitiesGridView
|	|	├── EditorDateEntitiesListView
|	├── AddNewDateEntityButton
|	├── EditAllTicketAssignmentsButton
```

where all of the filtering and pagination control was handled by `EditorDateEntitiesList`

What _might_ potentially work better is having the pagination and filtering all handled by the `EntityList` component instead since we now have the filter bar and pagination components in subfolders of `assets\src\application\ui\layout\entityList`:

```
├── entityList
|	├── EntityList
|	├── filterBar
|	|	├── Collapsible
|	|	├── EntityListFilterBar
|	|	├── useEntityListFilterState
|	├── pagination
|	|	├── EntityPagination
|	|	├── useEntityPagination
```

So `EditorDateEntitiesList` would have to pass the following to `EntityList`:

- the raw list of all datetimes returned by Apollo
- its two view components `EditorDateEntitiesGridView` & `EditorDateEntitiesListView`
- its filter state manager `useDatesListFilterState` for managing current filter settings (or just the returned filter state object with the values)
- plus its actual filter logic `useFilteredDatesList` for filtering the array of datetimes

`EntityList` would then:

- pass the filter state object to the actual filters so they can be initialized with the current values
- run the full array of dates through the above filters 
- retrieve and pass the filter state object from `useEntityListFilterState` to `EntityListFilterBar` so it can be initialized with current values 
- run the filtered list of dates through the second set of filters to obtain the final list of dates for display
- then finally render all of the components using the data from above:
    - `EntityListFilterBar` & `DatesListFilterBar` with corresponding filter state objects
    - `EntityPagination` with its corresponding filter state object
    - the Grid or List view component for the dates list depending on the current value for the entity list filter bar "view" setting

The above will be a bit tricky because everything happening inside the `EntityList` component will have to be abstracted and work for both the dates and tickets lists, as well as any other entity lists we build in the future. **IF** it can be done, then it saves having to essentially duplicate the same logic for every single entity list.

**Comment by tn3rb** [comment]
I just noticed you had written this in your original post:

>  and should likely be renamed/moved into a folder to indicate it is for grid/card view

that's not correct. The DatesList will be the parent component for both the card view AND the list view and will pass both of those along to the `EntityList` for displaying according to the current state of the "view" filter
