### ISSUE TITLE
One $question_id passed in twice while another doesn't get passed in at all

### ISSUE THREAD

**Issue by weis0292** [eventespresso/event-espresso-core#245]
### Is this a bug report?

* [ ] yes
* [ ] no
* [x] I don't think so

### What branch did this occur in?
4.9.45.p

### What version of WordPress is on the site this issue happened?
4.8.1

### If you were directed to create an issue here by the EE support team, what is the link to your original EE support forum thread?
https://eventespresso.com/topic/autofill-filter-not-receiving-correct-values/#post-251478

### Outline the steps to reproduce
I wrote a filter to handle FHEE__EEM_Answer__get_attendee_question_answer_value__answer_value.  One of the parameters passed in is $question_id.  I have six questions, four of which are the default questions.  In the admin console, the other two are 11 and 13, but for some reason, they both come through as question ID 11.  My code then fills in both questions with the answer for question 11.  Everything in the database appears to be correct, I just can't get 13 to come through the method.  11 gets passed in twice.

### Please include any screenshots or screencasts that can help illustrate the issue (if possible).
```
function autofill_custom_question_answers($value, EE_Registration $registration, $question_id, $system_id = null) {
	global $current_user;
	if ((!$current_user instanceof WP_USER) || !$registration->is_primary_registrant()) {
		return $value;
	}

	switch ($question_id) {
		case 11:
			$value = esc_attr(get_the_author_meta('my_user_meta_field', $current_user->ID));
			break;
	}

	return $value;
}
```

### Please include any links to the page(s) demonstrating this issue (if possible).
The plugin is currently deactivated because it doesn't work.

**Comment by tn3rb** [comment]
That filter only works for questions that correspond to EE_Attendee properties. Please see the `EEM_Attendee::$_system_question_to_attendee_field_name` property for a mapping of system question IDs and the attendee properties they correspond to.

Since it is obvious that you need to reference questions that do not correspond to attendee properties, you will need to use another hook. Here is another question from only a few days ago pertaining to the same hook: https://github.com/eventespresso/event-espresso-core/issues/241

There are a couple of suggestions towards the end of the post.  I would recommend using the `FHEE_EventEspresso_core_services_commands_attendee_CreateAttendeeCommandHandler__findExistingAttendee__existing_attendee` hook if you only need to capture data **after** the attendee information checkout step has been submitted. If you want to access the question input both before that form is displayed as well as after it has been submitted, then try the `FHEE__EE_Question__generate_form_input__return` filter.

**Comment by weis0292** [comment]
Awesome.  So it looks like `FHEE__EE_Question__generate_form_input__return` does what I need.  You mention this filter is called both before the form is displayed as well as after it has been submitted.  Is there a way to tell the difference?  If the user changes their answer, I don't want to repopulate with the default value.  I only want to set the default before the form is displayed.

**Comment by tn3rb** [comment]
>  it looks like FHEE__EE_Question__generate_form_input__return does what I need.

they both will do what you need, but just in different ways. You can access ALL of the Questions that were asked of a registrant because its EE_Answer objects are related, which are in turn related to their corresponding EE_Question. for example:

```
$answers = $registration->answers();
foreach ($answers as $answer) {
    $answer->question(); // to get full question object 
    $answer->question_ID(); // to just get question ID
}
```

> You mention this filter is called both before the form is displayed as well as after it has been submitted. Is there a way to tell the difference? If the user changes their answer, I don't want to repopulate with the default value. I only want to set the default before the form is displayed.

this is why I suggest using the other filter in the CreateAttendeeCommandHandler class.

As for detecting when that filter is being run, you would have to detect something externally, since I don't believe there is anything within the parameters passed to the filter that you could use. 

So again, if you only want to run your logic AFTER the form is submitted, I would use the other filter.

**Comment by tn3rb** [comment]
bah sorry... scrap what I wrote above... end of the day for me here and I read your response incorrectly....

> I only want to set the default before the form is displayed.

then try the `FHEE__EE_SPCO_Reg_Step_Attendee_Information___generate_question_input__input_constructor_args` filter which is also in that same emthod as the other EE_Question filter. This one however filters the input options used to generate each form input. The default value for the input is specified by the value set in `$input_constructor_args['default']`. So whatever you set there will be used as the default input value and NOT affect what the user enters if the form is refreshed, or has to be resubmitted due to validation errors.

**Comment by weis0292** [comment]
Thanks for the followup.  I wasn't sure we were on the same page with the first response.  Your second response cured what ailed me.  I got the code up and running.  Thanks for the help.
