### ISSUE TITLE
AHEE__EE_SPCO_Reg_Step_Finalize_Registration__process_reg_step__completed not always being fired

### ISSUE THREAD

**Issue by gazchap** [eventespresso/event-espresso-core#250]
### Is this a bug report?

* [X] yes
* [ ] no

### What branch did this occur in?

EE 4.9.45.p

### What version of WordPress is on the site this issue happened?

4.8.2 (but was probably 4.8/4.8.1 when the issue happened)

### If you were directed to create an issue here by the EE support team, what is the link to your original EE support forum thread?

https://eventespresso.com/topic/hook-on-successful-registration-not-working-every-time/

### Outline the steps to reproduce

Not sure. The hook should (as I understand it) fire every time a registration is completed, regardless of whether it was a free event or a paid event.

There is no clear pattern to the hook not firing - sometimes it just doesn't.

### Please include any screenshots ar screencasts that can help illustrate the issue (if possible).

Not possible.

### Please include any links to the page(s) demonstrating this issue (if possible).

Not possible.

### Code is below, although I've edited it to remove some of the things the code performs. The key part is that the log file that should be created at the start of the function isn't being created, which means that the hook is not being fired at all.

	class EventEspresso4 {

		function __construct() {
			add_action( 'AHEE__EE_SPCO_Reg_Step_Finalize_Registration__process_reg_step__completed', array( $this, 'after_registration' ), 10, 2 );
		}

		function after_registration( $checkout, $txn_update_params ) {
			$fp = fopen( dirname( __FILE__ ) . "/logs/ee4-checkout-" . date('Y-m-d-H-i-s') . ".log", "ab" );
			if ( $fp ) {
				fputs( $fp, "[" . date('H:i:s') . "] Event registration received dumping checkout object.\r\n" );
				fputs( $fp, print_r( $checkout, true ) . "\r\n" );
			}
		}
	}

	new EventEspresso4();

No errors are logged either so it's not trying to create the file and failing.

So, my question is - are there any scenarios where that hook will not fire upon completion of a registration?

Events on the site in particular are either free, or can be paid for via PayPal standard. Does PayPal Standard sometimes not trigger the completion hooks???

**Comment by joshfeck** [comment]
Hi there,

I'm not certain that this would be related to the hook not firing, but using PayPal Standard can be very problematic because there can be delays with the IPN or even the no IPN. We recommend using the PayPal Express gateway in its place. You can use your same PayPal account with PayPal Express. Here's a link to a guide that shows how to get your PayPal API credentials for the PayPal Express gateway:
[https://ee-screenshots.s3.amazonaws.com/2015/09/pay-by-credit-card.png](
https://eventespresso.com/wiki/paypal-express-payment-gateway/#locate)

**Comment by mnelson4** [comment]
+1 to what @joshfeck said. @gazchap can you twitch to PayPal Express? We've basically deprecated PayPal Standard because it's so inconsistent (I'm not sure if you've noticed, but for new users of Event Espresso, PayPal Standard isn't even an option anymore; it's only there for users who used it previously)

**Comment by gazchap** [comment]
Thanks guys, I'm talking with the client to get an Express upgrade sorted and will advise if that cures the problem.

**Comment by tn3rb** [comment]
any updates  on whether using PayPal Express has helped? If not, I'm going to close this issue.

**Comment by gazchap** [comment]
Sorry, yes - changing to PayPal Express appears to have resolved it - thanks :)
