### ISSUE TITLE
Event edit page incorrectly says automatic status change is "not permanent"

### ISSUE THREAD

**Issue by dylanmccall** [eventespresso/event-espresso-core#251]
When I edit an event that is marked as "Sold out" but has tickets available, the following message appears:

 > Please note that the Event Status has automatically been changed to Published because more spaces have become available for this event, most likely due to abandoned transactions freeing up reserved tickets. However, this change is not permanent until you update the event. If you wish, you can change the status back to something else before updating.

However, it appears the status change has already been saved. From a cursory glance at the surrounding source code, this is easy to explain. In [Events_Admin_Page.core.php]((https://github.com/eventespresso/event-espresso-core/blob/master/admin_pages/events/Events_Admin_Page.core.php#L696)), *verify_event_edit* calls `$event->is_sold_out(true)`. That function (defined in [EE_Event.class.php](https://github.com/eventespresso/event-espresso-core/blob/master/core/db_classes/EE_Event.class.php#L876)) calls `EE_Event::perform_sold_out_status_check()`, which, after determining an event's status, *saves* the result.

It would solve this problem if you either change this message to reflect the expected behaviour, or change *perform_sold_out_status_check* to remove the side-effect.

**Comment by mnelson4** [comment]
Oh yeah, somehow we didn't notice that! We'll look into it... and pull requests welcome too, eh!

**Comment by tn3rb** [comment]
I think that notice needs to be changed since we want the events to go back on sale if tickets are available and NOT have to rely on the event admin to manually update the event, which could easily result in missed ticket sales opportunities.

What might be good is to have a filter in `EE_Event::perform_sold_out_status_check()` for controlling whether or not that happens automatically or not as it's possible that some event admins will want to control  whether event tickets go immediately back   on sale after  becoming available.

**Comment by sethshoultes** [comment]
@tn3rb how long will it take to add that filter?
