### ISSUE TITLE
Add Status Labels to Date and Ticket Sidebars

### ISSUE THREAD

**Issue by tn3rb** [eventespresso/event-espresso-core#2625]
- use `getStatusTextLabel()` functions in `\domain\shared\entities\{entity-type}\helpers\`

- add to `footerText` for date display calendar components in sidebar

**Comment by nicolad** [comment]
@tn3rb in one of the previous PRs `switchTenseForDate` has been added which doesn't align perfectly with `getStatusTextLabel`, because, for example, we need to have discrimination based on `footerPast` and `footerFuture`.

![image](https://user-images.githubusercontent.com/1477453/78545105-e3c82080-7803-11ea-8285-2d4a61dbf258.png)
