### ISSUE TITLE
Hook on registration cancelled!!

### ISSUE THREAD

**Issue by 5Hemant** [eventespresso/event-espresso-core#265]
> Before submitting your issue, please ensure that what you are reporting is specific to Event Espresso 4.

When submitting an issue, please follow this rough guideline for your report.

### Is this a bug report?

* [ ] yes
* [x] no
Hello,
I have written some custom $wpdb queries on "AHEE__Single_Page_Checkout__after_attendee_information__process_reg_step" hook. This is fired once we go to the second registration page. But the problem is, if the payment or registration is cancelled, the queries goes through. 
I want my queries to run only when the payment is successfully completed. On this note, i have used another hook that runs when the thankyou page is displayed. i.e. "AHEE__EE_SPCO_Reg_Step_Finalize_Registration__process_reg_step__completed", But this has another problem. My queries are for tickets table that increases the sold numbers for the similar events. While i use this hook for those custom queries this will increase the ticket number in the present event and for the other that i want through custom query. So i have decided not to use this hook. 

I am looking forward to a hook that runs on registration cancelled so that i can revert my custom query there.  Are there any other ideology which i can do to achieve this??

Regards

**Comment by mnelson4** [comment]
It sounds like @5Hemant doesn't just want when the user explicitly cancels the registration (eg when they're paying on an offsite gateway's site and press "cancel" and return to EE and cancel their registration) but also when the transaction is cancelled automatically because they took too long. What hook do you think would be the most correct @tn3rb ?

**Comment by 5Hemant** [comment]
Yes @mnelson4 That is what i want. If the user cancels the registration or gets back to the event listing page or closes the browser.

**Comment by tn3rb** [comment]
There's no single hook point that can be used that will cover all cases, so you will have to accommodate all of the various ways that this can happen:

 * if a user clicks the "cancel registration" link during checkout, then they are taken to the "/registration-cancelled/" page which fires the `[ESPRESSO_CANCELLED]` shortcode. The code for that can be found in the `\EventEspresso\core\domain\entities\shortcodes\EspressoCancelled` class which has a few hook points that you could use.  A good one might be: `AHEE__EES_Espresso_Cancelled__process_shortcode__transaction`. This is the same place that users should be taken to if they click "cancel" while at an off-site payment gateway.
 * if a user takes too long to register and their session expires, then things won't get cleaned up until `EE_Cron_Tasks::process_expired_transactions()` runs which is done via a WP_Cron that is set to run just after the session expires. There are a few hook points within that method as well, but you would most likely be looking at `AHEE__EE_Cron_Tasks__process_expired_transactions__incomplete_transaction` or `AHEE__EE_Cron_Tasks__process_expired_transactions__abandoned_transaction`

Now that said, if you only want your queries to run "when the payment is successfully completed", then you could use the `AHEE__EE_Payment_Processor__update_txn_based_on_payment__successful`  hook point in `EE_Payment_Processor::update_txn_based_on_payment()` that  fires whenever a payment is successful.  This can be triggered at various times that may not be applicable to your use case, so you would need to first determine whether or not to run your queries or not when it is triggered (although this is likely true for any hook point you use).

Another hook point that you might want to try is `AHEE__Single_Page_Checkout__after_payment_options__process_reg_step` located in `EED_Single_Page_Checkout::_process_form_action()` which fires after the payment options reg step form  is processed. This would be great if you are using an on-site payment method, because it would fire after the payment was made, but would not be so great for off-site payment methods because it would fire before they are redirected to the payment gateway. So this wouldn't work much better  than the `AHEE__EE_SPCO_Reg_Step_Finalize_Registration__process_reg_step__completed` hook point you are using now.

**Comment by 5Hemant** [comment]
Well these are certainly a lot of options  and Thank you @tn3rb @mnelson4 both for helping me out.
Im going to check all these hooks and will let you know on this.

Regards

**Comment by tn3rb** [comment]
going to assume that no news is good news since you haven't responded since November 2017.
