### ISSUE TITLE
Question: How to record how many tickets (including ticket types) a unique user has purchased per a specific event?

### ISSUE THREAD

**Issue by steven-hadley-snugsite** [eventespresso/event-espresso-core#267]
I was told to post here from support staff on the thread https://eventespresso.com/topic/recording-the-number-of-tickets-purchased-by-a-user-per-event-to-database/

I am attempting to record how many tickets a unique user has purchased per a specific event so that I can limit how many discounted tickets a user can purchase. Currently EE’s Ticket Limit feature works on a per transaction basis, allowing users to return to the page after ordering and simply order more discounted tickets. So far to record the transactions I've got

```
function record_purchases(){
    $user_id = get_current_user_id();
    $checkout = EE_Registry::instance()->SSN->checkout();
    if ( $checkout instanceof EE_Checkout ) {
        $transaction = $checkout->transaction;
        if ( $transaction instanceof EE_Transaction ) {
			$primary_registration = $transaction->primary_registration();
			if ( $primary_registration instanceof EE_Registration ) {
				$event = $primary_registration->event();
				$tickets_purchased = $primary_registration->group_size();
				echo "User is ".$user_id."<br>";
				echo "Tickets purchased = ".$tickets_purchased;
			}
        }
    }
}
```

However that will only record the number of tickets purchased for that specific event (not the qty of each specific ticket type). It also won't work for Multi Event Registration. How can I get the data for how many tickets (including ticket types) a unique user has purchased per a specific event?

**Comment by tn3rb** [comment]
The ticket ID  is recorded on each registration, so instead of retrieving the primary registrant, you could loop through all of the registrations on the transaction and retrieve the ticket from each registrant.
Also, plz keep in mind although one registration is created for each registrant, and there is a 1:1 relationship between tickets and registrations, each registration is also related to an `EE_Attendee` object, which can  also be retrieved from the registration.

So if you have people that are performing multiple  transactions in order to obtain multiple discounts, then assuming they are using the same first name, last name,  and email address, their registrations would ALL have the same related attendee. so you could also use that to further organize your data:

```php
// ticket quantities ordered by event ID and then ticket ID
$ticket_quantities = array();
if ($transaction instanceof EE_Transaction) {
    $registrations = $transaction->registrations();
    foreach ($registrations as $registration) {
        if (! $registration instanceof EE_Registration) {
            continue;
        }
        $event = $registration->event();
        if (! $event instanceof EE_Event) {
            continue;
        }
        $attendee = $registration->attendee();
        if (! $attendee instanceof EE_Attendee) {
            continue;
        }
        $ticket = $registration->ticket();
        if (! $ticket instanceof EE_Ticket) {
            continue;
        }
        if (! isset($ticket_quantities[ $event->ID() ])) {
            $ticket_quantities[ $event->ID() ] = array();
        }
        if (! isset($ticket_quantities[ $event->ID() ][ $attendee->ID() ])) {
            $ticket_quantities[ $event->ID() ][ $attendee->ID() ] = array();
        }
        if (! isset($ticket_quantities[ $event->ID() ][ $attendee->ID() ][ $ticket->ID() ])) {
            $ticket_quantities[ $event->ID() ][ $attendee->ID() ][ $ticket->ID() ] = 0;
        }
        $ticket_quantities[ $event->ID() ][ $attendee->ID() ][ $ticket->ID() ]++;
    }
}
```

that would give you an array of ticket objects organized by event ID,  attendee ID,  and ticket ID, although you could likely perform  your logic right within that loop, or call other functions to do it, instead of creating arrays of data.

**Comment by tn3rb** [comment]
going to assume that no news is good news since you haven't responded since December 2017.
