### ISSUE TITLE
Refactor styles

### ISSUE THREAD

**Issue by nicolad** [eventespresso/event-espresso-core#2725]
Currently, we have 2 approaches when applying border to a button or icon button in hover/focust state:
1. using border
2. using box-shadow

I think we need to make it uniform, such that it will use only `box-shadow`, the reason being that it won't affect the element inner sizing.

**Comment by tn3rb** [comment]
an alternative to `box-shadow` with relatively the same end result is to use `outline` (assuming you only want to add a solid line around the element).

As well, `box-shadow` has some additional considerations: https://stackoverflow.com/a/52616313

IIRC i had only added styles for `box-shadow` as a focus/hover indicator to override AntD styles

**Comment by nicolad** [comment]
That is a very interesting consideration, I had checked before that chakra and assumed it's perfectly accessible since it is focused on `a11y` in the first place:

![image](https://user-images.githubusercontent.com/1477453/80011363-73442380-84d4-11ea-91a5-d8d625c3ddb1.png)

**Comment by nicolad** [comment]
TODO:
- Create `ee-btn-base` as an overlap for styles used in button as well icon button, such that icon button does not inherits all the button's styles. 
- In `IconButton` replace `ee-button` with `ee-btn-base`
- In `src/application/ui/input/Button/style.scss` remove `.ee-event-editor` namespace and refactor to take advantage of `ee-btn-base`, such that we can target `.ee-btn-base.ee-button`

**Comment by nicolad** [comment]
Fun fact: checked what is WP editor, they use both border and box-shadow:

![image](https://user-images.githubusercontent.com/1477453/80140800-2c782b80-85b1-11ea-93c4-a79c9f44c40d.png)

**Comment by nicolad** [comment]
and in another case box-shadow and outline:

![image](https://user-images.githubusercontent.com/1477453/80140887-4d408100-85b1-11ea-997b-c69de9c6d4e8.png)

**Comment by tn3rb** [comment]
Let's use the following as a start and then tweak from there

### Input, and Select

 - Focus:

```css
	border-color: var(--ee-color-primary);
	box-shadow: 0 0 0 1px var(--ee-color-primary);
```

 - Hover

```css
	border-color: var(--ee-color-primary-low-contrast);
	color: var(--ee-color-primary-high-contrast);
	box-shadow: 0 0 0 1px var(--ee-color-primary-low-contrast);
```


### Button

 - Focus

```css
	border-color: var(--ee-color-primary);
	box-shadow: 0 0 0 1px var(--ee-color-primary);
```

 - Hover

```css
	border-color: var(--ee-color-primary-low-contrast);
	color: var(--ee-color-primary-high-contrast);
	box-shadow: 0 0 0 1px var(--ee-color-primary-low-contrast);
```

 - path (ie: the svg icons)

```css
	fill: currentColor;
```

and then also add that hack for Windows High Contrast Themes:

```css
/* Visible in Windows high-contrast themes */
  outline-color: transparent;
  outline-width: 2px;
  outline-style: solid;
```

**Comment by nicolad** [comment]
@tn3rb I've renamed this issue to act as an umbrella for other changes I am applying, also it is as a master issue, story kinda

**Comment by tn3rb** [comment]
Some observations from latest master:

![ScreenShot_20200430173015](https://user-images.githubusercontent.com/1751030/80771463-6e9cf200-8b08-11ea-99a2-fd042e302b6d.png)

many of the icon buttons appear to have one or more of the following issues:

- icons are not the correct size
- icons are not centered

The following styles:

```css
.ee-btn-base.ee-icon-button svg {
  display: inline-block;
  flex: 0 0 auto;
}
```

is great, but is not working because the buttons need `display:flex` for the above flex settings to work. Although adding that fixes the centering issue, the padding is still off, so might be good to set that to be the same all around. As well, the height and width values don't need to use `calc()`.

So icon buttons should all have:

```css
display: flex;
height: var(--ee-icon-button-size);
padding: var(--ee-padding-micro);
width: var(--ee-icon-button-size);
```

For the legend icon, part of the centering issue also appears to be because the svg has the following class and styles applied to it.

```
.ee-svg {
  display: inline-flex;
  margin: 0 var(--ee-margin-micro);
}
```

I think that was added to fix spacing issues for the "timezone info" icon button, but that's messing up the legend button, so let's remove that. We can fix the "timezone info" icon button separately.


For the size issue, you can see from the following svg html:

```html
// table view icon
<svg aria-hidden="true" class="css-thzv76 dashicon dashicons-table-view espresso-icon" focusable="false" height="20" role="img" viewBox="0 0 20 20" width="20" xmlns="http://www.w3.org/2000/svg">...</svg>

// card view icon
<svg viewBox="64 64 896 896" focusable="false" class="css-thzv76" data-icon="appstore" width="1em" height="1em" fill="currentColor" aria-hidden="true">...</svg>
```

that they are using different units for the height and width attributes (20 && 1em). 1rem typically works out to 16px, so we either need to change ALL SVGs to be:

```html
 height="20"  width="20"
```

or

```html
 height="1.25rem"  width="1.25rem"
```

Lastly, you mentioned something about maybe needing the active style to be more prominent... 
what do you think about giving active selections a blue background with white text and svg fills?

As well, to make the focus style more pronounced what do you think about changing the box-shadow to something like:

```css
box-shadow: 0 0 3px 3px var(--ee-color-primary-low-contrast);
```

???

try it out and lemme know what you think

**Comment by nicolad** [comment]
Applied `display: inline-flex`, instead `display: inline`, here is why:

![Peek 2020-05-01 11-49](https://user-images.githubusercontent.com/1477453/80794278-321dd480-8ba2-11ea-98c9-3085564f83e9.gif)
