### ISSUE TITLE
Hidden notice elements creating theme display issue on taxonomy archive

### ISSUE THREAD

**Issue by stevengliebe** [eventespresso/event-espresso-core#274]
Bug report. WordPress 4.9.4, EE 4.9.57.p.

EE is adding hidden notice elements to a custom taxonomy archive where EE is not used. This is creating problems with the [Saved](https://churchthemes.com/themes/saved/) theme. Here's code showing where the EE elements are added.

```html
<main id="saved-content" class="saved-bg-contrast">

	<div id="saved-content-inner" class="saved-centered-large saved-entry-content">

		<h1 id="saved-main-title">Heading</h1>

		<div id="saved-loop-multiple" class="saved-clearfix saved-loop-entries saved-loop-four-columns">

			<div id="espresso-notices"></div>
			<div id="espresso-ajax-loading" style="display:none;"><span class="ee-spinner ee-spin"></span><span style="display:none;">loading...</span></div>
			<div id="espresso-ajax-notices">
			...
			</div>

		    <article id="post-5010" class="saved-sermon-short saved-entry-short saved-entry-has-image saved-entry-has-excerpt post-5010 ctc_sermon type-ctc_sermon status-publish has-post-thumbnail hentry ctc_sermon_topic-power-of-words ctc_sermon_series-just-sayin ctc_sermon_speaker-brad-mullins ctfw-has-image">
		    ...
```

You can see this on a theme users' website at https://springhill.cc/sermon-series/just-sayin/ (asked them to leave EE active). The first two posts are without the expected margin separating them.

![screen shot 2018-02-13 at 11 31 35 am](https://user-images.githubusercontent.com/3372396/36164266-7a8e2274-10b1-11e8-89c4-91fa7d81ec10.png)

Remove the EE notice elements from ```#saved-loop-multiple``` (or move them outside of it) with your browser and things straighten out.

![notices](https://user-images.githubusercontent.com/3372396/36164407-e114def2-10b1-11e8-928a-d2aff2fe7a4d.png)

![screen shot 2018-02-13 at 11 33 00 am](https://user-images.githubusercontent.com/3372396/36164343-aec470e8-10b1-11e8-8c93-07b87b329721.png)

Can these elements not be added when not needed? I think that would be the simplest solution. I am assuming they have no purpose on a taxonomy archive like this. Thank you for looking.

**Comment by nerrad** [comment]
As far as I can tell looking at our code, the one place that is loading our notices template is found in `EE_Front_Controller::display_errors` which is hooked in on `loop_start`.  However that is protected behind some conditionals:

```php
public function display_errors()
    {
        static $shown_already = false;
        do_action('AHEE__EE_Front_Controller__display_errors__begin');
        if (
            ! $shown_already
            && apply_filters('FHEE__EE_Front_Controller__display_errors', true)
            && is_main_query()
            && ! is_feed()
            && in_the_loop()
            && $this->Request_Handler->is_espresso_page()
        ) {
            echo EE_Error::get_notices();
            $shown_already = true;
            EEH_Template::display_template(EE_TEMPLATES . 'espresso-ajax-notices.template.php');
        }
        do_action('AHEE__EE_Front_Controller__display_errors__end');
    }
```

So the one thing I can see that _might_ be happening, is somehow `$this->Request_Handler->is_espresso-page()` is returning true for this view when it _should_ be returning false.  If you're able to add some debug code to this site to see what is being returned for that method that would help.  

Also, if you're able to get what the keys are found in `$wp->query_vars` at that point, that will also help.

Finally, does the theme add any custom post types?  Or is there another plugin on this site that adds custom post types?  If so, what is the registered slug(s) for those cpts?

**Comment by nerrad** [comment]
In the meantime, a way you can workaround this is using the filter in the above conditional. Anytime before the `loop_start` hook fires, have the following execute:

```
add_filter('FHEE__EE_Front_Controller__display_errors', '__return_false');
```

You can also just conditionally set that filter only on the routes you know there will be no EE activity.  But again, by design/default we've attempted to ensure the notice skeleton is only set on routes involving EE.

**Comment by tn3rb** [comment]
This can also be fixed by using better targeting with your css selectors.

Instead of 

```css
.saved-loop-four-columns .saved-entry-short:not(:nth-child(4n)) {
    margin-right: 1.875em;
}
```

which is saying: apply a right margin to all `.saved-entry-short` elements within the `.saved-loop-four-columns` container... as long as they are NOT the fourth child in that container... but it doesn't specify at all what type of child element that applies to, therefore anything else that appears in that container will throw off your styling.

What you want to do is not apply that margin ONLY for the fourth  `.saved-entry-short` element

So try:

```css
.saved-loop-four-columns .saved-entry-short:not(:nth-of-type(4)) {
    margin-right: 1.875em;
}
```

which is now saying: apply a right margin to all `.saved-entry-short` elements within the `.saved-loop-four-columns` container... as long as they are NOT the fourth child OF THE SAME TYPE in that container...

**Comment by stevengliebe** [comment]
Thank you both for the workarounds. I'm using ```is_tax()``` to return false for ```FHEE__EE_Front_Controller__display_errors``` as a workaround for now.

If I have other reports of this then I'll spend some time debugging to see if there's something my plugin or theme is doing to cause EE to output those elements on a non-EE page.
