### ISSUE TITLE
Evaluate Event Attendees Gutenberg Block and Document Requirements for JS Models Replacement

### ISSUE THREAD

**Issue by tn3rb** [eventespresso/event-espresso-core#2744]
see:

- `assets/ZZZ/blocks/event-attendees` for block declaration 
- `assets/ZZZ/components/event-attendees` for frontend component

Both of the above relied on the previous JS models for retrieving data from the server and populating the block with the necessary data as well as maintaining data integrity by converting REST API data into JS classes that mirrored teh EE PHP model entities.

We need to develop a plan for how we are going to replace the previous JS models, get data from the server into React for GB blocks, and then use said data within GB. We can't utilize the standard WP functionality because we depend too much on custom tables with a far more complex data schema, so we need some other way to send and receive data. In the previous JS models, Darren tried to emulate what WP core did as much as possible and therefore did everything via the REST API. This ended up being pretty terrible because of the number of requests required to retrieve all of the necessary data, so ideally we want something that can do everything in a single request. He of course also tried to recreate the PHP model objects that Michael and I developed but using JS classes which were bloated, unreliable, and difficult to use.

So far I've only had the following idea for doing this :

- utilize the CommandBus server side and create Commands for each of our blocks and then just use the standard [JS Fetch API](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API) to retrieve the necessary data to populate the blocks. A request might look something like:

```
https://www.example.com/eegbapi?cmd=event-attendees-block&eventId=1&9datetimeId=2&ticketId=3
```

then we:

- detect all requests sent to `/eegbapi/` and parse the request for the command: `cmd=event-attendees-list`

- if that translates to a known block (in this case the EventAttendeesList) then we generate a Command, otherwise return an error

- the Command manually populates itself using the data from the `$_REQUEST` (and handles sanitization)

- the Command is passed to the CommandBus which can automatically check permissions, etc before passing the Command to its handler

- the CommandHandler uses the request properties in the Command to build a JSON response which is returned to the client

- client side we use TypeScript (if possible) to define our entities which can then be simple JSON

the benefits to this approach are:

- it's relatively simple and only requires a single request to retrieve all of the data necessary

- most of the mechanisms are already in place

- the CommandBus is a well established design pattern and works great with DDD (Domain Driven Design) because it helps to isolate domain logic in specific use cases represented by the commands.

- if we can mirror the existing Apollo GQL Types we are using for the EDTR then we can possibly use some of our existing application layer components when building out the UIs (at least for the public frontend, not the GB editor).

For the Gutenberg Editor we might have no choice but to use the REST API and just send separate requests for populating all of the dropdowns and options required for working with GB block.

#### next steps

- go through `assets/ZZZ/blocks/event-attendees` and `assets/ZZZ/components/event-attendees` and document what code can be salvaged and what needs to be replaced.

- plan/design data schema for use in GB blocks (can hopefully mirror our Apollo GQL Types)

- plan/design logic framework for converting incoming JSON into entities

- plan/design logic framework for managing relations between entities

- plan/design logic framework for managing data persistence

- create additional issues/PRs for further defining work to be done

**Comment by manzoorwanijk** [comment]
### Challenges

-   Data requirements of the blocks which can be dynamic (based on selected options)
-   Data persistance
-   UI components to use, which involves some smarter components. For example WP `SelectControl` doesn't have a loading indicator.
-   Application layer dependency
-   Bundle size, which should not be too high

### Potential Solutions

#### For Data requirements

-   GraphQL

    GraphQL seems to be the best option for complex data needs of the blocks.

    -   Pros

        -   Faster data retrieval
        -   Less preparation needed (considering our EDTR already using it)

    -   Cons

        -   May be an overkill for simple blocks
        -   May have to dump the code for existig blocks

-   REST API

    -   Pros

        -   Blends more into GB patterns
        -   Less bundle size cost

    -   Cons

        -   Slow data retrieval
        -   May have to create REST endpoints to use for data
        -   Will have to recreate `fetch` handling if we choose not to go with GB `data` package

#### For Data persistance

We should avoid saving JSX in `save` function of blocks to avoid blocks getting depricated. We can make use of block attributes to render them on front-end.

#### For UI Components

-   WordPress components

    We should stick to WP components as much as possible to reduce the bundle size and to decouple blocks from rest of the design layers. If a component doesn't satify our needs, we should think of an alternate way. For example to use WP `SelectControl` with loading inficator, we can create that indicator just beside the control.

#### App layer dependency

Blocks should be less dependent upon application layer as much as possible. Although we can pull TS types (even from other domains) as much as we want because they are only there till compilation.

#### Bundle size

Bundle size is of utmost concern for blocks because we don't have an option to lazy load them.

## For Front End (Public facing)

Here we need to make a decision whether we want to render the blocks using PHP code (via `render_callback`) or React.

-   PHP

    Blocks are already functional this way I think and may not require much changes except to use QGL GUIDs instead of DB IDs (if we go with GQL).

-   React

    If we want to use React, then we have no restriction upon how we want to use it. We can fully use our application layer and create a separate domain for that.

**Notes:**

-   Some webpack magic will be needed to get the things working
-   We will have to load `React` and `ReactDOM` externally (for EDTR) to avoid conflicts in GB.
-   Existing blocks are too toghtly coupled with JS models and not much code will be reusable.

**Comment by manzoorwanijk** [comment]
Done via #2767
