### ISSUE TITLE
I want the qty increment and decrement button on registration checkout page

### ISSUE THREAD

**Issue by sumant1412** [eventespresso/event-espresso-core#275]
> Before submitting your issue, please ensure that what you are reporting is specific to Event Espresso 4.

When submitting an issue, please follow this rough guideline for your report.

### Is this a bug report?

* [x] no

### What branch did this occur in?

Registration checkout page

### Please include any links to the page(s) demonstrating this issue (if possible).

I want to display the Qty increment decrement button on the checkout page as it is on cart page, and when increasing the number of qty attendee form should also be increased and decreased  as well.

**Comment by sumant1412** [comment]
http://www.race2gather.com/events/test-event-61/

**Comment by tn3rb** [comment]
that's a lot of work... how far have you gotten?
You do realize that we only offer support here for developers that require assistance with writing customized code or building their own applications that work with Event Espresso right?

**Comment by mnelson4** [comment]
Ya @sumant1412 we can't give you exact instructions on how to do that.

I'd suggest you override the ticket selector template (template files are in /modules/ticket_selector/templates. You'll need to override that default template in your theme or in a plugin, although while experimenting you could just hack `standard_ticket_selector.template.php` directly, but realizing that won't work for a live website because those changes will get overwritten when Event Espresso is updated). Instead of having a dropdown, you could replace it with a number HTML 5 input, or something fancier (like a hidden input, with buttons that use javascript to change the hidden input's value).

If you leave the input's name the same, I think that everything else will continue to work (like server-side processing shouldn't be affected)
