### ISSUE TITLE
Question about Making a different transaction for each attendee

### ISSUE THREAD

**Issue by Stefanos-Stefanidis** [eventespresso/event-espresso-core#276]
Questions

### Is this a bug report?
* [ ] no

Hi I am making some customization to ees.
When i choose 2 attendees from the Qty dropdown in the table esp_registration  i want to change th TXN_ID and in the esp_transaction table i want to create 2 rows. Making a different transaction for each attendee. Could you please tell me the files that write to the esp_registration and the esp_transaction table when you press 'Add Tickets and Continue to Registrant Details'? 

Thanks in advance

**Comment by mnelson4** [comment]
Hey Stefanos, 
the file responsible for setting up the transaction initially is `modules/ticket_selector/ProcessTicketSelection.php`, which gets the `EE_Cart` to do some work.
But creating two transactions like that will probably wreak all sorts of havoc on the single page checkout logic. 
Why are you wanting two transactions? Is it so you can split the payment up between the two?

**Comment by Stefanos-Stefanidis** [comment]
Thanks a lot for your response.

I am actually trying not to have a single page checkout logic.
Long story short i import a csv to single check out and split each user with comma(,) i create a different user with different ATT_ID in registration.
Also to spare me sometime can you tell me the files that send e mail when you add the attendees?

Thanks in advance.

**Comment by mnelson4** [comment]
> Long story short i import a csv to single check out and split each user with comma(,) i create a different user with different ATT_ID in registration.

Hmmm, ok. So it sounds like you're building a fairly custom solution there.

> Also to spare me sometime can you tell me the files that send e mail when you add the attendees?

It's a pretty long story there, but sending of messages gets kicked off by `core/business/EE_REgistraiton_Processor.class.php`'s `trigger_registration_update_notifications()`, which triggers an action which calls `modules/messages/EED_Messages`'s `maybe_registration()`, which makes a bunch of calls to `modules/messages/EE_Messages_Processor` to create the messages and then enqueue them for sending (we recently moved to sending messages on a separate request because they're pretty slow). 
Here's some of our documentation about messages https://github.com/eventespresso/event-espresso-core/tree/master/docs/E--Messages-System, although it mostly talks about creating custom messages, not triggering existing ones. Here's another post explaining how we're scheduling messages etc :https://github.com/eventespresso/event-espresso-core/tree/master/docs/E--Messages-System

Hopefully that gives you some good info to work with. It sounds like you're building a pretty custom solution and so you're probably going to need to be pretty familiar with the internals of EE

**Comment by tn3rb** [comment]
Sorry for the confusion but transactions are not created until you hit the checkout page.
You can look at the code in `EED_Single_Page_Checkout::_initialize_transaction()` (location: `modules/single_page_checkout/EED_Single_Page_Checkout.module.php`) to see how transactions are created and `EED_Single_Page_Checkout::_initialize_registrations()` to see how registrations are added to the transaction.

Emails are triggered for each registration after the entire transaction is finalized via an action hook in `EE_Registration_Processor::trigger_registration_update_notifications()` (location: `core/business/EE_Registration_Processor.class.php`)

**Comment by tn3rb** [comment]
doh! didn't see your response Michael... was busy writing mine :\
