### ISSUE TITLE
Secure my custom code from updates

### ISSUE THREAD

**Issue by Stefanos-Stefanidis** [eventespresso/event-espresso-core#279]
* [ ] no

Hi,
I have added some code inside EE_SPCO_Reg_Step_Attendee_Information.class.phpf file in the _process_registrations function, to add some functionality when there is a new registration.
 I also removed all the code inside from function in EE_Max_Length_Validation_Strategy_strategy.php 
Because i do not want any validation when i am adding an attendee. This code will be overwritten
when then plugin updates? How can i protect my code? Can i put it inside an action in my function.php? 
Thanks in advance

**Comment by mnelson4** [comment]
Cool @Stefanos-Stefanidis.
In order to protect your code during the next update, you need to keep it in your own plugin or theme's functions.php, and use actions and filters.
There is one filter in `EE_SPCO_Reg_Step_Attendee_Information::_process_registrations()` called `FHEE__EE_SPCO_Reg_Step_Attendee_Information___process_registrations__pre_registration_process`. Although it's a filter, you technically can use it just like an action (just make sure you continue to return whatever the filter's input was). If that filter doesn't meet your needs, please create a pull request with an action or filter placed wherever you need it. If you want to override from EE core behaviour, you may want to make execution of that core code conditional on a new filter. (The filter I just mentioned is an example of that).

Here's our documentation on actions/filters: https://github.com/eventespresso/event-espresso-core/blob/master/docs/A--Best-Practices/ee-actions-and-filters.md. But TBH if you don't get the naming exactly right that's ok, we'll fix. IMO the most important thing is getting the placement of the action/filters right so they meet your needs.

Regarding `EE_Max_Length_Validation_Strategy_strategy`, from which inputs did you want to remove the max-length validation? The forms code has a ton of filters and actions in it, so I suspect you should be able to use a filter to do what you want.

Eg, this code snippet, if placed in your theme's functions.php file, should remove the max length validation strategy from all inputs everywhere in EE

```
add_action('AHEE__EE_Form_Input_Base___construct_finalize__end', 'mn_remove_max_length_validation_everywhere', 10, 3);

function mn_remove_max_length_validation_everywhere(EE_Form_Input_Base $form_input, EE_Form_Section_Proper $parent_form_section, $name)
{
    $form_input->remove_validation_strategy('EE_Max_Length_Validation_Strategy`);
}
```

**Comment by tn3rb** [comment]
> Although it's a filter, you technically can use it just like an action (just make sure you continue to return whatever the filter's input was).

although this is technically correct it's not advised to do this (but I understand that MIchael was simply trying to ensure that you were able to do what you need to do).

The reason is because performing what should normally be an action from within a filter callback adds an unexpected side effect to that filter call. If some other code at some point determined that it needed to remove all filtering from the variable in question, and called `remove_all_filters('filter-in-question')` then it would unintentionally also remove your action that you hooked into that filter.

So it is **much** better to find the best location in the code to perform the logic you need to do and add a new action hook point there. Make a pull request: 

https://github.com/eventespresso/event-espresso-core/pulls

and assuming everything looks good, we will try to get your new hookpoint into the next release

**Comment by Stefanos-Stefanidis** [comment]
Thanks a lot! 
I want to remove the validation
in attendee registration form.
I will try to make my code with a hook!
But it is  a fairly custom solution to meet my
Ends.
You where a great help

**Comment by mnelson4** [comment]
> it returns 1 no matter how many attendees i try to register. Am i doing it wrong?

This should probably be a separate issue- it gets really confusing for anyone else looking up issues when the are several topics discussed in a single GitHub ticket. But here goes anyways...

That code snippet is always grabbing the first registration it finds in the database (not necessarily the one that's being registered right now), which registration must be in a group of only 1. 

So you should isntead be using the registration objects already in-use in that method. 

Eg. this is one way to get that. On line 140 there is this

```
 $registrations = $this->checkout->transaction->registrations($this->checkout->reg_cache_where_params);
        if ($registrations) {
```

you could get the group's size by changing it to this:

```
 $registrations = $this->checkout->transaction->registrations($this->checkout->reg_cache_where_params);
$first_reg = reset($registrations);
echo $first_reg->get('REG_group_size');
        if ($registrations) {
```

> And last how can i hook html code in specific pages?
You need to find the right hook, unless you want to add them using javascript (which isn't best). Can you please create a separate issue for that, and include a screenshot showing exactly where you want to add the buttons?
