### ISSUE TITLE
Remove primary registrant validation

### ISSUE THREAD

**Issue by Stefanos-Stefanidis** [eventespresso/event-espresso-core#282]
* [ ] no

Hi
I have made some custom change in the plugin 
and i do not want to have a primary registrant
so i added a `return true` to the  `function _validate_primary_registrant()`
in the beginning.
It works fine but i want if possible to have a hook to remove the validation
so i do not have to edit a file inside the plugin.

Thanks in advance.

**Comment by nerrad** [comment]
The Event Espresso system is currently oriented around the concept of a primary registration attached to a transaction and is dependent on it.  So while it may appear to be working fine for you, its possible there's other parts of the system you have not covered yet in your tests after your changes (unless you've made other changes in the code you just haven't mentioned here).

Before adding code (even filters and/or actions) we prefer pull requests that show where you want code changed (in this case a filter/action added) and then in the pull request ticket you can include an example of how you'd use the new filter and/or action.

Without more information demonstrating use case for it, we probably won't be adding a filter/action in this method because as I stated the concept of primary registrant is currently an important paradigm in the system.

**Comment by Stefanos-Stefanidis** [comment]
Thanks for the quick response.

Yeah i thought so. 
It is true i made customizations to fit my
requirements and maybe some other 
functionality does not work.

I will keep it like this! Thanks

**Comment by nerrad** [comment]
I don't know if you're new to WordPress development or not, but I can't emphasize enough that you are setting yourself for a lot of painful maintenance if you directly edit the files of a plugin.  Anytime you update the plugin you will lose your changes.  If you're doing work for a client you are also putting your client in a precarious position because they will be unable to safely make any updates of the plugin without overwriting the changes you made.  This puts them in the place of not being able to update to get new features and even worse update to get any security related fixes that might get released.

**Comment by Stefanos-Stefanidis** [comment]
Thanks for your concern and your time! 

But it is one line of code.
I recently updated the plugin
and i just re enter this one line.
