### ISSUE TITLE
Fatal Error on Activation (known issue)

### ISSUE THREAD

**Issue by tn3rb** [eventespresso/event-espresso-core#2933]
Upon activating EE when using the `EDTR/master` branch, the following error occurs
```php
Fatal error: Uncaught ArgumentCountError:

Too few arguments to function EventEspresso\core\domain\entities\routing\handlers\Route::__construct(),

0 passed and at least 3 expected in /core/domain/entities/routing/handlers/Route.php on line 65
```

this is related to #2911 and is waiting for #2916 but may require additional fixes

was unable to troubleshoot the above error because of 2911 and I'm assuming that there may be additional fixes required (hence this ticket) but I won't know for sure until 2916 is merged. The error **only** occurs during the activation request and refreshing the page fixes things and allows you to use EE with no further problems

**Comment by Pebblo** [comment]
Ran into this today when I started testing the editor.

Here's a full stack trace just because I have it open already:

`
( ! ) Fatal error: Uncaught ArgumentCountError: Too few arguments to function EventEspresso\core\domain\entities\routing\handlers\Route::__construct(), 0 passed and at least 3 expected in C:\laragon\www\ee4editor\wp-content\plugins\event-espresso-core\core\domain\entities\routing\handlers\Route.php on line 65
--



1 | 0.0009 | 541856 | {main}( ) | ...\plugins.php:0
2 | 0.0013 | 585080 | require_once( 'C:\laragon\www\ee4editor\wp-admin\admin.php' ) | ...\plugins.php:10
3 | 0.0015 | 599808 | require_once( 'C:\laragon\www\ee4editor\wp-load.php' ) | ...\admin.php:34
4 | 0.0017 | 610760 | require_once( 'C:\laragon\www\ee4editor\wp-config.php' ) | ...\wp-load.php:37
5 | 0.0022 | 706120 | require_once( 'C:\laragon\www\ee4editor\wp-settings.php' ) | ...\wp-config.php:97
6 | 0.1585 | 22812056 | do_action( ) | ...\wp-settings.php:403
7 | 0.1585 | 22812432 | WP_Hook->do_action( ) | ...\plugin.php:478
8 | 0.1585 | 22812432 | WP_Hook->apply_filters( ) | ...\class-wp-hook.php:311
9 | 4.7396 | 30840144 | EE_Bootstrap::register_shortcodes_modules_and_widgets( ) | ...\class-wp-hook.php:287
10 | 4.7396 | 30840144 | do_action( ) | ...\EE_Bootstrap.core.php:61
11 | 4.7396 | 30840520 | WP_Hook->do_action( ) | ...\plugin.php:478
12 | 4.7396 | 30840520 | WP_Hook->apply_filters( ) | ...\class-wp-hook.php:311
13 | 4.7396 | 30841648 | EE_System->register_shortcodes_modules_and_widgets( ) | ...\class-wp-hook.php:287
14 | 4.7396 | 30841648 | EventEspresso\core\services\routing\RouteHandler->addRoute( ) | ...\EE_System.core.php:974
15 | 4.7396 | 30841648 | EventEspresso\core\services\loaders\Loader->getShared( ) | ...\RouteHandler.php:55
16 | 4.7396 | 30841648 | EventEspresso\core\services\loaders\Loader->load( ) | ...\Loader.php:105
17 | 4.7483 | 30853208 | EventEspresso\core\services\loaders\CachingLoader->load( ) | ...\Loader.php:82
18 | 4.7485 | 30853208 | EventEspresso\core\services\loaders\CoreLoader->load( ) | ...\CachingLoader.php:147
19 | 4.7485 | 30853264 | EE_Registry->create( ) | ...\CoreLoader.php:111
20 | 4.7489 | 30853376 | EE_Registry->_create_object( ) | ...\EE_Registry.core.php:773
21 | 4.7489 | 30853992 | newInstanceArgs ( ) | ...\EE_Registry.core.php:1262
22 | 4.7489 | 30854120 | EventEspresso\core\domain\entities\routing\handlers\frontend\ShortcodeRequests->__construct( ) | ...\EE_Registry.core.php:1262
`

**Comment by tn3rb** [comment]
thanks @Pebblo 

the issue is fixed in another branch that has yet to be merged because it affects a how pile of underlying new code
