### ISSUE TITLE
Filtering the defaults on creating a new event documentation

### ISSUE THREAD

**Issue by joshfeck** [eventespresso/event-espresso-core#297]
### Is this a bug report?

* [ ] yes
* [ ] no
* [x] kind of

### What branch did this occur in?
master branch

### What version of WordPress is on the site this issue happened?
4.9.5

It seems that this document may need to be updated:
https://github.com/eventespresso/event-espresso-core/blob/master/docs/T--Tutorials/modifying-defaults-for-events.md#modifying-the-defaults-on-creating-a-new-event
The reason I created this issue is because I ran through the example code from there, and each time I'd go to create a new event, `$creating_event` is always empty, so none of the code there executes.

**Comment by nerrad** [comment]
I added the bug label because I think if the instructions in the documentation aren't working then that's as much as a bug as if expected behaviour in code wasn't working.  Unknown yet whether there's an actual problem with the filter referenced or the docs just need updated but agree needs looked at.
