### ISSUE TITLE
EDTR: Table View for tickets layout is messed up

### ISSUE THREAD

**Issue by sethshoultes** [eventespresso/event-espresso-core#3001]
This can be seen on Brent's NK site here:
https://brent.eventespresso.com/wp-admin/admin.php?page=espresso_events&action=edit&post=167&edit_nonce=c6654787ea

Using the Chrome web browser:
![image](https://user-images.githubusercontent.com/235315/85635800-11bb4500-b63c-11ea-818a-d0be704d1aaf.png)

**Comment by tn3rb** [comment]
@sethshoultes 

what device were you emulating?

AND... **really important**

did that happen after you were switching between multiple device emulations? 
because sometimes the emulations get completely messed up when you do that, but refreshing the page so that it loads as that device will fix things.

**Comment by sethshoultes** [comment]
I'm not sure what you are referring to about "device emulations". I am on my Mac desktop using the Google Chrome web browser.

**Comment by tn3rb** [comment]
oh I assumed it was because you were testing the site using Chrome's mobile emulators, which you can do via the following:

- right click anywhere on the screen (dunno what the Mac equivalent is to right clicking? Maybe sending Apple $125?)

- choose "inspect" to open up the dev tools

- in the top right corner of the dev tools window that opens, click on the button that looks like a phone in front of a tablet with the tooltip text "toggle device toolbar"

- the screen with the EDTR should now display a toolbar where you can select various devices to emulate, such as iPhones, etc

**Comment by tn3rb** [comment]
OH I see... that's in Table View on a screen under 1280px wide... kk will fix

**Comment by nicolad** [comment]
same is happening with datetime table view when there are more than 2 items there:

![image](https://user-images.githubusercontent.com/1477453/85738291-96739500-b708-11ea-8233-1c7b0c40999a.png)
