### ISSUE TITLE
Sold out status color change

### ISSUE THREAD

**Issue by Pebblo** [eventespresso/event-espresso-core#3018]
Can we please change this to orange to keep the status colours consistent between the editors?

Current editor status colours: https://monosnap.com/file/amvMaDey0cFQ59SDAUHbxpJvwnGP9u

(Note they don't have to match exactly, 'orange' is close enough orange)

**Comment by tn3rb** [comment]
right... forgot that I wanted to bring that issue up with the tEEm.

That color in the legacy code for sold out dates is a deep dark yellow (school bus yellow). If you look at the legend at the bottom of the Registrations admin page, you can see that same color used for "Incomplete" registrations, and compare that to our orange color used for "Not Approved" registrations.
![ScreenShot_20200706164738](https://user-images.githubusercontent.com/1751030/86669779-c93f4800-bfa8-11ea-8a32-294c969e0bb5.png)
Just pointing that out so that everyone is on the same page when we talk about colors.

Anyways, I have an alternate suggestion...
instead of changing the EDTR sold out color to yellow to match the old UI...
how about we change the legacy editor status colors to match the EDTR?

Here's why:

- red, orange, and yellow are typically used to indicate some kind of warning due to them being "hot" colors (think traffic lights, fire trucks, school buses, construction equipment, etc). As I've pointed out above, we already use these colors to indicate various warning and/or error states for transactions, registrations, and payments

- for registrations, we currently use purple for the "Wait List" reg status. What kind of Date and/or Ticket is a "Wait List" registration associated with? That's right... a "Sold Out" datetime or ticket. But currently for datetimes and tickets, we are using a "warning" color (yellow) to indicate "Sold Out":
![ScreenShot_20200706164758](https://user-images.githubusercontent.com/1751030/86678250-3b1b8f80-bfb1-11ea-815f-2fa3d96c6527.png)
As well, for datetimes we are using purple for the "Postponed" status (which should be some kind of warning color) and for tickets we use purple for the "Archived" status. It's all very inconsistent imho.

So going forwards, I would like to change the colors around a little bit to be better coordinated and consistent:

color | Datetimes | Tickets | Transactions | Registrations | general meaning
--- | --- | --- | --- | --- | ---
red | cancelled | - | failed | declined | real bad
orange | - | - | overpaid  | not approved | bad warning
yellow | postponed | - | abandoned | incomplete | warning
green | active | on sale | complete | approved | good
blue | upcoming | pending | incomplete | pending | default good but not done yet
purple | sold out | sold out | - | wait list | no spaces available
grey | expired | expired | - | cancelled | done / over / no more
black | trashed | trashed | trashed | trashed | trashed maybe?

thoughts?

**Comment by sethshoultes** [comment]
I think the colors you've outlined above will work and consistency across the different areas sounds great.

**Comment by Pebblo** [comment]
Personally I don't think changing the colours users are used to seeing on the legacy editor is a good idea and iirc is why we didn't change them a while back.

I'm 99% certain this is going to get pushback as soon as we release the above from anyone that already knows the difference between (for example) a sold-out and archived ticket. I know if it were me and I just randomly opened up the event editor to see various different colours that I'm not used on tickets I knew shouldn't be archived etc (the above will be changing sold out tickets to 'appear' sold out at first glance) I think something broke and start digging into it.

So imo we are likely going to panic users for no reason here and then either get :

'OMG ALL MY TICKETS JUST ARCHIVED! HELP!"

Or:

'Why did you just change the colours? I wasted X hours trying to figure this out only to find nothing broke"

Yes I know we can add this to the what's new section etc but we all know people don't read.

Seeing how some of those users will have been using EE for years the above would be no surprise to me at all.

---

If you want the colours changing moving forward with the new editor then ok, I won't argue with that any further but again I really don't think its a good idea to (what will appear to are users as) randomly change the current editor colours.

**Comment by nicolad** [comment]
based on @Pebblo feedback it sounds like color change might be better accompanied with tooltips, such that when user see a new or changed color he/she can just hover over and know exactly what does that mean;
of course, I might miss some important details here that I am not aware of, but these are my 2 cents

**Comment by Pebblo** [comment]
Thanks @nicolad but already have tooltips showing on the status bar but many still miss them unfortunately and it's those users that I'm referring to above with the 'Omg' title.

**Comment by tn3rb** [comment]
@Pebblo 

we can simply add a little text notice like the following:

![ScreenShot_20200707162442](https://user-images.githubusercontent.com/1751030/86855117-92cc0080-c06e-11ea-828a-53ec42b8c72e.png)

which when clicked would display something like:

![ScreenShot_20200707162514](https://user-images.githubusercontent.com/1751030/86855126-952e5a80-c06e-11ea-9289-0cce4ccd704e.png)

text could be better but you get the idea

**Comment by Pebblo** [comment]
> we can simply add a little text notice like the following

Yeah ok, I get the feeling we'll still get some posts about it (referring back to the whole 'people don't read' comment) but that notice will help, thanks.

> With regards to the new editor, we display the actual status text on the cards themselves at the bottom of the coloured sidebar so that's kinda hard to miss

I'm not worried about people missing the status on the new editor as its pretty obvious, I just prefer both to be consistent so support didn't need to swap and change between colours when working through this and having people with both the new and old editor posting up.

Initially, I thought the colour change was a simple oversight but obviously not, tbh I'm still not a big fan of changing the colours but I understand why you want to, the above does fit better and I'm not arguing against doing it any further.

**Comment by tn3rb** [comment]
this is fixed in the `barista-prod` branch now

**Comment by garthkoyle** [comment]
Can Sold out status color change be tested on brent.eventespresso.com?

**Comment by garthkoyle** [comment]
@Pebblo can you test this please?

**Comment by tn3rb** [comment]
> Can Sold out status color change be tested on brent.eventespresso.com?

yes the the `barista-prod` branch is active on `brent.eventespresso.com`

**Comment by garthkoyle** [comment]
Is it possible to put the red text about the notice underneath the legend heading to add more context to the message?
![image](https://user-images.githubusercontent.com/3094547/97477950-e3b17e80-1915-11eb-9298-f6d6503bc55c.png)

**Comment by Pebblo** [comment]
I like the location Garth mentioned, can we also split out changes for their relevant sections as it highlights statuses (stati/statuseseseseses) that don't exist in some sections.

These 2 have no meaning in the Event Editor:
https://monosnap.com/file/Xw7q17O6lP5ea5B9QU0vwhkrDiCywr

These 3 have no meaning in the message queue:
https://monosnap.com/file/s6fkfFshe1EEWyeLStzN88Dg8N1JKl

Also, note that 'Failed' (Status MFL) has been changed to a more of a 'pink'

'Debug only' messages (Status MDO) has been changed to a 'red'.

Those 2 changes expected?

I would have thought Failed should remain red and I'm not really fussed on what it used for MDO, it's more by us than users.

**Comment by garthkoyle** [comment]
@Pebblo I'm going to close this. Please reopen this if you have any more changes.
