### ISSUE TITLE
Make 'Edit Datetime/Ticket dates' button icon more obvious?

### ISSUE THREAD

**Issue by Pebblo** [eventespresso/event-espresso-core#3042]
I completely missed the fact that the calendar icon under the date was a button that allowed you to edit the date/time of the datetime/ticket.

![Entity Sidebar edit date button](https://user-images.githubusercontent.com/1751030/88406233-3dd5fd00-cd85-11ea-9696-9363a8ec356b.png)

I was about to create a ticket requesting something like clicking the date took you to the 'full' editor for easier access or something and just happened to hover the mouse over that icon. 

I really like having those details editable there but given the fact that I didn't even realise it was a button, should we make that a little more obvious?

Or maybe add that icon to the legend?

**Comment by tn3rb** [comment]
@nicolad 

any ideas about how to do this without wrecking the existing UI design too much?

potential solutions I can think of:

- add a border to that button (may want to consider that for ALL icons for consistency then)

- change ALL button backgrounds to default background color: `var(--ee-background-color)`

- change ALL button backgrounds to default button background color: `var(--ee-button-background)`

- change ALL button backgrounds to a semi-opaque background color like `rgba( 192, 192, 192, 0.25)` which would potentially work on ALL background colors whether dark or light. We could simply change the `--ee-button-background` var to this value 


I kinda like that last option, because it requires the least changes and works ok with the existing styles.

Here's a screenie after haxxoring things via dev tools:

![ScreenShot_20200724085134](https://user-images.githubusercontent.com/1751030/88410408-34e82a00-cd8b-11ea-8b3f-3dffc540c062.png)

I'm open to other ideas though

**Comment by Pebblo** [comment]
Noice! This is muchos better.

Thanks guys.
