### ISSUE TITLE
Convert `[ESPRESSO_EVENT_ATTENDEES]` shortcode to gutenberg block

### ISSUE THREAD

**Issue by tn3rb** [eventespresso/event-espresso-core#316]
# branch Gutenberg/event-attendees-block
plz also see https://events.codebasehq.com/projects/event-espresso/tickets/11426 for further commit history

**Comment by nerrad** [comment]
@tn3rb I committed a number of fixes to the Branch attached to this ticket (`Gutenberg/event-attendees-block`) along with some fixes in #466 (that should get merged to Gutenberg/master once approved).  Fixes/changes include:

- fixing some of the import schema's in the js (use the package name instead of the `wp` global, webpack takes care of building correctly)
- fix jed "domain not found" error because blocks script was importing from `@wordpress/i18n` instead of `@eventespresso/i18n`
- move files around so they are more granular/modular
- move EventSelect component to InspectorControls (you can't have inputs in the main edit area because they will be disabled - all inputs have to be in controls)
- change name of block to `EventAttendees` (react standard has components capitalized).  Also shortened the name because the source file path is a namespace so we don't have to be verbose with our component names.
- I wrapped the block in a `withSelect` hoc that was wired up to `eventespresso/lists` for storing/retrieving the list of attendees by eventId.  
- Added a **very simple** output of a list of attendee names to demonstrate things are working when event id is selected in the control.

So the block is far from finished but its at a state now where I think there will be enough for you to learn/evaluate and build off of.  I thought it'd be helpful to get it to this point mostly because it helped me iron out some bugs in some of the upstream code (stores, event-select component).

Not an exhaustive list, but things that need done:

- ensure selected event id is persisted (this is a configuration issue, if you get stuck let me know)
- style the attendee list output in the editor to be what it will be on the frontend
- consider if you want to add additional controls for controlling the attendee list output (to match existing shortcode options and maybe add additional options?)
- Work on how this will get compiled for display in the frontend content.  You _shouldn't_ load the same editor script for the frontend (block does not need registered javascript side on frontend).  Two options are to either use server rendering via block registration, or the `save` property value in the block can output a skeleton container that provides enough data for a frontend react script to pull in the attendee list.  If you go with the latter option, you'll probably want to put the javascript output of attendee list  in its own react component so it (along with any css) can be loaded either in the editor via the editor script or in the frontend via the frontend script.  If what I'm suggesting as options here is not clear, let me know 👍

**Comment by nerrad** [comment]
Ya it works, I just whipped up a really quick proof of concept (against the latest master branch of gutenberg):

![Demonstration of working input](http://g.recordit.co/dUn9c5UzfJ.gif)

**Comment by nerrad** [comment]
Before work on the branch related to this issue can be continued, #466  needs to be completed and merged into `Gutenberg/master` and then into this branch.  It in turn has a dependency on #471 which is currently up for review.  It's a fairly intricate chain but everything is ready to go, it just has to be done in order (and reviewed/discussed as necessary)

**Comment by nerrad** [comment]
K all necessary merges have been done and are now in the `Gutenberg/event-attendees-block` branch.

**Comment by tn3rb** [comment]
Currently the Event Attendees block :

* displays attendees for the selected event
* properly formats everything 
* saves the selected event id so that upon refresh or return to the post, the previous event is automatically selected and the corresponding attendee list is displayed (yay)

PLZ pull the latest changes for this to see
(you'll need to rebuild the assets of course even though I had pushed some changes)

Here are some wonky things that are happening that may require your superior skills to fix:

* the `withSelect()` HoC in `assets/src/blocks/widgets/event-attendees/block.js` fires repeatedly when first loading the editor as well as after selecting an event from the sidebar. I've added some console logging so that you can see this happening. It's pretty extreme as it appears to happen about 24 times just on initial loading. I think we need to fix that.
* selecting a different event from the event selector does not appear to send an updated attendees array to the function that renders the HTML for the attendee list. This may be connected to the way that I am persisting the `selectedEventId` in the block attributes, but from everything I have read, that appears to be the correct way to do things, or it may be connected to the above issue with the `withSelect()` HoC
* the persisted `selectedEventId` does not appear to be getting passed to the PHP callback used for the dynamic rendering. Again, I may not be persisting that data correctly or it might be some other issue. THe attributes array being received by the block's PHP callback is empty.
