### ISSUE TITLE
Cloned Default tickets have wrong prices.

### ISSUE THREAD

**Issue by manzoorwanijk** [eventespresso/event-espresso-core#3313]
Steps:
- Create a couple of default tickets or more
- Add prices to those tickets
- Save
- Add New event
- Check the prices of these cloned tickets

They are incorrect

**Comment by tn3rb** [comment]
I think this may be some bad data in your db

When I first started looking into this, I was able to reproduce the issue!
I would create some default tickets, save them, then create a new event, and the prices would be different.

Initially I looked at the code in `\core\domain\services\admin\entities\DefaultPrices::cloneDefaultPrices()` which is responsible for creating the default prices for default tickets when you create a new event, but that code is not really doing anything except cloning all of the default tickets and prices and creating the appropriate relations.

I eventually discovered that the price order fields appeared to be wonky for all of my default prices.
I followed those rabbit holes and discovered that a bunch of my OLD default prices and tickets had wonky price orders set as well. WHY this affected NEW default tickets, I'm not sure, but here's what I did to get things working:

- deleted ALL of my old default tickets and prices (except for the one free ticket)
- also went directly into the db and deleted anything that looked like default data (again, except for the one free ticket and the default $0 base price)
- refreshed the EDTR
- created new default tickets with multiple price modifiers
- saved those new defaults 
- created a new event after all of updates finished
- the default tickets for this new event were all correct this time

Here's some screenies to show the results (don't have any of the initial wonky prices)
(veuillez excuser les français)

## my three default tickets just after initial creation

![ScreenShot_20210204170508](https://user-images.githubusercontent.com/1751030/106977150-9e6bcc80-670e-11eb-91d1-f89b2ebffa99.png)

## TPC for the "Default Prices in Order" ticket

![ScreenShot_20210204170534](https://user-images.githubusercontent.com/1751030/106977196-b7747d80-670e-11eb-8190-b0d02a9b11df.png)

## TPC for the "Default Prices in Reverse Order" ticket

![ScreenShot_20210204170557](https://user-images.githubusercontent.com/1751030/106977248-cd823e00-670e-11eb-81bf-2e9182f5c88f.png)

## the three new tickets created for my new event
plz note that the ticket prices are both correct and the same as they were when I initially created these defaults

![ScreenShot_20210204170703](https://user-images.githubusercontent.com/1751030/106977391-1d610500-670f-11eb-8ceb-e15ef0b9e6c7.png)

## TPC for the NEW "Default Prices in Reverse Order" ticket
(notice that the price IDs are different than above, since these are clones of the above ptices)

![ScreenShot_20210204170747](https://user-images.githubusercontent.com/1751030/106977414-294cc700-670f-11eb-97fd-189ec725eac3.png)

and here's the corresponding database fields for the above prices:

![ScreenShot_20210204171421](https://user-images.githubusercontent.com/1751030/106977554-6f098f80-670f-11eb-8e3d-e14833ab24d2.png)

## TPC for the NEW "Default Prices in Reverse Order" ticket

![ScreenShot_20210204170809](https://user-images.githubusercontent.com/1751030/106977590-7b8de800-670f-11eb-8588-c592a6bec5de.png)

and its corresponding database fields for the above prices:

![ScreenShot_20210204171321](https://user-images.githubusercontent.com/1751030/106977653-96f8f300-670f-11eb-96a3-835efccd1e38.png)


So at this point, it's not 100% clear whether this is a bug in the code somewhere or whether its simply a case of wonky development db data corrupting how things work. That said I can no longer recreate the issue. Can you plz try deleting ALL of your default entities (except the one free ticket and free base price) and then try again from scratch?

I'm going to try a completely new installation and see if I can reproduce the initial issue, so not going to close this yet until we are both 1000% confident that things work properly.

**Comment by tn3rb** [comment]
# OK

Things are different after a fresh install...


## three default tickets just after initial creation

![ScreenShot_20210204175559](https://user-images.githubusercontent.com/1751030/106979289-e260d080-6712-11eb-9870-409cf356e34e.png)

### **IMPORTANT** Plz note that there was a default tax created upon activation named "Federal Tax" that initially appeared when I clicked the "Add Default Prices" button in the TPC step of the new default ticket creation process. I deleted that tax from each of the default tickets prior to saving so that the ticket prices would match my previous test data I posted earlier.


## TPC for the "Default Prices in Order" ticket

before save:

![ScreenShot_20210204175350](https://user-images.githubusercontent.com/1751030/106979328-f60c3700-6712-11eb-94ec-1758970b1c25.png)

after save:

![ScreenShot_20210204175648](https://user-images.githubusercontent.com/1751030/106979365-091f0700-6713-11eb-8075-43dfcb09d015.png)


## TPC for the "Default Prices in Reverse Order" ticket

before save:

![ScreenShot_20210204175536](https://user-images.githubusercontent.com/1751030/106979389-13410580-6713-11eb-978c-e7646e647ea4.png)

after save:

![ScreenShot_20210204175703](https://user-images.githubusercontent.com/1751030/106979409-1d630400-6713-11eb-8ec5-51ba8447b9a5.png)


so good so far... 

now let's create  new event and see what happens...

### 💥 **BOOM** 💥 

![ScreenShot_20210204175759](https://user-images.githubusercontent.com/1751030/106979685-b134d000-6713-11eb-9b2c-537740b96135.png)

And here's the culprit for both tickets:

![ScreenShot_20210204175902](https://user-images.githubusercontent.com/1751030/106979714-c01b8280-6713-11eb-9c2c-adca21ffb3dc.png)

![ScreenShot_20210204175939](https://user-images.githubusercontent.com/1751030/106979724-c4e03680-6713-11eb-88c6-e336c6d5c645.png)

That tax has reappeared because it was marked as a default price and was therefore added to the newly created default tickets for the new event.

Going to reevaluate how taxes are applied in `DefaultPrices::cloneDefaultPrices()`

**Comment by tn3rb** [comment]
OK... changed `DefaultPrices::applyTaxes()` from

```php
    private function applyTaxes(EE_Ticket $ticket, bool $is_free)
    {
        if (! $is_free && ! empty($this->taxes)) {
            foreach ($this->taxes as $tax) {
                // assign taxes but don't duplicate them because they operate globally
                $ticket->set_taxable(true);
                $tax->_add_relation_to($ticket, 'Ticket');
            }
        }
    }
```

to (notice the addition of `$ticket->taxable()` in the IF condition)

```php
    private function applyTaxes(EE_Ticket $ticket, bool $is_free)
    {
        if (! $is_free && $ticket->taxable() && ! empty($this->taxes)) {
            foreach ($this->taxes as $tax) {
                // assign taxes but don't duplicate them because they operate globally
                $ticket->set_taxable(true);
                $tax->_add_relation_to($ticket, 'Ticket');
            }
        }
    }
```

and upon creating another new event:

![ScreenShot_20210204181307](https://user-images.githubusercontent.com/1751030/106980361-e55cc080-6714-11eb-8b07-f373a945cb0a.png)

everything looks great again.

Now that said, can you look at your prices that were created and see if there are extra taxes added that you did not intend to be there. If that's the case, then you can try the fix above (which I'll push in a PR in a minute) or if your wonky tickets do NOT have extra prices, then can you plz investigate more to see if you can more clearly identify where the problem is originating. Screenshots of data would be great so that i can see what is actually happening.

**Comment by tn3rb** [comment]
plz see: https://github.com/eventespresso/event-espresso-core/pull/3314

**Comment by manzoorwanijk** [comment]
Everything is fine there except the ticket total. If you check the related prices for cloned tickets, everything is good except the ticket total which is incorrect.

After debugging, I found out that in `DefaultPrices::create()`, `$entity->ticket_price()` is correct before and after calling `applyTaxes`, the problem is that `$entity->get_ticket_total_with_taxes(true)` returns the wrong price which results in the issue. I have no idea how that function works internally.

**Comment by tn3rb** [comment]
plz see: https://github.com/eventespresso/barista/issues/706

**Comment by tn3rb** [comment]
@manzoorwanijk 
is this fully resolved now?
can you verify that everything operates to your expectations plz?

**Comment by manzoorwanijk** [comment]
> 
> 
> @manzoorwanijk
> is this fully resolved now?
> can you verify that everything operates to your expectations plz?

You had mentioned that it was an issue bot server-side and client-side, i.e. the price calculation was wrong. You also mentioned that it will be fixed by setting the order of all the current prices to be the same via some DMS.
