### ISSUE TITLE
Allow unpaid Registrations to pay if tickets are still available after ticket sale end date is passed

### ISSUE THREAD

**Issue by sethshoultes** [eventespresso/event-espresso-core#336]
Original Codebase ticket: https://events.codebasehq.com/projects/event-espresso/tickets/11274
See also: https://events.codebasehq.com/projects/event-espresso/tickets/11420

Steps to replicate the issue:

1) Register for an event and either abandon after completing the reg form or choose an offline payment method, then finalize.
2) set the ticket's sale end date to yesterday's date
3) Return to SPCO (revisit the txn) and you'll see this message:

> We're Sorry It appears that the event you were about to make a payment
> for has sold out since you first registered. If you have already made
> a partial payment towards this event, please contact the event
> administrator for a refund. Please note that availability can change
> at any time due to cancellations, so please check back again later if
> registration for this event(s) is important to you.

The above message isn't correct in this case because the event is not sold out, but it is past the sale end date.

**Comment by tn3rb** [comment]
@sethshoultes 
re: the issue as described in the title

> Allow unpaid Registrations to pay if tickets are still available after ticket sale end date is passed

enabling this would allow people to still obtain early bird pricing after that pricing option has been closed.

@joshfeck 

I've re-opened #826 because the code fix required for that issue is very different than what is required for this issue

**Comment by joshfeck** [comment]
We'll close this because we actually do not want to allow people to obtain early bird pricing after that option has been closed.

**Comment by tn3rb** [comment]
@joshfeck 

there's still the issue @sethshoultes pointed out that the error message you receive when a ticket is expired is incorrect, which is a separate issue than what the title for the issue says.

we **could** (if you want) reword the title to something like:

> SPCO shows "event sold out" error when ticket is expired

and then use this issue to fix that error message so that it is more appropriate, but not allow expired tickets to be paid for.

again, feel free to close ro do whatever with this.

**Comment by joshfeck** [comment]
I retested this from the steps outlined in the original ticket and it appears something has changed, you are allowed to pay for the previously registered ticket. So there's a different issue now.
