### ISSUE TITLE
Verify Nonce in PUE Stats

### ISSUE THREAD

**Issue by sethshoultes** [eventespresso/event-espresso-core#3429]
In the current code, if the nonce isn't set, the nonce won't be
checked, allowing for a bypass of the nonce restriction:
https://plugins.trac.wordpress.org/browser/event-espresso-decaf/tags/4.10.11.decaf/core/domain/services/pue/Stats.php#L194
This can be repaired by changing the logic to:

```
if ( isset( nonce ) || ! wp_verify_nonce ) {
return;
}
```

**Comment by tn3rb** [comment]
lolz their suggested fix will totally break things... 😆 

```
if ( isset( nonce )...
	return;
```

so if the nonce is set then... don't proceed with running the code that the nonce is supposed to be guarding?!?!?

their wording is also pretty funny:

> if the nonce isn't set, the nonce won't be checked

uhhh... ya.. .that's right.. how do you check the nonce value... IF IT'S NOT SET ?!?!?

lolz


anyways, the issue with the existing code is still obvious:

```
if (isset($_POST['nonce']) && ! wp_verify_nonce($_POST['nonce'], 'ee-data-optin')) {
	exit();
}
```

which is basically that the code following that conditional is still allowed to run if no nonce is set because we ONLY exit IF the nonce exists but is invalid. 

We need to also exit if there is no nonce whatsoever. So EZ fix.
