### ISSUE TITLE
PHP8: Unknown named parameter $new_template

### ISSUE THREAD

**Issue by webaware** [eventespresso/event-espresso-core#3515]
**Describe the bug**

When saving a new custom message template, PHP 8.0 throws a fatal uncaught exception "Unknown named parameter $new_template". Does not happen in PHP 7.4.

**To Reproduce**

1. in WP admin, go to Event Espresso > Messages > Default Message Templates
2. click Create Custom button for Registration Approved
3. click Save in message editor screen

**Expected behavior**

Message editor should save successfully. This happens in PHP 7.4.

**Environment:**
 - Version of Event Espresso:  4.10.13.p
 - Version of WordPress: 5.8
 - Browser: Firefox 91.0.2
 - PHP Version: 8.0.10

**Comment by tn3rb** [comment]
sry i missed this issue submission somehow, will look into this today
not sure how that is happening considering we do not use named variables anywhere
do you know if you have any customizations active?

**Comment by webaware** [comment]
It was a couple of weeks ago now, but IIRC I tested it in isolation with a plain-old twentysomething theme and no hooks, same deal. (I'm running in a theme based on Timber/Twig, but switched to a plain theme to confirm it wasn't me!)

**Comment by tn3rb** [comment]
pushed a fix to this branch: https://github.com/eventespresso/event-espresso-core/tree/BUG/fix-named-parameter
feel free to try that out if you know how to use git to do so.

otherwise you'll have to wait for that to be tested and then get packed up for release...

OR

you can manually apply the same fix to your files locally:
https://github.com/eventespresso/event-espresso-core/pull/3520/files

**Comment by webaware** [comment]
Thanks, hope to check it out this weekend; ran out of time today.

**Comment by rubas** [comment]
> otherwise you'll have to wait for that to be tested and then get packed up for release...

Is there an ETA for an official release?
