### ISSUE TITLE
Event Status Banner Not Showing in Default Twenty Twenty-Two Theme

### ISSUE THREAD

**Issue by garthkoyle** [eventespresso/event-espresso-core#3676]
The event Status banner does show in the default Twenty Twenty-One theme, but not the Twenty Twenty-Two theme:

Twenty Twenty-One: 
![image](https://user-images.githubusercontent.com/3094547/149567763-8cbf467f-c7e2-43c9-9f2b-584948c82c62.png)

Twenty Twenty-Two:
![image](https://user-images.githubusercontent.com/3094547/149567625-fb69a727-92d9-484b-b69f-d8e15f87ac69.png)

**Comment by tn3rb** [comment]
nothing is showing up on archive pages from what I've seen so far

**Comment by tn3rb** [comment]
@hoseinrafiei 
can you try to investigate this a bit?

First update to the latest version of WP 5.9 so that you get the latest copy of the new 2022 theme.

you'll likely to look around in one or more of the following:

- public/template_tags.php
- public/Espresso_Arabica_2014
- modules/event_single/EED_Event_Single.module.php
- modules/events_archive/EED_Events_Archive.module.php

don't spend too long because it could very well be a problem within the 2022 theme. 
So maybe 1-2 hours, then report back here plz and thnx.

**Comment by hoseinrafiei** [comment]
@tn3rb 

I checked this theme. It's a block theme which means it doesn't follow classic theme hierarchy and loop. It generates the content via blocks instead of classic loop.

Moreover, our event status banner is hooked to the `the_title` correctly but we have a condition to append the status banner only when `in_the_loop()` function returns true but in block themes it returns false since there is no loop. if we remove that condition from our code then, it will work just fine.

Another solution can be to detect the loop using another possible way and create a combined or condition like `new_detection() || in_the_loop()`.

**Comment by tn3rb** [comment]
thnx Hossein, 

I don't remember why we added the `in_the_loop()` check as that was probably 6-7-8 years ago that that was done, but I'm guessing if we simply remove it, then things will go badly.

For your second solution, the `new_detection()` function would have to detect that the content was being generated via blocks, which off the top of my head might not be possible. That said, want to give it a try?

Can you spend an hour or two researching if there is a relatively straightforward to detect when that shortcode is running within a block instead of the loop?

**Comment by tn3rb** [comment]
well let's try your fix and see how that goes
so yes, plz create a PR for this 👍🏻 thnx

**Comment by hoseinrafiei** [comment]
@tn3rb 

Please check the PR and let me know your thoughts.
