### ISSUE TITLE
Make the Registrations > Check-in List Table Check in/out Actions Work Without First Filtering to Events

### ISSUE THREAD

**Issue by garthkoyle** [eventespresso/event-espresso-core#3743]
They don’t do anything after you click the check in/out button on the List Table. We should hide those buttons if they aren’t supposed to use those buttons. But the check in/out buttons do work when you filter to a specific event.

Since each row is tied to a single event and registration, we should make them work without filtering to an event.

**Comment by tn3rb** [comment]
this has been updated and is active on MENW now.
plz note that due to how some of the checkin logic works I was not able to make it so that you can just perform checkins on ANY registration at ANY time.

That said, the checkins table is now capable of performing checkins on ANY registration for any **ACTIVE** event, meaning one whose start date has been reached and end date has not yet been reached. Since it's likely that most event admins will want to begin checkins before the event actually starts, a default offset of 2 hours has been applied. So if an event started at 8pm, then the checkins list will begin allowing checkins at 6pm. This can be filtered via the new `FHEE__EventEspresso_core_domain_services_admin_registrations_DatetimesForEventCheckIn__start_date_offset` filter which simply needs to return a new time in seconds to subtract from the event start date. For example, if an event admin wanted to begin checkins 4 hours before the actual event start date, they would need to add a filter like:

```php
add_filter(
    'FHEE__EventEspresso_core_domain_services_admin_registrations_DatetimesForEventCheckIn__start_date_offset',
    function () {
        return HOUR_IN_SECONDS * 4;
    }
);
```

this doesn't help Event Smart users, so we can think about adding an admin option for controlling that offset

**Comment by garthkoyle** [comment]
That seems to be working great!
<img width="469" alt="image" src="https://user-images.githubusercontent.com/3094547/159346133-65a16008-562d-419e-86e6-1ed2fe706ba9.png">

What do you want to do with this ticket?
