### ISSUE TITLE
Need Attention ! Plugin Performance and Speed Optimization

### ISSUE THREAD

**Issue by mohdshakeel** [eventespresso/event-espresso-core#3767]
I would like to draw attention of team EE plugin. This is very serious issue. Here are the plugin performance reports based on database queries. There are 96 database query called with duplicate queries (means same repeated select queries at single event page).

96 queries is very big number for a single Event ADD/Update page in DECAF. Why are we need so much SELECT query to load this single page. 
 
There are many duplicate means repeated queries and slow queries also.

 It goes to very high in premium version. It will affect our plugin performance. We should consider it.

**ALL QUERIES CALL REPORT**

![query_caller_3](https://user-images.githubusercontent.com/1772444/158428428-3a249a72-90c8-4a47-8752-99bd7d9c63e3.png)

**SLOW QUERIES REPORT**

![slow_query_report](https://user-images.githubusercontent.com/1772444/158302587-bfad2620-edfa-4dfd-89f9-293611547d62.png)

**DUPLICATE QUERIES REPORT**

![duplicate_query](https://user-images.githubusercontent.com/1772444/158302583-3e21fdc4-a6cf-418e-811e-da9a12af101f.png)

**SUMMARY REPORT**
![speed_report](https://user-images.githubusercontent.com/1772444/158429621-8a75d958-3b9c-484e-8dc1-f998154abfa6.png)

**Comment by tn3rb** [comment]
Hi Mohammad, thnx for providing the information that you have but can you plz provide some example links for the specific pages these issues occurred on? You stated in one spot that this happened "at single event page" is that in the admin  (ie: the event editor) or is that an event listing on the frontend?

I'm guessing that this is for the event editor because the frontend doesn't (afaik) perform any queries related to Message Templates, but the Event Editor does for this section:

<img width="581" alt="Screenshot 2022-03-16 151121" src="https://user-images.githubusercontent.com/1751030/158699971-ad6f35f1-4cfe-4f49-b557-3318098b19ad.png">

The messages system is... ummm... not our best work so I'm not surprised to see a bunch of duplicated queries.  
The solution for this would be to find where those queries are executed and look into ways to rewrite the queries to be more performant. I'm guessing that the queries are probably running within one or more loops. 

You can see from the last screen shot that queries 150 - 161 are identical except for the specified message type. 
It's probably something like:

```
$message_types = db->query( "SELECT message_type FROM ... " );
foreach ( $message_types as $message_type ) {
	$message_template = db->query( "SELECT message_template FROM ...  WHERE ... MTP_message_type = " . $messege_type );
	// do stuff with template
}
```

whereas the smart thing to do would be to replace that loop with a single query that returns ALL of the templates in one shot, like:

```
$message_types = db->query( "SELECT message_type FROM ... " );
$message_templates = db->query( "SELECT message_template FROM ...  WHERE ... MTP_message_type IN (" . $messege_types . ")"  );
```

The messages code is tricky to navigate and make sense of (i'm trying hard to be nice here), so I'm not eager to dive in and try to fix that as there are a lot of other things that need attention too.  Now that said, maybe when we get through this next big batch of work, we can talk to Garth about looking into this more and you can take some time to investigate this more and find the actual code that is responsible for the above issues. 

One final thing to keep in mind is that Event Espresso is likely a lot more complex than any other plugin you have worked on (i'm totally speculating here and could be completely wrong so my apologies if that is the case) so some things will be inherently slower than a basic plugin that does not do as mush as EE does.

**Comment by mohdshakeel** [comment]
Hi Brent  ,
@tn3rb You are right. This is Event edit page at dashboard http://stable.local/wp-admin/admin.php?page=espresso_events&action=edit&post=21.  I gave the results for all queries for this page only. 

Why do we need so much select queries from a table in a single Event edit  page. 

It would be perfect to replace that loop with a single query that returns ALL of the templates in one shot like:-
$message_types = db->query( "SELECT message_type FROM ... " );
$message_templates = db->query( "SELECT message_template FROM ...  WHERE ... MTP_message_type IN (" . $messege_types . ")".

We can remove the duplicate queries easily. 

I am working on full report with File name, Function Name, Line of code etc. And I will try to give exact fixes for speed performance. 

May I contribute in code to fix these issues?

**Comment by tn3rb** [comment]
> We can remove the duplicate queries easily.

that might be a premature conclusion 😆

> May I contribute in code to fix these issues?

plz get permission from Garth first before working on this!
As far as I'm concerned you are welcome to try, but I think you will find things to be a bit more complex than you are expecting.

**Comment by garthkoyle** [comment]
@mohdshakeel Thank you for taking initiative, but please do any assigned testing before working on this. And before you do the actual work, please plan out your work and ask Brent for approval before starting.

**Comment by mohdshakeel** [comment]
@garth I will follow you.
