### ISSUE TITLE
Custom Setting Value from Payment Method is not setting in OnSite Gateway class

### ISSUE THREAD

**Issue by archergod** [eventespresso/event-espresso-core#379]
As per Mockup class and sample, where in Offsite we create a Setting Form's Extra field and they get set in Gateway class for offsite. But for OnSite these values are not setting by its own. is there anything I am missing. 

       public function generate_new_settings_form() {
		$form = new EE_Payment_Method_Form(array(
			'extra_meta_inputs'=>array(
				'truevo_user_id'=>new EE_Text_Input(array(
					'html_label_text'=>  sprintf(__("User ID %s", "event_espresso"), $this->get_help_tab_link() )
				)),
			    'truevo_password'=>new EE_Text_Input(array(
			        'html_label_text'=>  sprintf(__("Password %s", "event_espresso"), $this->get_help_tab_link() )
			    )),
			    'truevo_entity_id'=>new EE_Text_Input(array(
			        'html_label_text'=>  sprintf(__("Entity ID %s", "event_espresso"), $this->get_help_tab_link() )
			    )),
			)));
		return $form;
	}

These fields are shown in admin, and I Can save value in them. 

    class EEG_TAS_Truevo_Onsite extends EE_Onsite_Gateway{

	/**
	 * All the currencies supported by this gateway. Add any others you like,
	 * as contained in the esp_currency table
	 * @var array
	 */
	protected $_currencies_supported = array(
					'USD','EUR','GBP');

	protected $_truevo_user_id;
	
	protected $_truevo_password;
	
	protected $_truevo_entity_id;

	public function __construct() {
		//if the gateway you are integrating with sends a separate instant-payment-notification request
		//(instead of sending payment information along with the user)
		//set this to TRUE
		parent::__construct();
	}
       .....

Now I have these varaiable created in my Gateway.php class, but values for my variable is not getting set. I test Offsite class example and values get set in that. Is there something wrong in this code or if there is any other way to pick those variable. Also how can I determine if "Debug" is On in setting.

**Comment by mnelson4** [comment]
hey @archergod, that code looks correct, and so those settings should be set on the gateway class. It's not normally a problem with onsite gateways because `EEG_Aim` does this fine.

I'm suspicious that somehow `EE_Gateway::set_settings()`, which sets these properties, isn't get called. I'd suggest adding some debug lines in there (like `echo "got to this line!"; die;`) to make sure that's being called, and make sure the `$settings_array` has your extra inputs in it too.

It's also possible you're trying to use those properties before they're set. Where are you trying to use them from?

**Comment by archergod** [comment]
Thanks your guidance again help me find the issue. I accidently broke the set_settings when searching and that was causing the issue.

**Comment by mnelson4** [comment]
aha. Good find!
