### ISSUE TITLE
2022 theme: "Display Venue Details" option for the Event listing page is not reflecting in the frontend

### ISSUE THREAD

**Issue by Saam01** [eventespresso/event-espresso-core#3873]
When we activate the option to show "Display Venue Details" and "Display Ticket Selector" option for the Event listing page under EE > Events > Templates, it is not showing the venue and other options.

https://user-images.githubusercontent.com/99984614/172168837-91f0c674-b64d-4d5d-9909-64b643799a09.mp4

**Environment:**
 - Version of Event Espresso: 4.10.31.rc.003 
 - Version of WordPress: 6.0
 - Browser: Chrome 
 - PHP Version: 7.4.1

**Comment by tn3rb** [comment]
@hoseinrafiei && @majidabbasi96 

Can you guys take a look at this issue and see if you can figure out an easy fix for it?
I've messed around with it but can not figure out an easy solution.

You'll want to look at `modules/events_archive/EED_Events_Archive.module.php` as that is the logic that hooks into non-block enabled themes to inject our logic. If it look overly complex, it's because the events list shortcode shares the same logic.
