### ISSUE TITLE
Is it possible to set the currency per gateway, or filter the price per gateway?

### ISSUE THREAD

**Issue by freeLinden** [eventespresso/event-espresso-core#4100]
Is it possible to set the currency per gateway, or filter the price per gateway.
I have a client requesting this feature.

I have tried filtering the line items, but this method updates the price for all payment gateways.

**Comment by tn3rb** [comment]
Hi @freeLinden 

Can you please elaborate on what it is you need to acheive? There just isn't enough detail in your comment for me to give you a solid answer.

That said, and based solely on the limited info you _have_ provided, I'm going to say "no" because to do what i _think_ you want would require us to store gateway and currency info with every single payment amount throughout the system, including adding a ton of fields to database tables.

I'm going to have a quick look through the code and see if I can think of a solution while waiting for more details from you.

**Comment by tn3rb** [comment]
So after a quick look through the code, what _might_ work for you (at least as a starting point) would be to add a filter to the payment details used to create a payment object in `EE_PMT_Base::process_payment()`. This would give you access to:

- the transaction and all of its info
- the payment amount which you could modify prior to actual payment
- ALL of the payment gateway's details since this method is on the base class that all payment methods inherit from.

This would allow you to:

- modify the payment amount prior to the actual payment attempt via the gateway
- modify the existing line items created for the transaction (via `EE_Transaction::total_line_item()`) so that you can correct the amount already recorded
- modify each registration's share of the transaction total

What this _won't_ let you do is:

- control the display of currency info for this particular payment everywhere throughout the UI. As stated earlier, this would require having to record the currency alongside every money value throughout the entire database. So i'm not sure if there will be any viable solution for you with regards to that.

**Comment by freeLinden** [comment]
Thank you so much for your reply. So if I were to filter EE_PMT_Base::process_payment() I can filter the payment amount per gateway? Can you please point me to the filter for EE_PMT_Base::process_payment()

I would prefer not to edit the line items as this can be confusing for the customer if I cannot update the currency code, and they may wonder why the change of price displayed?

Also, would this be an issue:
"You can't simply change the price charged within the payment method itself as when EE confirms the payment the value won't match so within the EE_Transaction it will show up as either an over or underpayment."

Thanks for your help.
