### ISSUE TITLE
Feature Request - Show the number of availiable/remaining seats within the Event Overview.

### ISSUE THREAD

**Issue by sethshoultes** [eventespresso/event-espresso-core#430]
Codebase https://events.codebasehq.com/projects/event-espresso/tickets/7582

Requested here :- http://eventespresso.com/topic/feature-request-number-of-availiableremaining-seats/

Right now we show the amount of approve registration on the event overview, is it possible to show the remaining available spaces?

I think that this could be different values depending on how you have the event set up, (Datetimes Limits vs Ticket Limits) so not sure if this is practical, but thought it worth asking.

**Comment by nerrad** [comment]
@sethshoultes you could get feedback from @tn3rb on this, but if you'e asking for this number to be shown in the event list table I think it will _dramatically_ slow down the loading of the Event List table because of the calculations involved (plus that amount of slowdown could vary significantly depending on how events are setup).  It also sounds like from this statement you're not sure what the final ui should look like: 

> I think that this could be different values depending on how you have the event set up, (Datetimes Limits vs Ticket Limits) so not sure if this is practical, but thought it worth asking.

At a minimum, I think:

* [ ] We should do a test with a simple ui (not worrying about looks initially) to see if my slowdown guess is correct (maybe get some feedback on Brent on what he thinks about my assessment as well?) - this could require an investment of about 1 hour to just inject the raw number and then take benchmarks.
* [ ] If the decision is to go ahead, then some planning needs to happen to figure out how this will be implemented in the ui
