### ISSUE TITLE
add a flag to indicate that a registration is in process

### ISSUE THREAD

**Issue by sethshoultes** [eventespresso/event-espresso-core#440]
Original Codebase ticket https://events.codebasehq.com/projects/event-espresso/tickets/4978
See also https://events.codebasehq.com/projects/event-espresso/tickets/5048

Per @nerrad 
Something like this would be saved:

   $transient_name = 'reg_in_process_13`;
   add_transient( $transient_name, true, 60*5 );

Should be saved as a transient that expires after 5 minutes?  or 10?  whatever we think is needed for registrants to complete their registration (my example is 5 minutes).

The transient name is what the admin will look for using the heartbeat api and the number in the name is the evt_id.   for the following reasons: 

1. any registration will simply update the transient for the existing reg in the process for events in the cart and the timer will always be updated accordingly.
2. Admin just has to look for a transient matching the id of the event (or ANY transients matching 'reg_in_process').

####Why do this? 
Because its the easiest way for the admin to give feedback to event managers when they are editing an event that there is a registration happening and it might not be a good idea to update the event.  I can also put a useful indicator right in the Event List table when an event is experiencing registrations (and down the road even update reg counts LIVE) via the heartbeat api.

Initially I'll just do this when an event being edited that is published and add the other stuff down the road.

**Comment by nerrad** [comment]
Just adding notes.  I'm not sure we'll want to use transients for this unless it ends up that it'll be okay if the transient gets deleted prematurely (i.e. before the expiry time).  So, worded differently, if we _depend_ on the transient to be _reliable_, then we should not use a transient and we should use an option or some other mechanism (maybe extra_meta attached to the registration).

**Comment by joshfeck** [comment]
Updated the title because we definitely do not want to use a transient to do this.

**Comment by joshfeck** [comment]
I think [4990](https://events.codebasehq.com/projects/event-espresso/tickets/4990) has been sufficient for this. Also, since the time when original ticket was created, we've added the reserved counts to the ticket/datetime editor. So if the event manager wanted to be sure there wasn't any registrations in progress, they could check those first, then put the event into draft.

Along with the above, I did a few tests to see what would happen if I edited an event while a registration was in progress and found there were no errors and everything "just worked". For example if I edit a ticket price while a registration is already in progress for that ticket, the original ticket price (as expected) is used at checkout.
