### ISSUE TITLE
x_currency_code and Authorize.net AIM

### ISSUE THREAD

**Issue by lorenzocaum** [eventespresso/event-espresso-core#579]
In the Authorize.net AIM payment gateway, I saw a few currencies like these:

AUD, USD, CAD, EUR, GBP, or NZD.

However, when testing, I don't see the x_currency_code parameter in use in the logs but I do see others: https://cl.ly/3P2T2M233Q0q

From this doc (https://www.authorize.net/content/dam/authorize/documents/AIM_guide.pdf), you can use x_currency_code to accept payments in another currency even if your merchant account has a default set. For example, you can have a default of USD on the merchant account and then you should be able to use the parameter to accept payments in another currency like EUR.

What happens right now (assuming your Authorize.net account is set to USD) is that if your site is set to a country in Europe, then you'll see Euros for the currency but then Authorize.net will run the transaction in the default currency of USD.

**Comment by sethshoultes** [comment]
@knazart or @mnelson4 thoughts on this issue?

**Comment by mnelson4** [comment]
yeah good point @lorenzocaum. I just checked the code and we're definetely not sending the currency code to AIM, or Authnet Accept actually. I think we've gotten by because most people set the same currency on their Authorize.net account as what's in EE. But if someone set that incorrectly, it would really stink if they're getting paid in the wrong currency!
So ya, I think we should address this, and it should be plenty easy to pass the currency code along.
But before we jump in and fix this, I should ask: could any site owners be relying on the current behaviour? Eg, their Authnet account is in Euros, but their site's location is still set to the default USA location, and they've just changed USA's currency code to €: so they're expecting to be paid in Euros and they currently are, and when we make this change they'll suddenly start getting paid in USD.
IMO this situation is possible, but it's probably still best to make this fix.

**Comment by lorenzocaum** [comment]
That scenario is a possibility but I think the occurrence would be low as compared to most event organizers that expect the currency to be consistent with the selected country by default.

Using the currency that is linked to the base of operations through the general settings page would likely be the best choice for most event organizers.

@Pebblo Could you share a recommendation here for how we determine the currency to use?

**Comment by knazart** [comment]
Yeah, not sending a currency in this situation is a no-no. But in the DOCs the `x_currency_code` parameter is marked as optional and that makes me remember that some gateways we encountered along the way, in fact, didn't allow to override/change the default (set in the merchant account) currency when creating a transaction through the API. I am not sure that this is the case here, but there is a possibility that this parameter was added/updated after this gateway was developed.

We might also want to look at the API we use here because looking at the docs it might be the deprecated one.

**Comment by lorenzocaum** [comment]
@sethshoultes could you triage this please? It is a blocker for someone using ES. Thanks

**Comment by sethshoultes** [comment]
Ya, it's already in the 'Next' pipeline

**Comment by knazart** [comment]
So I guess this is the gateway I mentioned above, the one that didn't allow to change the currency through the API to anything other then set as default in the account.

But adding the currency parameter should help anyways, because of this:
> If you are setup with a GBP Authorize.Net Payment Gateway account and a GBP merchant account and you are sending a different currency code other than GBP, you will get an error.

That should help prevent incorrect currency payments and allow to debug the issue.

Another maybe possible idea is to add some notification on settings form (on a validation or load action) about the not matching currencies. That is if their API allows to get the account currency setting.

**Comment by mnelson4** [comment]
merged the PR into master.
For the record, folks can't use multiple currencies with Authnet. All we could do is have an error if their Authnet account's currency doesn't match the currency of EE
