### ISSUE TITLE
Add UI to add new registrations via the EE Contacts admin

### ISSUE THREAD

**Issue by joshfeck** [eventespresso/event-espresso-core#659]
This is a feature request to add a “add new registration” feature to the EE Contact record page. 

We could reuse the attendee mover add-on's select event UI, then progress on to the regular EE admin SPCO steps.
The possible workflow steps would be: (edited)

1) a) From a single contact record admin page click an "Add new registration"
or b) from the contact list table click a new icon that links to a "Add new registration" action, similar to how we initiate an Attendee mover action from the Registration list table.
2) Select the event, submit
3) Select ticket(s) (could be the same as the current admin ticket selector
4) On the attendee information step where the fields will be auto populated from the contact record

This could be built as a new feature for the Attendee Mover add-on, in which case that might be best re-branded as the "Attendee Manager" add-on.

**Comment by tn3rb** [comment]
## questions

> re: from the contact list table check some boxes and select a "Add new registration" action

**How should tickets be assigned to those contacts (or how should contacts be assigned to those tickets) ?**

for example, if you select 4 contacts from the contact list and then after choosing an event you are presented with a Ticket Selector that has two ticket options, and you choose 2 of each, which contacts get assigned to which tickets? How would the UI for doing that look?

One way would be to use the `'FHEE__EEH_Form_Fields__generate_question_groups_html__before_question_group_questions'` filter hook to add some checkboxes before the first question group for seelcting which contact to use for the attendee info for that registration, ie:

![add registration for contact ui](https://user-images.githubusercontent.com/1751030/46698946-3b64dc00-cbcd-11e8-9bd3-4b7b0c98fc69.png)

then use some JS to copy the contact details from some hidden inputs into the visible inputs.

But you may have had something else in mind...

(i used the following code to generate the above mockup:
```php
        add_filter(
            'FHEE__EEH_Form_Fields__generate_question_groups_html__before_question_group_questions',
            function($html, $registration, $question_group, $reg_step) {
                $html .= '
            <tr>
				<th scope="row">
					<label class=" ee-reg-qstn" for="contact">Use contact information for</label>
				</th>
				<td>
				    <div style="display:inline-block; width:150px;">
                        <label for="contact-1">
                            <input type="checkbox" id="contact-1" label="checkboxes" value="1">John Doe
                        </label>
                    </div>
				    <div style="display:inline-block; width:150px;">
                        <label for="contact-1">
                            <input type="checkbox" id="contact-2" label="checkboxes" value="2">Jane Doe
                        </label>
                    </div>
				    <div style="display:inline-block; width:150px;">
                        <label for="contact-1">
                            <input type="checkbox" id="contact-3" label="checkboxes" value="3">Joe Schmoe
                        </label>
                    </div>
				</td>
			</tr>
';
                return $html;
            },
            10, 4
        );
```
)

## comments

> re: We could reuse the attendee mover add-on's select event UI, then progress on to the regular EE admin SPCO steps.

in order to reuse `EventEspresso\AttendeeMover\form\SelectEvent` we would have to make some modifications to it as well as some other classes, but it would be  easier (albeit slightly less DRY) to modify a copy of that class in order to customize it for this new purpose.

> re: This could be built as a new feature for the Attendee Mover add-on, in which case that might be best re-branded as the "Attendee Manager" add-on

I think that's a great idea and love the new name. We would want someone to invest some time in handling the necessary redirects and SEO changes required for renaming any web site pages that currently deal with the term "Attendee Mover" but that is an issue for another repo.


## estimates

Here's the various tasks I see needing to be done for an MVP and the time estimates for each

- (2 hours) copy `EventEspresso\AttendeeMover\form\SelectEvent` to new class and modify to process selection and then redirect to `admin.php?page=espresso_registrations&action=new_registration&event_id=###&contacts=1-2-3-4`.
- (2-3 hours) add a new admin page for displaying the above form for selecting the event to add registrations to
OR
- (2-3 hours) add logic for generating a modal window for displaying the above form
- (1 hour) inject an "Add New Registration" button to the bottom of the "Registrations for this Contact" meta box on the Contact CPT editor that either:
    - immediately redirects to a new admin page for selecting the event to add registrations to
    - OR displays modal window for doing so
- (1 hour) add an "actions" column to the "Contact List" admin list table and populate with an icon/button for doing the same as the above point
- (1 hour) add logic to the first step of the add new registration process in the admin for capturing the `contacts=1-2-3-4` query param and injecting in to the query params passed to the second step
- (4 hours) assuming the UI mockup displayed earlier is sufficient, hook into the `'FHEE__EEH_Form_Fields__generate_question_groups_html__before_question_group_questions'` filter and display a set of checkboxes for associating each registration with one of the contacts passed via the query params. Contact details need to be retrieved from the db and saved to hidden inputs in the form or similar structure.
- (4 hours) load javascript during the above step that copies hidden contact details into the corresponding attendee info question inputs. An icon/link should be added for clearing the same fields populated by the above process.

Total (generous) estimate for the above: 2 days (15-16 hours) which does not include time for code review, testing,  and/or additional communications required to complete the work.

**Comment by joshfeck** [comment]
Maybe for step 1, the options could be:
a) From a single contact record admin page click an "Add new registration"
or b) from the contact list table click a new icon that links to a "Add new registration" action, similar to how we initiate an Attendee mover action from the Registration list table.

**Comment by tn3rb** [comment]
that would make the last two steps unnecessary, so we can shave 8 hours (50%) off of the time estimate

**Comment by joshfeck** [comment]
A very similar customer request that was reported in codebase:

> The current way to manually register an existing contact is very tedious and error prone. I would like to request a more streamlined way:
1) Under the Event Espresso main menu, have a top level item named “Contacts”. Clicking on this should display a list of contacts, organized by First Name, Last Name and Email address.
2) To the right of each contact should be a button called Register. If I click on this:
a) The system should identify all events and times that are still open and available for registration. Past events should not be displayed. Future events that are sold out may be hidden or displayed but grayed out.
b) Present a single long list of all eligible events and times. Allow me to select one of them.
c) After selecting one of them and clicking on Continue or Register Now, the contact first name, last name and email will be used to register the contact for the select event and time.
> This will be much faster and less error prone than the current method, which involves copying and pasting the contact’s first name, last name and email into the manual registration form.

From: https://eventespresso.com/topic/request-a-streamlined-way-to-create-manual-registrations-for-existing-contacts/

**Comment by joshfeck** [comment]
Updated estimates follow (based on Brent's above estimate, with an adjusted scope of only allowing a single contact via this feature)

## estimates

- (2 hours) copy `EventEspresso\AttendeeMover\form\SelectEvent` to new class and modify to process selection and then redirect to `admin.php?page=espresso_registrations&action=new_registration&event_id=###&contacts=1`.
- (2-3 hours) add a new admin page for displaying the above form for selecting the event to add registrations to
OR
- (2-3 hours) add logic for generating a modal window for displaying the above form
- (1 hour) inject an "Add New Registration" button to the bottom of the "Registrations for this Contact" meta box on the Contact CPT editor that either:
    - immediately redirects to a new admin page for selecting the event to add registrations to
    - OR displays modal window for doing so
- (1 hour) add an "actions" column to the "Contact List" admin list table and populate with an icon/button for doing the same as the above point
- (1 hour) add logic to the first step of the add new registration process in the admin for capturing the `contacts=1` query param and injecting in to the query params passed to the second step


Total (generous) estimate for the above: 2 days which does not include time for code review, testing,  and/or additional communications required to complete the work.
