### ISSUE TITLE
Fix admin event list table orderby sorting when events have multiple datetimes

### ISSUE THREAD

**Issue by joshfeck** [eventespresso/event-espresso-core#678]
**Describe the bug**

When an event has more than one datetime, the admin event list table can display the events & start dates in an inconsistent way when using the order by start date feature. 

What happens is the _next upcoming datetime_ is displayed in the Start Date column, but the orderby sorting uses a different datetime set in the event.
**To Reproduce**
Example 1: An event with one datetime in the past and one datetime in the future will display the future date, but the orderby uses the past date. In this example the first datetime is 08/16/2018 and the future datetime is 02/08/2019.
So 02/08/2019 is displayed as the start date in the event list, but the event is placed in order between events in April 2018 and August 31 2018. 

Example 2: An event with its first datetime in the far future and its second datetime is upcoming, but closer to the current date. In this example the first entered datetime is 03/31/2019 and its second entered datetime is 10/26/2018. 
The 10/26/2018 start date is displayed in the event list, but the event is placed first in the list because it's using the 3/31/2019 date in the query.

**Expected behavior**

The expected behavior is the sorting of events by dates should be consistent with the date that's displayed. 

### Screenshots

**Example 1**
![screen shot 2018-08-31 at 10 16 20 am](https://user-images.githubusercontent.com/891156/44918986-53158e80-ad0a-11e8-809c-01e721e05b8f.png)
**Example 2**
![screen shot 2018-08-31 at 10 31 31 am](https://user-images.githubusercontent.com/891156/44919496-a76d3e00-ad0b-11e8-97d3-0f1d46ce7f54.png)

**Additional context**
ee4m site's admin event list table URL, with orderby params:
https://ee4m.eventespresso.com/wp-admin/admin.php?page=espresso_events&orderby=Datetime.DTT_EVT_start&order=desc

**Comment by joshfeck** [comment]
Another solution to this would be to display a date range in that column so the very first datetime will still be displayed (even if expired).

**Comment by joshfeck** [comment]
We're mostly concerned with example 1 (where the first datetime is used for the sort order, but the date that's displayed is the next upcoming datetime).

It seems we have two options to fix this:
1) Just display the next upcoming datetime so the sort matches what's displayed
2) Display a range of dates (e.g. {first datetime - last datetime)

If we go with option 1, it may also be helpful to add some type of indication that there are other datetimes for the event (before or after the display date).

If either option would involve similar effort/time then I lean towards option 1.

**Comment by raphaelkross** [comment]
@joshfeck @tn3rb  I agree with going with option 1, where we display the next upcoming datetime and then a kind of indicator

**Comment by tn3rb** [comment]
@joshfeck 

This ended up being more complex because of the way things are set up.

Basically the query that populates the list table is doing one thing, and then the "Event Start" column is doing its own thing, completely separate from the main query. The disconnect between the sorting and what's displayed in the "Event Start" column is because the sorting is handled by the query itself (ie: happening within the actual database) whereas the "Event Start" column is being populated after running additional queries to retrieve the next upcoming (or currently active) datetime.

So as is, there is NO really straight forward way to do this and not cause side effects. The only way that I can think of actually maintaining the existing results but ONLY modifying the sorting would require having to loop over the results and perform even more queries in order to re-sort the array of events before sending that off to the list table to display. I don't think this is a good solution at all though because it will unnecessarily slow down that page and will also quite likely be fragile (ie: buggy). 

I can explain what I think the mechanics for doing this would be, but again, I don't think it's a good path to go down.

Here's some alternate ideas:

#### Option A) your option 2 from above

- keep the query as is, which (unless other filters are employed) shows Active AND Inactive events/dates
- rename the "Event Start" column to something like "Event Dates" and display a date range (ie: first -> last)
&nbsp;
- PROS:
    - does not affect existing query results or sorting
    - not too too difficult
    - dates displayed would now appear chronologically correct (kinda sorta) but only uses very first date
- CONS
    - messes with the dates displayed (in a bad way imho) and adds extra data/text to the table (more noise)
    - sorting does not change but is also not improved in any way
    - could be jarring since it could make it impossible to determine which events are active or soon to be active
    - requires extra queries (need to get first AND last dates for each event)

&nbsp;
#### Option B) change the default status filter to "Show Active/Upcoming" dates instead of "Show Active/Inactive"

- as the title says, rename the filter option from "Show Active/Inactive" to "Show Active/Upcoming"
- filter expired dates out of the query results by default so **only** events with active or upcoming dates will appear in the event list
- possibly display discrete notice above/below list table to indicate that expired dates are being filtered and to use the "Expired" status filter to view those events
&nbsp;
- PROS:
    - might be faster because expired events will be filtered out by default so less results are returned
    - might not be too too difficult to achieve
    - dates displayed would now appear chronologically correct
    - no longer have to look at old expired events (also listed as a CON - depends on user)
- CONS
    - affects existing query results (in a good way imho but still a change)
    - may possibly still affect the dates displayed (may not but I'm not 100% certain at this point) and may require extra work to ensure that the displayed dates are synced properly with dates the query is using for sorting
    - have to use status filter to view old expired events (also listed as a PRO - depends on user)
    - could be jarring since expired dates are suddenly missing from list table

&nbsp;
#### Option C) change the default status filter to "Show Recent/Active/Upcoming" dates instead of "Show Active/Inactive"

- similar to **Option B** but rename the filter option to "Show Recent/Active/Upcoming"
- filter out dates that are **more** than 30 days expired from the query results by default so **only** events with active or upcoming dates, or ones that are recently expired will appear in the event list
- possibly display discrete notice above/below list table to indicate that expired dates are being filtered and to use the "Expired" status filter to view those events
&nbsp;
- PROS:
    - most of the PROS of Option B (faster, chronologically correct, less expired dates)
    - still shows recently expired events instead of them disappearing the instant they are over, which would greatly help admins that need to edit events just after they have ended and would be less jarring of a change
- CONS
    - most of the CONS of Option B
    - will require modifying both the query AND the logic that displays the date in the "Event Start" column



thoughts? other ideas?

My personal preference is leaning towards Option C because I think it would be the most usable for admins.

**Comment by joshfeck** [comment]
How about we leave the query and default status filter the same, and keep the display mostly the same, but instead of showing just the next upcoming datetime, we append the first datetime.

So in the example 1 above, prior to Feb 8, the column would display something like this:
First: Aug 16 2018 
Next: Feb 8 2019

Then, after Feb 8, if there are more datetimes in the future, that next datetime would be displayed.

Then after that, if no more datetimes, the word "Last" will replace: "Next".

**Comment by sethshoultes** [comment]
@joshfeck I like that idea.

**Comment by raphaelkross** [comment]
@joshfeck yeah - this would not break the current sort by start date and will make send on the UI, since the user will be able to clearly the information.

**Comment by tn3rb** [comment]
oops... sry for not responding... ya I think your suggestion sounds great Josh 👍
