### ISSUE TITLE
Add filter hook to allow overriding batch size limit

### ISSUE THREAD

**Issue by joshfeck** [eventespresso/event-espresso-core#701]
I was working on a customer's site today where one of their issues was they could not download the CSV registration report. What happened was there were over 3000 registrations and when the report tool got to about the 10th batch, it threw an error and stopped.

![screen shot 2018-09-21 at 9 53 07 am](https://user-images.githubusercontent.com/891156/45888310-ba63b300-bd8b-11e8-9b71-2463245cd365.png)

So I FTP'd in and changed the $batch_size to 350 (change made directly to core) and that allowed the report to complete as expected. They'll lose this mod when they update of course.

Since it's a zero-impact change to add some filter hooks can we do that?

**Comment by sethshoultes** [comment]
@mnelson4 any issues with adding a filter, as Josh recommends?

@joshfeck is that something you can add or would you prefer that Mike adds it?

**Comment by mnelson4** [comment]
Yeah we could add a filter, although there is currently the constant `EE_BATCHRUNNER_BATCH_SIZE` you can use (see https://github.com/eventespresso/event-espresso-core/blob/master/core/libraries/batch/BatchRequestProcessor.php#L100). If you think a filter would still be helpful, I'd be inclined to filter that value there too.

(And I'm puzzled about the exact problem you had there, because usually lowering the limit fixes the migrations, not increasing it :confused:. If you see something like that again, feel free to make a ticket because maybe there's a more general fix possible.)

**Comment by joshfeck** [comment]
I think it's a server config issue where it wasn't allowing more than 10 writes to the temp file in one go. 

Anyway I'll close this as I forgot about the EE_BATCHRUNNER_BATCH_SIZE constant.
