### ISSUE TITLE
Investigate usages of `static` keyword used for variables inside class methods for potential problems

### ISSUE THREAD

**Issue by nerrad** [eventespresso/event-espresso-core#710]
**Describe the bug**

This may or may not a potential bug, this issue is created to document potential problematic usage of the `static` keyword in our codebase and present the opportunity to investigate whether they actually do cause problems.

When the `static` keyword is used along with variable definitions within class methods (static or otherwise), the value set persists across any instance of that class method.  So it's a potential gotcha when that behaviour is not recognized in any code.  I searched through our codebase to see any usages of the `static $something;` pattern to find places we might need to investigate further.

**Note: I've only included findings in this table for things it's not immediately clear there is a problem or not.  I chose not to include usages where there's only ever expected to be one instance of the class around anyways (such as in `EE_Admin::filter_plugin_actions`).

| Class and method | Notes |
|-----------|------------|
`EE_Admin_List_Table::_get_row_class` | Unlikely to be a significant problem because usually there's only one list table in a view. Even with multiple list tables the behaviour here will probably be what is desired anyways.
`EEH_HTML_Helper::indent` | I don't think this would be problematic as its sole purpose is to set a default if its never been set before
`EEH_DTT_Helper::get_timezone_string_for_display` | I think this may have the potential for being problematic in a multi-lingual environment where users might switch between languages in the _same_ view.  However, I think that's unlikely that the same view will be content in multiple languages (more likely that each language would be setup on its own request)
`EEH_DTT_Helper::wp_timezone_choice` | This is used as a cache of sorts for the loaded request so I don't think usage here is problematic.
`EEH_Line_Item::calculate_final_price_for_ticket_line_item` | This one looks potentially problematic to me, however I'm not immediately aware of how this method is used so can't say for sure. 

@mnelson4 and @tn3rb, out of the places I discovered in my code search the only one I'm kinda uncertain on is the last one.  I think it'd be good if each of you review these places and add any feedback you have as well.  I'll be happy if we're able to close this issue without any code changes but it'd be good if this exposes potential cause for bugs that may have eluded us.

**Comment by mnelson4** [comment]
yeah `EEH_Line_Item::calculate_final_price_for_ticket_line_item` looks like a potential for bugs, because `$final_prices_per_ticket_line_item` is created based on a specific total line item. It's possible we could call this function again using a different total line item. (Although this hasn't bitten us yet because there's usually just one total line item per normal web request. So this would be more likely to expose itself in unit tests or bulk REST API requests etc).

**Comment by tn3rb** [comment]
I agree that `EEH_Line_Item::calculate_final_price_for_ticket_line_item` looks like it could potentially cause problems but I'm pretty sure we would have noticed since it would be totally obvious

**Comment by mnelson4** [comment]
> I agree that EEH_Line_Item::calculate_final_price_for_ticket_line_item looks like it could potentially cause problems but I'm pretty sure we would have noticed since it would be totally obvious

Yeah it hasn't caused problems yet because the situation where it would have a problem doesn't arise normally (it would basically require having multiple carts and some price modifiers that only apply to one cart but not the other).

If we don't want to embark on changing that function, maybe we should just put a comment on it pointing out that if that method will probably have problems if used for different total line items during the same request.

**Comment by mnelson4** [comment]
I think it's good to be aware of this, and this could potentially be a gotcha, but we haven't seen any immediate problems. Fixing the one iffy spot would probably be an hour or two, plus an hour-or-two of testing, and adding an automated test would be good.
My vote is to pass this off to Seth for triage.

**Comment by nerrad** [comment]
Thanks for leaving your comments guys, so it sounds like this isn't an urgent thing (fortunately!).  Assigning to you for triage Seth but its likely low priority and can maybe go in the Icebox.
