### ISSUE TITLE
Custom offsite payment method

### ISSUE THREAD

**Issue by megabait1212** [eventespresso/event-espresso-core#72]
We created custom offsite payment method. It’s working only when user return on the website after payment, but if user payed and didn’t return to the website then for payment and transaction status is abandoned. Developer manual https://developers.paysera.com/en/payments/current#integration-via-library. 
code ex.
public function handle_payment_update($update_info, $transaction) {
        $payment = $transaction instanceof EEI_Transaction ? $transaction->last_payment() : NULL;
        
        if ($payment && $payment instanceof EEI_Payment) {
            $response = WebToPay::checkResponse($update_info, array(
                        'projectid' => $this->_projectid,
                        'sign_password' => $this->_password,
            ));

            if ($response['status'] == 0) {
                $payment->set_status($this->_pay_model->declined_status());
                $payment->set_gateway_response(__('Payment has no been executed', 'event_espresso'));
                $payment->set_txn_id_chq_nmbr($response['orderid'] . '/' . $response['requestid']);
            } elseif ($response['status'] == 1) {
                $payment->set_status($this->_pay_model->approved_status());
                $payment->set_gateway_response(__('Your payment is approved.', 'event_espresso'));
                $payment->set_txn_id_chq_nmbr($response['orderid'] . '/' . $response['requestid']);
            } else {
                $payment->set_gateway_response(__('Your payment has been declined.', 'event_espresso'));
                $payment->set_details($response);
                $payment->set_txn_id_chq_nmbr($response['orderid'] . '/' . $response['requestid']);
                $payment->set_status($this->_pay_model->declined_status()); 
            }

            if (isset($_REQUEST['ee_payment_method']) && $_REQUEST['ee_payment_method'] == 'paysera_payment_method') {
                @ob_clean();
                header('HTTP/1.1 200 OK');
                exit('OK');
            }

            return $payment;
        } else {
            throw new EE_Error(sprintf(__("Could not find payment for transaction %s", 'event_espresso'), $transaction->ID()));
        }
    }
How to change registration and transaction status if user doesn’t return back? How can I trigger update methods for registration and transaction status when payment gateway visit callback url and what are these update methods? I think main problem in handle_payment_update method. I hope you can give me right direction.
Josh from support recommended me next "I can advise looking through the PayPal_Standard gateway and how it interacts with SPCO. It updates the transaction after so many minutes if the payer doesn’t return to the site by means of a wp cron, which is exactly what you’re looking to do." How to setup interaction with SPCO? Thank you

**Comment by mnelson4** [comment]
I'm not very familiar with Paysera, but it sounds like they send you payment notification information on both the "Accept URL" (the URL the user is redirected to after a succcessful payment) AND the "Callback URL" (the URL Paysera sends a payment request to when a payment is made).

This is very similar to Paypal Standard: Paypal sends a payment notificaiton (IPN) to the EE transactions page, but they also send payment data along with the redirection.

First, you should make sure you have set your Payment gateway class to receive separate IPNs (like documented here: http://developer.eventespresso.com/docs/ee4-payment-method-development/#handle_payment_update) by setting `$this->_uses_separate_IPN_request=true;` in your gateway class' constructor. Like with Paypal, this means your gateway WON'T process payment data when the user returns to your site, but will instead only process payment information when Paysera sends information in their IPN sent to the "callback url". This is actually preferred, because otherwise users could receive duplicate email notifications when their payment is processed on both the IPN AND the return to EE.

It looks like when an IPN is received, the payment object is getting updated correctly, but NOT getting saved before you send back the response and exit. Your `handle_payment_update()` method needs to return the payment object back to `EE_Payment_Processor` so it has a chance to save the payment, update the transaction, and send notifications.
So you should instead have code like this:

```
public function handle_payment_update($update_info, $transaction) {
 ...
 if (isset($_REQUEST['ee_payment_method']) && $_REQUEST['ee_payment_method'] == 'paysera_payment_method') {
          //don't exit yet because EE_Payment_Processor still needs to process the payment data
          //but setup a filter so we will exit and send back the response Paysera needs
          add_filter( 'FHEE__EES_Espresso_Txn_Page__run__exit', array( $this, 'send_ok' );
        }
return $payment;
}
//sends back OK to paysera upon receipt of an IPN and informs the transaction page shortcode to exit
function send_ok() {
    echo "OK";
    return true;
}
```
you'll find the filter used defined in event-espresso-core/shortcodes/espresso_txn_page/EES_Espresso_Txn_Page.shortcode.php around line 97

And if your payment integration goes well, let us know: we'd like to list it among other 3rd party devs' work. See "What's next" here: https://eventespresso.com/2015/03/developers-guide-to-payment-methods-for-event-espresso-4-6/

**Comment by mnelson4** [comment]
Sorry the documentation on https://eventespresso.com/2015/03/developers-guide-to-payment-methods-for-event-espresso-4-6/ didn't explain this so I've updated it

**Comment by megabait1212** [comment]
Thank you

**Comment by mnelson4** [comment]
kk let us know if you have more questions or how we could make this an easier experience for you!

**Comment by megabait1212** [comment]
I spent 2 days trying to fix this problem. I am very very grateful to you for your help. Thank you very much.

**Comment by megabait1212** [comment]
Also I am writing here some improvements because I don't know where to write them
1) In Lithuania from 1 january national currency is euro
2) It's will be good to implement search by TXN ID. Like in my case we got payment from paypal and payer email and name is different from ticket registrant, how to find ticket registrant? Only export to csv can help. Searching plugins doesn't work like Relevanssi or Search Everything

**Comment by mnelson4** [comment]
Those both sound like good points.
They would probably be best submitted to our support forum (
https://eventespresso.com/support/forums/) as separate items, because the
support guys will be more aware whether those features have been previously
requested and can help prioritize them best. Would you mind doing that?
