### ISSUE TITLE
Ability to add registrations in the admin after event is expired

### ISSUE THREAD

**Issue by sethshoultes** [eventespresso/event-espresso-core#731]
See Codebase tickets:
https://events.codebasehq.com/projects/event-espresso/tickets/7227
https://events.codebasehq.com/projects/event-espresso/tickets/8509

Grinder Discussion:
http://p2.eventespresso.com/2014/12/18/adding-registrations-in-the-admin-after-event-is-expired/

If a ticket expires, it also expires in both admin and front end. Many customers are requesting thatr the ticket should remain open in the admin (but expired front end) so any manually added attendees can be applied to that (expired) ticket.

**Comment by tn3rb** [comment]
setting estimate at easy for the time being, but won't know until this is investigated.
it's possible this could be more convoluted if overriding expired entities needs to "trickle down" through a ton of code

**Comment by joshfeck** [comment]
See also #892

**Comment by joshfeck** [comment]
Currently in order to add a registration to an event after it's expired you need to:

1) Go in and edit the event and either change the datetime or add a new datetime so the event is no longer expired
2) edit the ticket sale end date to today or later
3) then add the registrations
4) Go back edit the event and remove/change the end date back

We'd like to change this so all they'd need to do is add the registrations, they won't need to edit ticket sale end dates or edit datetimes.

**Comment by joshfeck** [comment]
Here's how I see things working:
- [ ] The issue reported in #892 should get fixed first and it its own PR
- [ ] No changes to the front end, the only changes will happen in the admin
- [ ] If a ticket sale date is past, the event admin will continue to be able to select that ticket 
- [ ] If the last datetime's end date is past, the event admin will continue to be able to select tickets for that event using the ticket selector in the admin
- [ ] No changes to the the admin ticket selector's behavior if tickets are sold out, one day we might add support for the admin side within the wait list add-on

**Comment by joshfeck** [comment]
tracking additional requests for this feature:
https://eventespresso.com/topic/book-user-in-expire-event/
