### ISSUE TITLE
Import Functionality

### ISSUE THREAD

**Issue by amallory** [eventespresso/event-espresso-core#74]
Hello, 

Garth suggested I open an issue here and ask about importing data into EE. I have a client who has some data they would like to import into EE4 and I'm looking for info on how to accomplish this. I understand there are some issues with the current import and would like to get some insight into what the issues are with the goal of finding a work around and import this data for my client. 

Thanks

**Comment by mnelson4** [comment]
hi @amallory, where are you wanting to import the data from? From another install of EE4? If so we have a fix but it's been undergoing testing on-and-off for a few months now. You can checkout the branch here: https://github.com/eventespresso/event-espresso-core/tree/BUG-7537, but since it seems something has changed in master branch that's busted it. I'll let you know. But it would probably be very helpful if you could beta-test this branch to get it merged into master asap. Would you be willing to beta test it?

**Comment by amallory** [comment]
Hey, @mnelson4 thanks for getting back to me so quickly. The data is coming from a system called Your Membership... But it's reformatted it into a csv in the EE4 format. Thinking this will make the import a little more straight forward. I could run a test import under that branch to give it a test. So I guess the answer is yes will beta test it.

**Comment by mnelson4** [comment]
So the data is in the csv format that EE4 expects? Because EE3 had a different format. If it's in EE4's format then the importer should be able to handle it, once I've worked out this kink I just discovered

**Comment by mnelson4** [comment]
so @amallory, feel free to give the above-mentioned branch a whirl: it's in-sync with EE4 master, except re-added the buttons to export things (events, contacts, venues, etc) and to re-import them.
Here is a part of our testing checklist that we're trying to work through, if you can try some of these testcases and validate that they work for you (on a test site), then we'll be much closer to getting this branch into master branch and on an upcoming hotfix release. Before doing each test, you'll probably want to do a database backup so you can quickly restore to that backup if you need to test again.

- [ ] Create an event with a paid ticket, register for it, change the ticket's price, and export that event. Look in the exported CSV's data at the "Ticket" area. You should see that ticket in there just fine. When you import that csv file into another site there shouldn't be any errors.
- [ ] Create an event with a venue on a state and a country. Export that event and then import into a different site. Make sure you don't now have any duplicate states in your database, or duplicate questions or question groups
Do a normal registration for an event requesting state info. Try adding a new state. It should work fine.
- [ ] Do another normal registration for an event reqeusting state info. Try adding a state you know ALREADY EXISTS (ie, has the same abbreviation and is for the same country). There should be no error and you should be able to use that state just fine
Export an event. Open the CSV file you downloaded. Find the cell that same "MODEL NAME" and the next one says "Event". Change "Event" to "Monkey". Also find the cell that says "MODEL NAME" and the next one says "Datetime". Underneath there is a header row with a cell named "Datetime IDDTT_ID". Change that to "Thingy TOTALLY_WACK". Then import that CSV file. There should probably be errors, but no FATAL errors.
- [ ] On an event, add some post meta to it. Export that event. Then change the values of those post meta. Then re-import that event to the same site using the importer. The postmeta should be restored.
- [ ] On an event, change the message template used for invoice from "Global" to a custom one, maybe called "My Custom template". Then export that event. Then change that template somehow, maybe replacing the entire message template's body with "CHICKEN", and save it. Then change the message template for invoice BACK to "Global". Then re-import that event to the same site. It should now use "My Custom Template" again, but the template itself should still say "CHICKEN" (that is because when re-importing EVENTS, although we have access to related data like message templates, we favour what's already in the database if it exists)

**Comment by amallory** [comment]
@mnelson4, So my client decided not to move forward with this import which is most unfortunate. If I can find someone else who is looking to do an import I'll be happy to test this. Sorry I wasn't able to get to this in a timely manner.

**Comment by mnelson4** [comment]
yeah sorry to hear that. well let us know if you get a chance to do any of the above beta testing of the branch BUG-7537
