### ISSUE TITLE
EE template settings override my custom template code

### ISSUE THREAD

**Issue by jonathan-dejong** [eventespresso/event-espresso-core#75]
Hi.

I've posted an issue here: http://eventespresso.com/topic/disable-automatic-injektion-of-excerpts-and-buttons/#post-156805

But was instructed to make an issue on Github instead.

As it says in the topic above I'm having issues with EEs template settings overriding my own code on event categories archives. Strangely enough this does not occur on the base archive which uses the same theme template file. 

What happens is that my own template is being affected by the settings in EE templates. When I set the archive to show excerpts it adds it's own button on top of my own and the event contact. If I disable it by setting it to "none" it also hides my own the_excerpt function. Like I said it only happens on the event category archive pages, not the base. http://kfsk.se/blog/event-category/energi-och-klimat/

There's nothing strange about my loop as you can see below. Also, using the filter provided by Josh only completely disabled my excerpt on both archives. All in all it's a complete mess.. 

This is my loop: 

```
<?php while(have_posts()): the_post(); ?>
					<article <?php post_class('article-item clearfix'); ?> id="event-<?php echo get_the_ID(); ?>">
						<?php 
				        $datetime_string = espresso_event_date('Ymd', '', $post->EVT_ID, false);
				        $datetime_object = new DateTime($datetime_string);
				        $month = date_i18n('M', strtotime($datetime_string));
						?>
						<div class="post-date">
							<span class="date"><?php echo $datetime_object->format("d"); ?></span>
							<span class="month"><?php echo $month; ?></span>
							<span class="week">vecka <?php echo $datetime_object->format('W'); ?></span>
							<span class="year"><?php echo $datetime_object->format("Y"); ?></span>
						</div>
						<div class="postcontent">
							<header class="event-header">
								<h2><a href="<?php echo get_permalink(); ?>"><?php the_title(); ?></a></h2>
								<?php $categories = get_the_terms($post->ID, 'espresso_event_categories'); ?>
								<?php if(!empty($categories)): ?>
										<?php foreach($categories as $category): ?>
											<a href="<?php echo get_term_link($category->term_id, 'espresso_event_categories') ?>" data-icon="T" class="event-cats"><?php echo $category->name; ?></a>
										<?php endforeach; ?>
								<?php endif; ?>
								<?php $venue = espresso_venue_address('inline',$VNU_ID,false); ?>
								<?php if($venue): ?>
									<div data-icon="J" class="event-address"><?php echo $venue; ?></div>
								<?php endif; ?>
							</header>
							<div class="entry">
								<?php the_excerpt(); ?>
								<?php espresso_view_details_btn( $post ); ?>
							</div>
						</div>
					</article>
				<?php endwhile; ?>
				<?php custom_espresso_pagination(); ?>
```

**Comment by tn3rb** [comment]
Hi Jonathan,

So that is the loop from your archive-espresso_events.php template?

I'll give that a shot and see if I can recreate, but it might be best if you can either supply:

 * the complete code for the affected template (ie the full template, not just the loop)
 * or event better, access to your entire theme just in case there is some other filter somewhere you have set that is confusing EE and throwing things off

some of what EE does is a bit unorthodox because we are caught between trying to write code that works for both templates that directly implement the main query and shortcodes that are running an additional query inside the main loop.

**Comment by tn3rb** [comment]
try adding this in your functions.php:

```
add_action( 'loop_start', array( 'EED_Events_Archive', 'remove_all_events_archive_filters' ) );
```

**Comment by jonathan-dejong** [comment]
Hi Brent,

Yeah I looked through some of the code in EE regarding this and it seems a bit hacky at some places.. I get why tho :) 

That action seems to have done the trick for me! Thank you so much for that! Just in time for my meeting with the client too :) 

On a sidenote you guys should really work on a complete categorized list of actions and hooks available in EE. I find new ones every time. 

Thanks!

**Comment by nerrad** [comment]
Hey Jonathan, thanks for the suggestion regarding a categorized list of actions and filter hooks available in EE.  It's something that we likely won't take time to do because at last count (using search in my IDE) there are 484 occurrences of EE filters and 332 occurrences of EE actions.

One thing that *might* help you with discovery of our actions and filters is to search in your IDE with the following strings:

All EE filters are prefixed with `FHEE`, so you can search through our codebase for: `apply_filters( 'FHEE_`

All EE actions are prefixed with `AHEE`, so you can search through our codebase for: `do_action( 'AHEE`

**Comment by jonathan-dejong** [comment]
Hi Darren (Yes your code is broken). 

A sad day for me but I see what you mean. Altho you don't really have to make a complete list off the bat. 
Just putting something up now and adding new actions and filters that are developed from this point on would maybe be a bit more manageable.. And then you host an "AfterWork" with beer and the whole shabang where everyone spend an hour or so documenting existing hooks.. Just putting it out there.

**Comment by nerrad** [comment]
> Hi Darren (Yes your code is broken).

No its not.  I do the searches with the partial matches because the part coming after the prefix is dynamic. 

I totally dig how it would be helpful to have some sort of index, organized and categorized.  The problem is we are not a big team and we already put in significant hours getting through the backlog of existing feature requests/bug reports etc.  I'm not saying your idea isn't a good one, it is, but its just not a high priority item when there's so much other stuff to be done :)

**Comment by jonathan-dejong** [comment]
I was referring to your usernames on github.. ;) 

Yeah I get that, and I'm one of those annoying ppl that buggers you about FET and BUG too.
