### ISSUE TITLE
Add content to the beginning of a manual registration in admin

### ISSUE THREAD

**Issue by jonathan-dejong** [eventespresso/event-espresso-core#77]
Hi, 

I'm able to add a login form to the registration on the front-end using this:
```
//Add login form to the checkout stages in EE
add_action('AHEE__SPCO__before_registration_steps', 'add_login_form_to_checkout');
function add_login_form_to_checkout(){
	if(!is_user_logged_in()){
		echo '<div class="ee-checkout-login" id="loginform">';
		echo '<h3>' . __('Har du redan ett konto?', 'sceleton') . '</h3>';
		wp_login_form(array(
			'redirect' => $_SERVER['REQUEST_URI'],
			'remember' => true
		));
		echo '<a href="' . esc_url(site_url('wp-login.php?action=lostpassword', 'login_post')) . '">' . __('Glömt lösenordet?', 'sceleton') . '</a></div>';
	}else{

		$user_meta = wp_get_current_user();
		echo '<div class="ee-checkout-login">';
		echo '<h3>' . __('Du är inloggad som', 'sceleton') . ' ' . $user_meta->user_firstname . ' ' . $user_meta->user_lastname . '</h3>';
		echo '<p><a href="' . wp_logout_url($_SERVER['REQUEST_URI']) . '" data-icon="l">' . __('Logga ut', 'sceleton') . '</a> eller ';
		echo '<a href="' . get_permalink(204) . '">' . __('Redigera din information', 'sceleton') . '</a></p>';
		echo '</div>';

	}
}
```

I have my own WP user integration plugin which is based on your very very beta plugin before you've launched the current stable one. This means that when a user log in many fields are automatically filled in from user meta on their user. Now the client is requestion a version of this when they do a manual registration themselves. Instead of having to log in as the person they are registering to automatically get the information they want like a dropdown on the manual registration page in wp-admin with all the users and when they select one their info is filled in. I can do all that with some custom AJAX etc. etc. but I'm not sure how to get this dropdown into the page. 

Figured you might have a sneaky filter or action laying around..?

**Comment by nerrad** [comment]
What about just using the same filter?  You could put the dropdown in the `else` condition block of your above example?

**Comment by jonathan-dejong** [comment]
I don't think the filter runs in admin.. 
If so I'd see the stuff that's in the `else` condition now but I don't. 
https://dl.dropboxusercontent.com/u/10298919/eescreen.png

**Comment by nerrad** [comment]
Oh sorry, I missed that you wanted this to happen in the admin, I read that "manual registration" meant doing in the admin.

I'll get back to you at some point today.

**Comment by jonathan-dejong** [comment]
Just bumping this issue a bit :)

**Comment by nerrad** [comment]
Hey,

Sorry I didn't get back to you that day, other issues came up needing dealt with and I forgot.

Unfortunately it doesn't look like there is an easy "action" that you can use to add your dropdown.  In the interim what you can do is filter the wrapper template used in the admin for manual registrations.

The wrapper template is `admin_pages/registrations/templates/reg_admin_register_new_attendee.template.php`.  The filter(s) is/are not one(s) we advertise because it can really bork things if not used correctly (due to it being on a core method we use for displaying templates we generally don't want modified).

You can find them in `EEH_Template::display_template()`, the filters are:

`FHEE__EEH_Template_display_template__template_path`
`FHEE__EEH_Template__display_template__template_args`

You likely will only need to use the first one and just filter the original wrapper template to substitute in your own.  Just make sure you keep the existing content (you can tweak if you want but the variables must be present).

The downside to doing things this way is if we ever make changes to this template or to how its setup, you won't get them.

**Comment by tn3rb** [comment]
@jonathan-dejong 
has this issue been resolved for you?

**Comment by jonathan-dejong** [comment]
As far as it can be yes :)

**Comment by tn3rb** [comment]
kk thnx
