### ISSUE TITLE
Datetime filter breaks multiple tickets if max tkt qty is set to 1

### ISSUE THREAD

**Issue by Pebblo** [eventespresso/event-espresso-core#785]
Reported here: https://eventespresso.com/topic/%EF%BB%BFan-error-has-occurred-you-need-to-select-a-ticket-quantity-before-you-can-proc/

If you set the max tkt qty for an event to 1, create enough datetimes tickets (I used 5 datetimes with 1 ticket per datetime) to trigger your 'show datetime selector' the ticket selector can't process any tickets other than the first.

This is my setup - http://take.ms/0ok4M

Frontend - http://take.ms/Q8jiV
(I selected ticket 3)

Ticket 1 works as expected.

Same happens with MER.

To be clear, your 'Show Date & Time Filter?' option in Event Espresso -> Events -> Templates needs to be set to Maybe and your threshold (for the example above) needs to be 5 or below.

If I deactivate that option and refresh the page I have no trouble registering on any ticket.

**Comment by tn3rb** [comment]
I saw this and took a quick look while eating lunch...
There was some Javascript that sets hidden ticket selection quantities to zero when you remove dates using the filter.
The problem is that radio buttons use the "checked" attribute to indicate they are selected and the "value" attribute to denote which input from the group they belong to, which is then required during processing to figure things out. 
Fix was as easy as not setting radio input values to zero when  you use the datetime filter.
