### ISSUE TITLE
REST API cant filter datetimes by deleted field

### ISSUE THREAD

**Issue by mnelson4** [eventespresso/event-espresso-core#811]
## Issue Overview

Queries like this always return an empty set: `/datetimes?where[DTT_deleted]=false` returns an empty set (even when there are definetely non-trashed datetimes) and so does `/datetimes?where[DTT_deleted]=true`.

## Bug report or feature request?

* [x] Bug
* [ ] Feature
* [ ] Neither

## Environment Data:

Version of EE: 
4.9.71

Version of WordPress:
4.9.7
PHP Version:  
7.1
Browser used:  
Firefox/postman

## Steps to Reproduce (for bugs)

1. Create an event with two datetimes, and trash one.
2. Send a request to `wp-json/ee/v4.8.36/datetimes`, you should see the one untrashed one. Then add `?where[DTT_deleted]=false` and somehow you'll get an empty set. Then change it to `?where[DTT_deleted]=true` and it's still empty. Weirdness.

## Expected Behaviour

`/wp-json/ee/v4.8.36/datetimes?where[DTT_deleted]=false` should return undeleted datetimes. And instead using `where[DTT_deleted]=true` should... probably tell you you're not allowed to see deleted datetimes, as they're not visible on the frontend; or maybe show them. It's up for debate, but probably an error would be better.

## Current Behaviour

See steps to reproduce.

**Comment by joshfeck** [comment]
A request to:
`wp-json/ee/v4.8.36/datetimes/?where[DTT_deleted]=0&include=DTT_id`
will get the expected results (use 0 instead of false)

However, it looks like there are some other related bugs with the models or the client code for the UI. What happens is after I trash a datetime in the UI, then look in the database, the DTT_deleted field is still 0 (should be 1) **and** the EVT_ID field is change to 0. 

Along with the above, there's a confusing error message that's shown when you trash a datetime:
> You cannot add this datetime to this ticket because the ticket has a sold amount that is greater than the amount of spots remaining on the datetime.
Which makes no sense in the context of trashing a datetime.

So it appears there's an issue where `false` isn't interpreted as 0, and then some other issues when a ticket is trashed in the event editor UI. 

Maybe we need a few more issues for these other items?

**Comment by sethshoultes** [comment]
Ya, let's create issues for the other items.

**Comment by mnelson4** [comment]
Huh, ya some nutty behaviour there when trashing datetimes. I think that admin code is more Darren's baby. So I'm actually not sure how to create a trashed datetime. 
But I do think it would be best if the REST API interpreted the string "false" to be boolean false.

**Comment by mnelson4** [comment]
Ok I created a PR that should address my original issue. We can follow up with Darren about those other issues Josh noticed, although they might not be a big deal if no one has noticed them.

**Comment by joshfeck** [comment]
Fixed in #977
