### ISSUE TITLE
Change All CSV Reports button text and explain report features in Help section

### ISSUE THREAD

**Issue by joshfeck** [eventespresso/event-espresso-core#838]
See related issue in ES:
https://github.com/eventespresso/eventsmart.com-website/issues/345

**Is your feature request related to a problem? Please describe.**

Yes.
**Describe the solution you'd like**

1) Change the button text from:
`All Registrations CSV Report`
to
`Registrations CSV Report for All Events`
2) Add a new section to the Help tab, "Registration CSV Reports" and explain what's included in the reports. a) differences between filtered & not filtered buttons, and which reg. statuses are included.

**Comment by joshfeck** [comment]
Also should update the Event Check-ins admin page with new information about what's included in the reports generated from that page.

**Comment by garthkoyle** [comment]
I'm not sure just changing the names of the buttons really clarifies what is reported to csv. What if we changed the export UI so that it is a radio select option that can be more descriptive,  then a `Generate Report` button? For example (this example uses checkboxes 

Reports:
* All Registrations (excluding failed or abandoned transactions).
* The filtered list as shown on the screen.

Note: Those descriptions may not be fully accurate. But the format should illustrate the layout that can accommodate a longer description of the output.
