### ISSUE TITLE
Allowing viewing a single transaction if `ee_read_transaction` cap is set to user account

### ISSUE THREAD

**Issue by joshfeck** [eventespresso/event-espresso-core#847]
Originally reported in https://events.codebasehq.com/projects/event-espresso/tickets/11352

> If the user account has ee_read_transaction but does not have ee_read_transactions, then the View Transaction button is displayed within the single Registration record. We expect the button to be displayed, but what's not expected is the error message that results when you click on the button: “Sorry, you are not allowed to access this page.”

Right now you need both `ee_read_transaction` & `ee_read_transactions` to view that single transaction. 

One gotcha we'll need to be aware of is the single transaction page has links to page through other transactions. Those links may need to be conditionally removed once it's possible to view a single transaction without the `ee_read_transactions` cap.

**Comment by nerrad** [comment]
One issue here is that `ee_read_transaction` has been implemented like a meta capability primitive (passing along a transaction id in the current_user_can call in some cases) but is not actually a meta capability AND it is added directly to a user role (whereas meta capability primitives should not be on a role - but rather the meta capabilities themselves - eg `ee_read_others_registrations`)  think this stems from some experimental work with connecting a transaction to an event author via the registration in determining whether the user can actually read a specific transaction.  Then we have `ee_read_transactions` which is for general access.

So I think the resolution here will be to:

- Don't add `ee_read_transaction` to default roles.
- Register `ee_read_transaction` as a meta capability primitive, but for now just have it always check for if the user has the `ee_read_transactions` role and grant access that way.

The impact here:

- If the user only has the `ee_read_transaction` capability on their role and NOT the `ee_read_transactions`, then some items they were able to see prior to the change will no longer be visible (i.e. View Transaction button) but that should be desirable because they woudn't have been able to access the resulting view anyways.

**Comment by nerrad** [comment]
Thoughts on this @joshfeck ?  I think this also impacts #846

**Comment by joshfeck** [comment]
It sounds like the impact will actually fix #846.

**Comment by nerrad** [comment]
To be clear, I'm also wondering if the approach I'm suggesting as a resolution sounds okay from a customer support perspective (noting the impact)?

**Comment by joshfeck** [comment]
What other impact will there be besides "If the user only has the ee_read_transaction capability on their role and NOT the ee_read_transactions, then some items they were able to see prior to the change will no longer be visible (i.e. View Transaction button)"?

**Comment by nerrad** [comment]
Basically if we search through the code for anything that has an `ee_read_transaction` capability requirement, after this change, the user would also require an `ee_read_transactions` capability.  That's what the impact is.  I can take some time to document all the places that will affect if needed?
