### ISSUE TITLE
Fatal error in `ProcessTicketSelector::addTicketsToCart()`

### ISSUE THREAD

**Issue by tn3rb** [eventespresso/event-espresso-core#892]
**Describe the bug**
While troubleshooting another issue, the following error was spotted in the EventSmart error logs:

```
PHP Fatal error: Uncaught TypeError: 
Argument 1 passed to EventEspresso\modules\ticket_selector\ProcessTicketSelector::addTicketsToCart() must be of the type array, boolean given,
called in /dom16036/wp-content/plugins/event-espresso-core/modules/ticket_selector/ProcessTicketSelector.php on line 213
and defined in /dom16036/wp-content/plugins/event-espresso-core/modules/ticket_selector/ProcessTicketSelector.php:403
```
The error occurs because if an invalid Ticket Selector Event ID is passed to `EventEspresso\modules\ticket_selector\ProcessTicketSelector::validatePostData()`, then that method returns false, whereas it otherwise returns an array. The boolean `false` value is therefore not being handled properly by `addTicketsToCart()`.

To correct the issue, the following steps should be taken:

- the return data type for `validatePostData()` should be consistent and return an empty array instead of `false` 
- `addTicketsToCart()` should then detect an empty array being returned and not proceed with processing ticket selections

**Comment by joshfeck** [comment]
I wonder if someone manipulated the form inputs and removed the `tkt-slctr-event-id` input from the form? In any case this sounds like it'd be a quick, zero-impact fix. This could probably be fit between larger high priority work.

**Comment by joshfeck** [comment]
This is actually an error that happens if the event is expired. In other words, the ticket sale end date hasn't passed yet, but the event's datetime end date is past. 

Also reported here:
https://eventespresso.com/topic/manual-registration-from-admin-error-message/
and here:
https://eventespresso.com/topic/add-new-registrations-to-the-past-event/

**Comment by joshfeck** [comment]
Maybe we could change this to allow adding registrations in the admin if the tickets are still on sale, but the event is expired?

**Comment by joshfeck** [comment]
A minor clarification: It doesn't appear to matter whether the ticket sale end dates are past, present or future. The "Add Tickets and Continue to Registrant Details" button is always shown regardless of whether the event is past, present, between datetimes, or future.

**Comment by joshfeck** [comment]
Mentioned earlier:

> To correct the issue, the following steps should be taken:

- [ ] the return data type for validatePostData() should be consistent and return an empty array instead of false
- [ ] addTicketsToCart() should then detect an empty array being returned and not proceed with processing ticket selections

We'll also look into reworking the admin ticket selector to allow for adding the #731

**Comment by sethshoultes** [comment]
Aha, you're right @joshfeck. It is broken in master. I'll create a separate issue.
