### ISSUE TITLE
Question: Are there any filters on the CSV output for registrations?

### ISSUE THREAD

**Issue by richardtape** [eventespresso/event-espresso-core#90]
Specifically, I'm looking to remove (quite a few) columns from the output. I've had a look through but can't seem to see any. Have I missed any? Ideally I'd also like to be able to inspect and modify the data before it gets passed into the export routine (to perhaps add other metadata i.e. I can get a user ID based off the fields that are submitted - everything for us is behind a log in screen).

If there aren't any, can you point me in the direction as to where I could add them and create a PR?

Thank you as always. Happy Friday!

**Comment by tn3rb** [comment]
our CSV import / export systems utilizes the following classes:

 * /core/db_classes/EE_CSV.class.php
 * /core/db_classes/EE_Export.class.php
 * /core/db_classes/EE_Import.class.php

but is currently undergoing a lot of changes due to some issues. 

the best recommendation for you at this point is probably to copy code out of the export class and create your own method for exporting just the content you want.

it's unknown whether any pull request you made against master would make it back.

if you want to see some of the changes in progress, you can have a look at:
https://github.com/eventespresso/event-espresso-core/tree/BUG-7537
but plz note that this is still under development and has not been through any thorough testing yet.

**Comment by richardtape** [comment]
Thanks for getting back to me so quick, I really appreciate it. will 
take a look at the classes you mentioned and see what our best foot 
forward is.

Brent Christensen wrote:
