### ISSUE TITLE
Reduce/remove caching of max_input_vars value

### ISSUE THREAD

**Issue by Pebblo** [eventespresso/event-espresso-core#908]
Currently, the server's `max_input_vars` value is saved within EE Config.

If you manage to throw the  "more inputs than your server's max_input_vars" notice and then you change the value on the server you still get the notice on the event editor until you rebuild the config.

Can we change this so the value updates when the event editor is loaded?

**To Reproduce**
Set max_input_vars to 200 on your server.

Go to Event Espresso -> General Settings, make a change and save (to rebuild the config)

Create a new event and you'll likely get the notice straight away with it that low, if not click to duplicate datetimes a few times, the notice should throw and show that max_input_vars is 200.

Now update the server to use 1000 (or more) for your max_input_vars value again.

Don't visit General Settings and just refresh the event editor/create a new event.

You should still get the notice showing that max_input_vars is 200 even though its not.

Again visit General Settings, make a change and save.

Repeat the above an no more notice until you hit 1000 inputs or whatever value you used.

**Comment by joshfeck** [comment]
whoa, I guess my reply got eaten!

If I remember correctly, my comment was I didn't think we should update the options every time we load up the event editor. The reason being is because changing the max_input_vars should be a one-time change. So after they make that change the options will continuously refresh every time they open the event editor, for no reason.

What we could do instead is add to the "The maximum number of inputs on this page has been exceeded. " messaging. Right now it gives no instructions, so we could add to that modal to include:
1) Instruction to contact their web host to bump that limit
2) Then provide a button to click that will refresh the max_input_vars option stored in settings, with instruction to click the button after the change is verified.

How does that sound?
