### ISSUE TITLE
Fix: Ignore `password` parameter on collection endpoints for REST API requests

### ISSUE THREAD

**Issue by nerrad** [eventespresso/event-espresso-core#917]
**Describe the bug**

In #804, handling of password protected entities was added to our REST API and it contains a feature described in the pull:

> all REST API requests allow you to pass a password query parameter. If this does not match the password that protects that data (eg on events that's the password field, or datetimes its their event's password field, on tickets it's their datetime's event's password field), an error response is returned. If it does, you are permitted to see the password-protected data. Note, the following are valid requests: wp-json/ee/v4.8.36/events?password=mypassword, /wp-json/ee/v4.8.36/datetimes?password=mypassword, wp-json/ee/v4.8.36/events/1/datetimes?password=mypassword and wp-json/ee/v4.8.36/events?include=Datetime&password=mypassword. BUT if that password isn't correct any single item returned, the entire REST response will be replaced with an error messsage. So wp-json/ee/v4.8.36/events?password=mypassword will return an error if that is NOT the password for any of the events retrieved. This makes brute force attacks more difficult.

A problem with this behaviour on collection endpoints is that it effectively means that when the collection endpoint query results in **multiple** entities that are password protected, there's will _always_ be a 403 response.  For now, I think it would be better if we just ignore the password parameter on _collection_ endpoint requests and always return protected results instead of an error.  The feature as it is, is mostly useless (for collection endpoints).

In a separate pull I think we'll need to consider having correctly authed users disable the password protection on collection endpoints (maybe for `read_admin`, and `edit` contexts only?) as that will be needed in certain contexts.

**To Reproduce**

1. Create multiple events that have password protection and a different password for each event.
2. Do a `GET` request on the events collection endpoint (`ee/v4.8.36/events`) adding a `password` query parameter with the password for one of the events.
3. Note that the entire response is 403.  Nothing you do can change that apart from removing password protection from one of the events or removing the usage of the `password` query parameter.

**Expected behavior**

Expect that for **collection** endpoints only, the `password` query parameter is ignored and the protected results are returned.

**Environment:**
 - Version of Event Espresso:  4.9.78.rc.003
 - Version of WordPress:  5.0.3
 - PHP Version  7.3

**Comment by joshfeck** [comment]
> For now, I think it would be better if we just ignore the password parameter on collection endpoint requests and always return protected results instead of an error

Can you clarify? Does this mean it'd show all the content for that event anyway, or instead show no private information and instead show something to the effect of "This content is protected"?

**Comment by joshfeck** [comment]
@mnelson4 can you give this a 1, 10, or 100 based on estimated effort to fix this?

**Comment by mnelson4** [comment]
Thanks for the feedback @nerrad, and outlining the desired behaviour.

> A problem with this behaviour on collection endpoints is that it effectively means that when the collection endpoint query results in multiple entities that are password protected, there's will always be a 403 response.

Unless they have the same password, which somewhat common for events (in WordPress' web-ui, if you provide the password to one password-protected post, then when you visit another post that uses the same password, you aren't asked to provide the password). It's very common for datetimes and tickets etc, seeing how the can be many that relate to the same password-protected event.

So it seems to me, the `password` query parameter it useful for collection endpoints if it's thought that all the entities (events, datetimes, etc) use the same password. In other cases, it shouldn't be used.

The downside to not having an error when a collection endpoint receives an incorrect password, and instead just omit the password-protected data for which the password was incorrect, is that it can be used for password guessing. Eg if a site has 100 events each with different passwords, every request to `/events?password=guess1` would be effectively trying that password on all 100 events (because client-side code could loop through the events and find when a protected event's content has been revealed.)

If there's something I'm overlooking and we need to implement this, I'm not totally sure how I'd do this. But I think it would probably be a couple well-placed changes, not a total overhaul.

I think it would help me to understand the situation that makes this appear to be a problem. Because in my head, usually API clients just wouldn't provide the password query parameter. To my understanding, that would give the desired behaviour: all the entities are returned, except password-protected parts (on some endpoints, like events, that means some of their content is protected; on other rendpoints, like datetimes, that means some entities are remove entirely.) Is there a reason this isn't good enough?

> In a separate pull I think we'll need to consider having correctly authed users disable the password protection on collection endpoints (maybe for read_admin, and edit contexts only?) as that will be needed in certain contexts.

+1 that. I find that growing on me (in my related pet project where I'm also consuming the WP REST API, this behaviour is a pain).

**Comment by mnelson4** [comment]
We discussed in Slack, and basically:
* Darren and Josh felt having `password` on any top-level collection endpoint (eg /events or /registrations) was confusing, especially how there is an error returned if any item doesn't match that password
* they thought it would be very rare for posts to have the same password, making the feature not very useful (although it's certainly more useful for data related to events, like datetimes, where, because an event can have many datetimes, it will be quite common for datetimes to share the same event and password)

I didn't think it's that confusing, but I'm biased. Also I thought it's quite possible events will share the same password.

Also, Darren was wanting to only accept `password` on related endpoints, but not top-level endpoints. Meaning `/datetimes?where[EVT_ID]=1&password=1` wouldn **not** be permitted, but `/events/1/datetimes?password=1` would be. To me, that's inconsistent because the two routes are otherwise identical, the related endpoint is really just there for convenience.

The compromise seemed to be: don't document the `password` query parameter on top-level collection endpoints (in either our docs or the schema), but still accept it.
