### ISSUE TITLE
Hide Most of the Event Editor Notice, Add Read More Link, Expand with JS

### ISSUE THREAD

**Issue by garthkoyle** [eventespresso/event-espresso-core#918]
## Issue Overview

![image](https://user-images.githubusercontent.com/3094547/51765207-6730a280-2094-11e9-8afa-72ac5ebd8b85.png)

The intention is to simplify the event editor notice that appears when editing a published so that the warning: takes up less screen real estate, reduces distractions, lessens warning fatigue, provides more space for the editor settings without scrolling, and has no impact on translations.

## Bug report or feature request?

* [ ] Bug
* [ ] Feature
* [x] Neither

## Environment Data:

Version of EE: master
Version of WordPress: trunk
PHP Version:  n/a
Browser used:  n/a

## Expected Behaviour

After talking to Josh about this on Slack, he recommends:

> As far as the real estate goes, we could take this approach, which will not break existing translations: 1) Add a (read further) link, 2) add some JS to hide most of the message where the (read further) link can expand the warning to full view.

That would reduce the amount of screen space dedicated to a warning that appears every time you edit a published event, even if you're fully aware of the warning.

## Current Behaviour
The full warning text shows each time you edit a published event.

## Related Information:
See also: https://events.codebasehq.com/projects/event-espresso/tickets/4979#update-55724423

**Comment by joshfeck** [comment]
Here's a quick and dirty codepen to help explain what Garth is asking here:

https://codepen.io/joshfeck/details/vbLeOw

**Comment by nerrad** [comment]
@joshfeck  this is turning out to be a bit more involved than I thought initially. Primarily for the following reasons:

- We need a way to only designate certain notices as "collapsible".
- The EE notice system condenses multiple notices on the same request into the same container for the notice type.  This doesn't apply as much here because _currently_ we only have the single attention type _for this view_.
- I could add additional logic for designating a notice as a "collapsible" notice so I can make this work but that does not extrapolate well for if/when this would get used in other places (meaning we are adding logic to fit a specific use-case that likely won't work for all use-cases).
- We've bandied refactoring our notices framework elsewhere (but it hasn't gone anywhere... still I'm hesitant to do _too_ much work in the existing notices system in light of that).
- WP notices are under review.
- The EE event editor is probably going to be refactored at some point too.

So in light of all that, it's not a quick fix/win. 

Alternatively, for this _specific_ notice, we could simply convert to doing a native WP admin_notice and make it collapsible.  That _might_ be doable more quickly if that's decided as an acceptable route to take.  Then if we find there are more areas we want to do collapsible notices I could simply abstract this into it's own (gasp) helper method until we resolve what we're going to do with notices in general. 

Thoughts?

**Comment by nerrad** [comment]
Another option would be to just remove this warning altogether?  Is it needed now that there is more protections in place against overselling?

**Comment by nerrad** [comment]
Ya that sounds like a good resolution for this.  Will need some direction on what the new message should be.

I've adjusted the estimate according to what I think it'd take for adding this.

**Comment by joshfeck** [comment]
I made a P2 to see if anyone wants to discuss what the new message should be:

http://p2.eventespresso.com/2019/02/05/new-warning-for-editing-events-see-https/
