### ISSUE TITLE
Payment module integration questions

### ISSUE THREAD

**Issue by jonmixnblend** [eventespresso/event-espresso-core#97]
Hi, I've recently been developing some payment methods for some friends of mine [City Soiree](http://citysoiree.co.za/) in Cape Town as a favour.

I’m almost done with the first gateway out of two, which is an integration with [PayU - South Africa](https://payu.co.za/). I just wanted to ask a few questions if possible that I can’t find in the [docs](http://developer.eventespresso.com/docs/ee4-payment-method-development/).

## Payment Form - Customisation

- I just wanted to ask, I would be quite keen to use [this client side validation library from Stripe](https://github.com/stripe/jquery.payment) in the PayU payment method. Now that necessitates changing the template of the billing form somewhat and adding space for error message divs etc? Is that possible, and if so which template would I have to over-ride or change?
- Secondly, obviously that’s a Javascript library. At what point or during which method call should I enqueue that Javascript and do I just do that by hooking a Wordpress hook in the standard way? From digging in the core I see there is a common method that seems to do that on some classes? load_scripts_styles() I think?

## Second Payment Method - Snapscan

- The second question I wanted to ask is in relation to whether it would be possible to or how you would work a payment method like [Snapscan](http://www.snapscan.co.za/) into your payment flow. Basically Snapscan is a mobile payment method in wide use in South Africa and how it would work with online payments is as follows:

1. At the point of your billing form getting rendered, make a call to the Snapscan API with your access token, and the amount you wish to bill for. A QR code link comes back which is then shown on the page.
2. User uses their phone with the snapscan app to take a picture of the QR code and pays using the app.
3. Snapscan then sends an message to an endpoint of your choosing (like an IPN) and you then handle that mesage and return a 200 response.

Now I know that you guys have support for IPN like messages built into your payment flow, but what I would like to know in short is:

- How would it be easiest to customise that billing form to get that QR code up at that point.
- How The system then takes action once it gets a message from the gateway.

Sorry I feel like I’ve probably missed something very obvious here, so please feel free to tell me if I have.

## Payment Status Updates

I see from the mockup that depending on responses from the Gateway (Timeout, declined, etc etc) in do_direct_payment You can update the payment status to declined, accepted etc etc. However if it’s declined and you set that in that method, you seem to get one error message telling you this (that I return) and then if you try and enter your details again and are declined a second time, your order is listed as processed, but with a status of payment declined. I mean, the order seems to be created, but with that status. Is that expected behaviour? Would you not want to hold the process up at that form until they got their details correct? Am I perhaps setting payment statuses incorrectly in that method?

**Comment by mnelson4** [comment]
hi @jonmixnblend 
Regarding "Payment Form - Customization":

before embarking on using another javascript library for performing client-side validation, I think you should know a little more about what EE4's form system can already do for you: it already handles client-side validation using jQuery validate for validating credit card numbers, CVVs, phone numbers, etc. In our documentation it tells you a little about how to create a billing form for your payment method: http://developer.eventespresso.com/docs/ee4-payment-method-development/#generate_new_billing_form. I JUST added another link in to our Form System documentation, which explains how to set your form up to do client-side and server-side validation, and how to customize the display of the form: http://developer.eventespresso.com/docs/ee4-forms-system/. Specifically, in there you'll notice there are already credit card inputs, cvv inputs, credit card date inputs, etc, which are auto-loaded and ready for use in your code.

Regarding "Second Payment Method - Snapscan"

Huh this sounds like quite a unique integration. It's not a normal ONsite payment method because billing info ISN'T being entered on the wordpress site, and it's not a usual OFFsite payment method because the user's browser isn't being redirected - we're just wanting to do some server-side logic, and  then display some payment instructions with an QR code image in them (instructing them to use their smartphone with the Snapscan app), and then once they're done using Snapscan to proceed to the thank you page.
So it actually sounds like an Offline payment method, because it doesn't interract with the gateway servers in the same way as Onsite or Offsite payment methods, and even though it DOES interract with the gateway but only when displaying the payment instructions.
So here's what I'd do: 
- create an OFFLINE payment method, 
- but override the `generate_new_billing_form( EE_Transaction $transaction, $extra_args) `. If the `$extra_args['amount_owing']` is set, use it as the payment's total, otherwise use `$transaction->remaining()`. And with this, send a request to Snapscan using the function `wp_remote_request`. Find the QR code image and return a billing form with an `EE_Form_Section_HTML` containing that scan, as well as instructions telling the user to use their snapscan app to scan it, and once they're done to click "Proceed" (or you could setup some javascript code to ping the server to see when the payment gets approved, adn which point the browser would automatically redirect to the thank you page)
- override the payment method's `handle_ipn($req_data,$transaction)` method to directly handle the IPN request once it gets sent in. If you sent a URL like this to Scanpscan `EE_Config::instance()->core->txn_page_url(
						array(
							'e_reg_url_link' 				=> $transaction->primary_registration()->reg_url_link(),
							'ee_payment_method' 	=> $payment_method->slug()
						)
					)` then EE will take care of making your payment method's `handle_ipn` method gets called when the IPN is received (you can also check the payment logs in the wp admin -> event espresoso -> payment methods -> logs)
Make sense?

And re "Payment Status Updates"
Each time an onsite payment method attempts a payment and it gets declined, the results SHOULD be the same: they should stay on the payment options step of SPCO until it gets approved. If you're seeing the user get redirected to the thank you page after the 2nd declined payment that's a bug and should be reported in a separate ticket. However, when payment is first attempted, the order needs to be created and saved to the database (so that we have something to attach the logs to, to reserve the spots, etc)

**Comment by jonmixnblend** [comment]
Thank you so much:)

That pretty much answered everything I needed to know. Hope you're having a good day that side.

Re: that redirection to the thank you page I will test that some more and if it is a bug rather than something stupid I am doing I will revert and submit a ticket.

Oh lastly, your guys product seems to be really well put together. Thanks, you guys really helped open up the music scene down here in Cape Town. Those two friends of mine who I'm working on this for used it to create a crowd funded gigs site, where people can pledge to see their favourite musicians in houses, non traditional music venues, etc. It's changed the whole way shows are put together here, as now the musicians involved kind of know the gig is funded before the event happens, and gets a fair payout.

If you're interested in taking a look check out [http://www.citysoiree.co.za](http://www.citysoiree.co.za) 

Best
Jon

**Comment by mnelson4** [comment]
cool! Maybe you want to post a review on wordpress.org for the EE4 plugin? https://en-ca.wordpress.org/plugins/event-espresso-decaf/ (need to login to post a review)

Also when you're done these payment methods, consider submitting them to our third-party addons page and selling them: http://eventespresso.com/third-party-addons/ (or if you'd rather not sell them and support them, putting them on github or wordpress.org's plugin repo would be good too, probably get some help maintaining them)

**Comment by jonmixnblend** [comment]
I will do for sure.

Thanks again:)

best
Jon

On Mon, Jul 20, 2015 at 11:33 PM, mnelson4 <notifications@github.com> wrote:

> cool! Maybe you want to post a review on wordpress.org for the EE4
> plugin? https://en-ca.wordpress.org/plugins/event-espresso-decaf/ (need
> to login to post a review)
>
> Also when you're done these payment methods, consider submitting them to
> our third-party addons page and selling them:
> http://eventespresso.com/third-party-addons/ (or if you'd rather not sell
> them and support them, putting them on github or wordpress.org's plugin
> repo would be good too, probably get some help maintaining them)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/eventespresso/event-espresso-core/issues/97#issuecomment-123049866>
> .
>



-- 

*Email:* jon@mixnblend.com

*Phone: *+27 76 393 3300

*Skype: *jonbreakdesign

**Comment by mnelson4** [comment]
hey @jonmixnblend are you "dkoyle" on wordpress.org? was that review yours? https://wordpress.org/support/view/plugin-reviews/event-espresso-decaf?filter=5

**Comment by jonmixnblend** [comment]
Hey hey

No that wasn't me. I've kind of been tied up on some development work since
I mailed you. As I said, I'm doing these gateway methods for my friends as
a favour, so I get to them when I can.

I'm going to get both of them to write a review for you though, will let
you know when they have for sure.

best
Jon

On Tue, Jul 28, 2015 at 10:16 PM, mnelson4 <notifications@github.com> wrote:

> hey @jonmixnblend <https://github.com/jonmixnblend> are you "dkoyle" on
> wordpress.org? was that review yours?
> https://wordpress.org/support/view/plugin-reviews/event-espresso-decaf?filter=5
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/eventespresso/event-espresso-core/issues/97#issuecomment-125740683>
> .
>



-- 

*Email:* jon@mixnblend.com

*Phone: *+27 76 393 3300

*Skype: *jonbreakdesign
